### ISSUE TITLE
Spaces in project names replaced with dashes (' ' -> '-')

### ISSUE THREAD

**Issue by kayvonkhosrowpour** [checkmarx-ltd/cx-flow#1003]
### Description

Using CxFlow with docker `cxflow:latest`, if a CX project name with a space (e.g. `project with space`), then cxflow will create a project in Checkmarx with dashes in place of the spaces (`project-with-space`).

### Expected Behavior
It would be desired to turn off this replacement, so projects can have spaces in their names. Instead of `project-with-space`, it would keep the spaces as `project with space`.

### Actual Behavior
Spaces in project names are replaced with dashes: `project-with-space`.

### Reproduction

Simply `exec` into the `cxflow:latest` docker container and run:
```
CX_PROJECT="project with spaces"
CX_TEAM=<YOUR TEAM>

java -jar /app/cx-flow.jar \
    --scan \
    --bug-tracker="Csv" \
    --csv.file-name-format="[TEAM]-[PROJECT]-[TIME].csv" \
    --csv.include-headers="true" \
    --csv.data-folder="checkmarx" \
    --app="${CX_PROJECT}" \
    --cx-team="${CX_TEAM}" \
    --cx-project="${CX_PROJECT}" \
    --spring.profiles.active="sast" \
    --f=.
```

### Environment Details

Latest docker image: `cxflow:latest`.

**Comment by jbrotsos** [comment]
Hey @kayvonkhosrowpour, please use the flag: 

 preserve-project-name: true

https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration
