### ISSUE TITLE
Github - Scan is not initiated when base branch is changed in the PR

### ISSUE THREAD

**Issue by y4ppieflu** [checkmarx-ltd/cx-flow#1006]
### Description

CxFlow only initiates the scan when pull request status received via Webhook from Github is one of (https://github.com/checkmarx-ltd/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L121):
- opened
- reopened
- synchronize

This does not cover the case when PR is initially opened into a different branch (e.g. branchA) and then gets re-based to the master. 

### Expected Behavior
CxFlow initiates a scan when:
- The new PR is opened from branchA to branchB
- branchB is merged into master and gets deleted
- branchA is automatically rebased to master

### Actual Behavior
Scan is not initiated in the mentioned scenario, the following message is logged:
`Pull requested not processed.  Status was not opened (edited)`

### Reproduction

- Configure a webhook for Github repository, that triggers CxFlow
- Configure CxFlow to scan master
```
cx-flow:
  branches:
    - master
```
- create branchA and branchB
- create a pull request (PR1) from branchA to branchB
- create a pull request (PR2) from branchB to master
- merge PR2 and delete branchB
- observe that scan is not initiated when PR1 is rebased to master (though branch protection rules for master still apply)

### Environment Details

CxFlow ver. 1.6.33

**Comment by itsKedar** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
