### ISSUE TITLE
Expose Prometheus metrics under /actuator/prometheus

### ISSUE THREAD

**Issue by hrabo** [checkmarx-ltd/cx-flow#1011]
### Describe the problem

Prometheus metrics are not exposed under `/actuator/prometheus`. The URL returns 404.
The `micrometer-registry-prometheus` needs to be added as a dependency. 
Here is the official Spring Boot documentation that states that the dependency is needed:
https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints

### Proposed solution

Add the `runtime ("io.micrometer:micrometer-registry-prometheus:1.8.5")`

**Comment by satyamchaurasiapersistent** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
