### ISSUE TITLE
Implement delta findings report (only changes between new, recurring and resolved) for GitHub

### ISSUE THREAD

**Issue by cx-leonelsanches** [checkmarx-ltd/cx-flow#1021]
### Describe the problem

Client wants the same delta report already implemented in AST. Only new findings, or findings with statuses changes, should be listed in this report.

### Proposed solution

New implementation, with the respective configurations in GitHub section.

**Comment by satyamchaurasiapersistent** [comment]
Hi @cx-leonelsanches can u please specify you requirements in detail.
