### ISSUE TITLE
Jira-assignee not working for Jira On-Prem instances

### ISSUE THREAD

**Issue by mgonzalezcx** [checkmarx-ltd/cx-flow#1024]
### Description
Cxflow is not assigned Jira tickets that are created to the user specified in the jira-assignee value. I have successfully tested with jira cloud but when I tried using the same configuration for jira on-prem it does not work. I tried providing the following valuesa as the jira-assignee: username, email address, account ID. None of these values worked to set a jira assignee. 

Instead of assigning it to the user specified, it assigns it to the project owner for some reason. 

### Expected Behavior
Be able to use the jira-assignee value to set the assignee on the jira ticket for Jira On-Prem

### Actual Behavior
The jira-assignee value is ignored and a default user is used to assign the ticket. 

### Reproduction
1. Use JIRA as bug tracker
2. Set a jira-assignee value
3. Initiate cxflow in project mode to create tickets
4. see that the jira-assignee value is not set to the correct user

### Environment Details

This happen for Jira On-Prem instances only.

**Comment by cx-scord** [comment]
@mgonzalezcx Did you use the `jira.assignee` property in the `jira` block?

This might works:
```yaml
jira:
  (...)
  assignee: <JIRA_USERNAME>
  (...)
```

The one you are mentioning is the `checkmarx.jira-assignee-field` and that might not work.

**Comment by mgonzalezcx** [comment]
@cx-scord I did try adding the jira.assignee to the jira block and passing it in as parameter. I was able to assign to the correct user when using a jira cloud instance but NOT when using on-prem. I saw the same behavior for the checkmarx.jira-assignee-field, it works fine for jira cloud but not jira on-prem.

**Comment by cx-scord** [comment]
@mgonzalezcx Thanks for confirming.

**Comment by itsKedar** [comment]
@mgonzalezcx  Jira tickets can be assigned to a user when they are only created. This can be achieved in the following way.

1) As a webhook url parameter - The url parameter 'assignee' can be appended to the url in the webhook configuration and a user's email address to whom the tickets should be assigned in cloud and username in on-prim, is provided as the value of the parameter.

> http​﻿://companyname.checkmarx.com?assignee=someUsersEmail@﻿xyz.com

for On-prim

> http​﻿://companyname.checkmarx.com?assignee=someUserName


2) For CLI --assignee cmd parameter can be used to assign the Jira ticket when they are created. This parameter can be used for scan, project , batch modes

For Cloud
> java -jar cx-flow-1.6.36.jar --spring.config.location="C:\Cx-Flow\Jar\application.yml" --scan --github --repo-name="someRepoName" --namespace="NameSpace" --repo-url="https://github.com/YourGitURl.git" --cx-project="YourProjectName" --branch="master" --assignee="EmailAddressToAssign" 


For On - Prim 
> java -jar cx-flow-1.6.36.jar --spring.config.location="C:\Cx-Flow\Jar\application.yml" --scan --github --repo-name="someRepoName" --namespace="NameSpace" --repo-url="https://github.com/YourGitURl.git" --cx-project="YourProjectName" --branch="master" --assignee="UserName"

3) As adding Custom Checkmarx field name 'jira-assignee' and setting value for this field as user's email address to whom the tickets should be assigned in cloud and username in on-prim

All the mentioned parameter are tested and are working on both cloud and on-prim

**Testing details** 
on-prim Jira server 9.2.0
SAST server 9.4

Please mention all environment details if problem still exist.

**Comment by itsKedar** [comment]
Fixed in 1.6.40 release
