### ISSUE TITLE
Support Bitbucket Issues bug tracker

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#1028]
### Describe the problem

> There is no bug-tracker for the Bitbucket Issues.

### Proposed solution

> Add bug-tracking capabilities to CxFlow for Bitbucket, similarly to other SCMs already implemented.

**Comment by itsKedar** [comment]
Hi 

There are no issues for bitbucket. In case of bitbucket issues gets logged in JIRA. 

Thanks
