### ISSUE TITLE
Map labels on bug trackers like Github Issues or Gitlab Issues

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#1029]
### Describe the problem

There's no capability of mapping labels (custom labels or coming from SAST/SCA results) to Github Issues or Gitlab Issues or any other bug-trackers like there is in JIRA.

### Proposed solution

 Be able to map labels to other bug-trackers issues similarly to what is done in JIRA, either by adding custom mapping them in `cx.config` file for config-as-code be it. This could be done similarly like jira, where fields can be set either statically, by using SAST custom fields or from the SAST, SCA, or any other supported product's vulnerability results.

### Additional details

Just as a request, the priority to consider when implementing this FR could be in this order: 

1. Github Issues
2. Gitlab Issues
3. ADO WorkItems 
4. (and Bitbucket Issues, if it is implemented #1028)
5. Others

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
