### ISSUE TITLE
JIRA SCA tickets contains the team configured for CXSAST 

### ISSUE THREAD

**Issue by luisgarciacheckmarx** [checkmarx-ltd/cx-flow#1033]
### Description

When running CxFlow   with
enabled-vulnerability-scanners:
    - SCA
    - SAST

and teams are different between SCA and SAST

sca:
  team: "/CxServer/sast"

checkmarx:
  team: /CxServer/sca

SCA tickets in Jira contains 
Cx-Team: /CxServer/sast"

Instead, if only running SCA, SCA Jira tickets do not contain any Cx-Team data (i.e. Cx-Team does not appear)

### Expected Behavior

SCA Jira tickets should show Cx-Team: /CxServer/sca, not /CxServer/sast

**Comment by itsKedar** [comment]
fixed in 1.6.36
