### ISSUE TITLE
Support the zip-excludes property via config-as-code

### ISSUE THREAD

**Issue by james-bostock-cx** [checkmarx-ltd/cx-flow#1034]
### Describe the problem

CxFlow provides a `zip-exclude` property which specifies a list of regular expressions. When creating the zip file to send to CxSAST for scanning, CxFlow checks each file against each regular expression and, if there is a match, the file is excluded. The `zip-exclude` property may be specified in the `application.yml` file, on the command line, or via an environment variable. It cannot, however, be provided via the `cx.config` config-as-code file, which is precisely what one of our customers has requested.

### Proposed solution

There may be a more elegant approach than:

- Add a `zipExclude` property, with associated getter/setter to the `FlowOverride` and `ScanRequest` classes.
- Modify the `applyFlowOverride` method of the `ConfigurationOverrider` class to set the request's `zipExclude` property if it has been 
set in the `cx.config` file.
- Modify the `scanLocalPath` method of the `AbstractVulnerabilityScanner` class to use the request's `zipExclude` property, if set, in preference to the flow properties `zipExclude` property.

### Additional details

N/A

**Comment by itsKedar** [comment]
Duplicate for https://github.com/checkmarx-ltd/cx-flow/issues/1043
