### ISSUE TITLE
Allow comments to be passed as an argument

### ISSUE THREAD

**Issue by octa** [checkmarx-ltd/cx-flow#1046]
### Describe the problem

>A lot us use the scan comments field to store metadata about the scan. CxFlow allows one to set the comments but it involves invoking a Groovy script which might not be desirable.
>Example, if one is running a gradle build and using the Nebula plugin to publish, they already know the version. The Groovy script is an overhead.

### Proposed solution

>Add an option to pass the comment when running CxFlow.
>Example, `java -jar CxFlow.jar ... --comment="Scan for release candidate"`.
```
VERSION=$(cat version.txt)
java -jar CxFlow.jar ... --comment=$VERSION
./gradlew -Prelease.version=$VERSION final
```

### Additional details

>Looking at the code, this change must be trivial and I would be happy to submit a PR if this feature request is approved.

**Comment by satyamchaurasiapersistent** [comment]
We have done this in [1.6.39](https://github.com/checkmarx-ltd/cx-flow/releases/tag/1.6.39)
