### ISSUE TITLE
GitLab merge requests create an endless loop of scans

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1079]
### Description

When opening a merge request in GitLab, there is an endless loop of scans due to the way the title is changed in the PR.  The title change triggers a PR webhook event, which CxFlow handles based on the configured value of `scan-resubmit`.

The scans continually update the PR comments with the new scan findings, update the title, which causes an endless loop of scans.

### Expected Behavior
There should be only one PR scan until the PR is updated with a code change.

### Actual Behavior
When `scan-resubmit` is false, the current PR scan is completed and then a new PR scan is started.  This repeats forever.

When `scan-resubmit` is true, scans are continually started in an uncontrolled loop that repeats forever.

#### With `scan-resubmit` set to false (this is the default setting)

Open a merge request targeting a protected branch.  You will see the following comment entries where the initial handling of the merge request event prepends `WIP:CX|` to the title.  The title update causes another merge request webhook event that is blocked due to an existing scan.  The comment says the scan was blocked, which is expected.  The title is then reset to the original title.

![image](https://user-images.githubusercontent.com/29153509/183942069-ab97a055-3e10-43b0-9878-727553ac8d1c.png)

The CxFlow logic will bypass the merge request event that is sent when the title is reset to the original title.  When the scan is complete, the merge request comment apparently sets the title to an unchanged value which causes another merge request webhook event to emit.  This repeats the scan cycle.  Scans and merge request comments will continually cycle.

#### With `scan-resubmit` set to true

The same cycle as above except the scans are rapidly submitted and the merge request title changed.  I let it run for a while:

![image](https://user-images.githubusercontent.com/29153509/183961585-465b780f-255c-4e37-8843-878fb4918918.png)

The SAST scan queue was flooded with scan requests as expected.

### Environment Details
GitLab non-premium public account.
CxFlow 1.6.35 also confirmed it in 1.6.15.
Webhook settings are `push` and `merge request` only, which is what is shown in the documentation.

**Comment by itsKedar** [comment]
Fixed in 1.6.37
