### ISSUE TITLE
CxFlow 1.6.35 docker image released from a feature branch

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1081]
### Description

The `/actuator/info` endpoint when running the 1.6.35 docker image indicates the image was produced from a feature branch rather than `master`.  The jar indicates it was produced from `master`.

### Expected Behavior

The `/actuator/info` endpoint should indicate the build branch as `master` in both the docker image and the jar release.  Not only is this used for troubleshooting, it indicates that the build process may produce a docker image that functions differently than the jar.

### Actual Behavior

`/actuator/info` endpoint from CxFlow running in the official docker container:
```
{"git":{"commit":{"time":"2022-07-25T10:05:38Z","id":"ac313f6"},"branch":"dockerfix"},"build":{"version":"1.6.35","artifact":"cx-flow","name":"cx-flow","group":"com.checkmarx","time":"2022-07-28T07:07:31.699Z"}}
```

Note the branch element is `dockerfix`.

The results from the same endpoint running with the official jar release:

```
{"git":{"commit":{"time":"2022-07-25T10:05:38Z","id":"ac313f6"},"branch":"master"},"build":{"version":"1.6.35","artifact":"repo","name":"repo","group":"com.checkmarx","time":"2022-07-25T11:31:08.628Z"}}
```

Comparison of the release tag and the `dockerfix` branch appears to indicate there is no difference in the code.  The build process should not be working such that a CxFlow jar is delivered from two different branches.  This may eventually go undetected and result in different code being released.

If someone is troubleshooting an issue, they may see that the branch is different on each and it will cause some research delay to make sure the branch and the tag contents do not differ.  

### Reproduction

1. Run CxFlow 1.6.35 in the official docker container.
2. Navigate to the endpoint `/actuator/info`, observe JSON response.
3. Repeat steps 1 and 2 running CxFlow 1.6.35 from the release jar.  The JSON response is different.

### Environment Details

CxFlow 1.6.35

**Comment by satyamchaurasiapersistent** [comment]
Please use latest version of cxflow it's released from master branch.
