### ISSUE TITLE
Jira support is broken for Jira versions 9.x+

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1082]
### Description

When running CxFlow with Jira versions 9.x, the issue creation fails.  Issue creation works with Jira 8.22.6 and prior versions.

### Expected Behavior
SAST and SCA issue lifecycles are updated by CxFlow on Jira server versions 9.x+.

### Actual Behavior

The issue creation fails.  See screen shot:
![image](https://user-images.githubusercontent.com/29153509/184419444-4980ec06-3704-4c44-aa40-05d1bdf81719.png)

### Reproduction

1. Set up a webhook CxFlow server, version 1.6.35 is the latest as of the data this is written.
2. Set up a Jira server version 9.x.  This was tested on 9.0 and 9.1.
3. Note the stack trace.
4. Retry with Jira 8.22.6 or before, note the issues are created/updated properly.

### Environment Details

CxFlow 1.6.35
Jira 8.22.6/9.0/9.1

**Comment by itsKedar** [comment]
Fixed in 1.6.37
