### ISSUE TITLE
Map custom result states to false-positives

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#1114]
### Describe the problem

When defining the custom states as it was implemented in #523, it's not possible to ensure CxFlow sees them as false-positive or true-positive (but since by default custom states represent true-positive, the main issue is with maping custom states to false-positives).

### Proposed solution

Enhance the custom state map config by splitting the current `custom-state-map` in 2 so you have both a `true-positive-custom-state-map` and `false-positive-custom-state-map`, where CxFlow succeeds when receiving custom true-positive states and fails on false-positive ones.

### Additional Details

The `custom-state-map` was developed on the sdk here:
- https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/142

**Comment by cx-scord** [comment]
This feature should include the distinction of the custom states on the PR markdown summary's total vulnerability state counts.

**Comment by itsKedar** [comment]
Fixed in release 1.6.46
