### ISSUE TITLE
Property gitlab.cx-summary is not taken into account (application.yml)

### ISSUE THREAD

**Issue by maklsoba** [checkmarx-ltd/cx-flow#1115]
### Description

Following property is not respected within application.yml
```
gitlab:
  cx-summary: false
```
### Expected Behavior
![image](https://user-images.githubusercontent.com/115146304/194270709-0dba145f-8a3a-450d-bc46-578a44227bc4.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/115146304/194271192-d2e5fa57-910b-41e8-822b-738b25bfea27.png)

### Reproduction

Adapt application.yml as described. Run cx-flow spring app from command line.

**Comment by itsKedar** [comment]
Fixed in 1.6.45
