### ISSUE TITLE
Support additional Linux image architectures

### ISSUE THREAD

**Issue by l3ender** [checkmarx-ltd/cx-flow#1116]
### Describe the problem

The current images only support linux/amd64 which limits how the image can be used.

If running on a system with a different architecture, the following occurs:
```bash
$ docker run checkmarx/cx-flow -it /bin/sh
{"msg":"exec container process `/usr/bin/java`: Exec format error","level":"error","time":"2022-10-10T15:17:33.000555502Z"}
```

### Proposed solution

Please add support for linux/arm64/v8 and linux/386.

### Additional details

See related for use of this image in Github action: https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/issues/57.

**Comment by itsKedar** [comment]
created new repo for Debian OS https://github.com/checkmarx-ts/checkmarx-cxflow-github-debian
