### ISSUE TITLE
Gitlab Bugtracker - add option to insert always new comment in MergeRequest instead of updating existing one

### ISSUE THREAD

**Issue by maklsoba** [checkmarx-ltd/cx-flow#1120]
### Describe the problem

When an scan is complete and the bug tracker "GITLABMERGE" is selected, it creates a comment within the merge request or it "updates" an already existing one. 
For tracking purpuses we would appreciate to have each time a new comment created per scan, so we can see differences and changes to previous scans.

### Proposed solution

Add option to create new comment per scan for "gitlab merge request - bug tracker"

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.0
