### ISSUE TITLE
No documentation for --forcescan CLI parameter or config option to force a scan.

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#1124]
### Description

There's in no `--forcescan` documentation in the [configuration options page](https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration) nor it can be found anywhere else except for some hints that it exists in the code or in the [Config-as-Code](https://github.com/checkmarx-ltd/cx-flow/wiki/Config-As-Code) section.

### Expected Behavior

To have `forcescan` documented anywhere, especially in the Configuration and Tutorials to explicitly tell one can use it in the CLI to force a full scan to run even if the code base is the same.

Also, if there is a way to force it in the config, please describe it as well or inform if it's a CLI/Config-as-Code only config.

### Actual Behavior

Can't find enough documentation on that parameter.

**Comment by itsKedar** [comment]
Fixed in 1.6.41
