### ISSUE TITLE
Support command line PR comments for Bitbucket Cloud and Bitbucket Server

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#1125]
### Describe the problem

Though they are supported using CxFlow's webhook mode, Pull Request comments are not supported when scanning using the CLI to trigger scans using Bitbucket Cloud/Server repos like they are for Github, Gitlab or ADO, we get a `BitBucket Pull not currently supported from command line`.

### Proposed solution

Implement it starting here in the CxFlowRunner class where the CLI call is done, similarly to the other SCMs in that same method:
- https://github.com/checkmarx-ltd/cx-flow/blob/f6566dd60e6c68884d2d1e5de4d9568f424b2d10/src/main/java/com/checkmarx/flow/CxFlowRunner.java#L324

### Additional details

This is somewhat related to #732 but given that ADO PRs work and ADO cloning using CxFlow's CLI is still not possible for ADO, it might not be relevant.

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
