### ISSUE TITLE
ScaResolver files left on container

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1129]
### Description

I have observed that there are several files left on the CxFlow running environment after a scan with ScaResolver.  In an enterprise environment, the volume of scans could eventually fill available storage space.  

### Expected Behavior
Any local files are purged after successful scans and potentially purged periodically if they are deemed to not be in-use for any activity in the running CxFlow instance.

### Actual Behavior

Files are left behind after a scan.  Observed:

* /tmp directory contained 
  * MSBuildTemproot
  * NuGetScratch
  * Empty directory where the resolution results json was originally written
  * zip file containing the ScaResolver results that were uploaded to SCA
  * A directory containing the cloned source
* /app/logs directory contained folders with ScaResolver logs

### Reproduction

Perform a scan, observe the /tmp and /app/logs directories after a scan.

### Environment Details

CxFlow 1.6.36 running in a container (likely affects non-container execution too)
ScaResolver

**Comment by itsKedar** [comment]
Fixed in 1.6.39
