### ISSUE TITLE
Container deployment difficult due to ScaResolver configuration not following normal spring-boot patterns

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1133]
### Description

ScaResolver has an "additional parameters" configuration item that is a string.  The elements in it are passed to the ScaResolver as part of invocation.  This poses some issues in that some of the values passed to ScaResolver may need to be encrypted or changed at runtime.  

Normally configuration of options is performed as specific entries in a YAML file or environment variables/command line parameters following the YAML heirarchy.  This is commonly used to set a common set of parameters in a common config, then invocation supplies other required parameters or overrides to the common parameters.

Some of the additional parameters are strings of parameters sent to package managers via ScaResolver.  Composed in a string, there would likely need to be several levels of escaping to successfully build the proper string containing the additional parameters.

### Expected Behavior
Options passed to ScaResolver should be definable as individual key/value pairs or key/list composition following the Spring Boot configuration pattern used with all other CxFlow configurations.

### Actual Behavior
The additional parameters string must be fully composed.  It is parsed internally to potentially de-dupe or replace with overrides, which could have been done by following normal Spring Boot configuration conventions.

The parsing logic also makes many assumptions (such as all parameters come in pairs) that may not always be correct.

### Reproduction

There is no reproduction, this is logically not correct and is making deployment difficult.

### Environment Details

CxFlow 1.6.36
ScaResolver

**Comment by itsKedar** [comment]
Fixed in 1.6.39
