### ISSUE TITLE
Using docker image execution, ScaResolver integration requires build tools installed or additional documentation

### ISSUE THREAD

**Issue by warrior8792** [checkmarx-ltd/cx-flow#1135]
### Description

Given that the ScaResolver integration will need access to Maven, Gradle, Python, npm, etc., documentation should provide guidance and examples on how to add these tools to a derived docker image since they are not included.  Without the tools installed, the integration is not useful.  

### Proposed solution

Either provide equivalent tools that the SCA SaaS has access to for dependency resolution or provide documentation on how to use these with the published docker image.

### Environment Details
cxflow 1.6.36
ScaResolver

**Comment by espguitarist33** [comment]
@satyamchaurasiapersistent Can you say more details on why this wouldn't be fixed? We are unable to use CXFlow and SCA Resolver together due to Maven not being installed

**Comment by karol-burczynski-ck** [comment]
> @satyamchaurasiapersistent Can you say more details on why this wouldn't be fixed? We are unable to use CXFlow and SCA Resolver together due to Maven not being installed

It also worth to mention that it makes https://github.com/checkmarx-ts/checkmarx-cxflow-github-action completely not usable when used with SCA Resolver scans on majority of configurations normally supported by it.

**Comment by satyamchaurasiapersistent** [comment]
Implemented in 1.7.06
