### ISSUE TITLE
Add badge for docker hub

### ISSUE THREAD

**Issue by kaplanlior** [checkmarx-ltd/cx-flow#1143]
CX-flow docker image has 1.8 million downloads. Please add a badge like ![Docker Pulls](https://img.shields.io/docker/pulls/checkmarx/cx-flow) to reflect this, similar to what we have in KICS.

```
![Docker Pulls](https://img.shields.io/docker/pulls/checkmarx/cx-flow)
```

**Comment by itsKedar** [comment]
Fixed in release 1.6.46
