### ISSUE TITLE
CxFlow uses same exit status for errors as for exceeding result thresholds

### ISSUE THREAD

**Issue by james-bostock-cx** [checkmarx-ltd/cx-flow#1145]
### Description

CxFlow uses the same exit status for errors as for exceeding threshold results. This means that automation scripts cannot distinguish between the two cases.

### Expected Behavior

CxFlow uses different exit statuses for errors and for exceeding result thresholds.

### Actual Behavior

CxFlow uses the same exit status for errors and for exceeding result thresholds.

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by itsKedar** [comment]
Fixed in 1.6.41 pull request https://github.com/checkmarx-ltd/cx-flow/pull/1233
