### ISSUE TITLE
Workflow change for submitting scans to avoid source location overwrite

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1151]
### Describe the problem

The current workflow of submitting scans is currently:

* Create a scan with a POST to `/sast/scans`
* Attach a source zip with a POST to `/projects/{id}/sourceCode/attachments`

The issue is that this overwrites the project source pulling settings.  If a user had configured the project for Git as the source location so they can invoke a scan from the UI, this workflow replaces the source location with "zip" and it can no longer be invoked from the UI.  If the scan was a scheduled scan, it can no longer execute on schedule since the source zip doesn't exist.

### Proposed solution

Use the `/sast/scanWithSettings` API to invoke scans.  The `overrideProjectSetting` parameter defaults to `false` so that it does not change the parameters of the source location.  

CxFlow should default `overrideProjectSetting` to `true` for all scans so that it functions as it currently does.  A configurable option to disable the scan settings overwrite should be available to enable the workflow that does not overwrite the source location settings.

### Additional Information
Some (if not all) of our other plugins have changed to use this API rather than the original API workflow.  I have not verified, but I believe the other plugin implementations don't overwrite the source location settings by default.  This likely should be different for CxFlow since many CxFlow installations prefer to disable the ability for project settings to change.

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.0
