### ISSUE TITLE
The get report from scan is not applying the filters

### ISSUE THREAD

**Issue by TaynaCT** [checkmarx-ltd/cx-flow#1158]
### Description
With the following command, I tried to retrieve a .csv report with information filtered according to the [application-local_report.yml.txt](https://github.com/checkmarx-ltd/cx-flow/files/10402703/application-local_report.yml.txt) file (filter-severity, filter-category, filter-status, filter-state) :

`java -jar cx-flow-1.6.38.jar --spring.config.location="C:\cxflow\application-local_report.yml" --project --cx-team="CxServer" --cx-project="WebGoat-cxflow" --app=WebGoat-cxflow`

The _application-local_report.yml_ file is attached.

### Expected Behavior

Generate a report showing the vulnerabilities based on the filters applied. 
This only works if triggerring the --scan  comand.

### Actual Behavior

Generates a empty csv file, containing only the headers.

**Comment by itsKedar** [comment]
Hi,

This issue is not reproduced in the newest cx-flow version. Please use the newest cx-flow release, which is currently 1.6.46.
