### ISSUE TITLE
When using --checkmarx.cx-branch=true and --branch is empty, created project name has a weird name

### ISSUE THREAD

**Issue by luisgarciacheckmarx** [checkmarx-ltd/cx-flow#1161]
### Description

> Provide a description of the issue

When using CxFlow with below parameters, 

--scan
--checkmarx.cx-branch=true ^
--cx-project="MyProject-MyBranch" ^
--branch="" ^
--default-branch="1.x"

### Expected Behavior

Fail/advice because --branch is empty string.

### Actual Behavior

The resulting created project is "1.xM1.xy1.xP1.xr1.xo1.xj1.xe1.xc1.xt1.x-1.xM1.xy1.xB1.xr1.xa1.xn1.xc1.xh1.x".

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

As far as I have seen, in CxService.java this line
derivedProjectName = params.getProjectName().replace(params.getModifiedProjectName(),defaultBranch)
when params.getModifiedProjectName() is empty (because branch is empty), derivedProjectName results in such a weird value (1.xM1.xy1.xP1.xr1.xo1.xj1.xe1.xc1.xt1.x-1.xM1.xy1.xB1.xr1.xa1.xn1.xc1.xh1.x)

**Comment by HussainS12** [comment]
@umeshwaghode I have fixed this in the SDK. Please test and merge if possible.

**Comment by satyamchaurasiapersistent** [comment]
We have resolved this issue in release 1.6.40
