### ISSUE TITLE
Sonarqube integration - secondaryLocations not appear in Json report

### ISSUE THREAD

**Issue by luisgarciacheckmarx** [checkmarx-ltd/cx-flow#1164]
### Description

When using SonarQube as bug-tracker, the resulting JSON report (to be imported into Sonarqube) does not include the attack vector into the secondaryLocations. This means that attack vector is not shown into Sonarqube.

As far as I see in the code, secondayLocations are not included.

sonarIssues.add(Issue.builder().engineId(properties.getSastScannerName())
                                    .ruleId(issue.getVulnerability())
                                    .severity(properties.getSeverityMap().get(issue.getSeverity()) != null ? properties.getSeverityMap().get(issue.getSeverity()):DEFAULT_LEVEL)
                                    .type("VULNERABILITY")
                                    .primaryLocation(ILocation.builder()
                                            .filePath(issue.getFilename())
                                            .message(StringUtils.isEmpty(issue.getDescription()) ? issue.getVulnerability() : issue.getDescription())
                                            .textRange(TextRange.builder()
                                                    .startLine(k<1?1:k)
                                                    .endLine(k<1?1:k).build()).build()).build());

### Expected Behavior

{
  "issues": [
    {
      "engineId": "Cx - SAST",
      "ruleId": "SQL_Injection",
      "severity": "CRITICAL",
      "type": "VULNERABILITY",
      "primaryLocation": {
        "message": "The application's return method executes an SQL query with query, at line 5 of dbSchemaChallenge_1.ts. The application constructs this SQL query by embedding an untrusted string into the query without proper sanitization. The concatenated string is submitted to the database, where it is parsed and executed accordingly.\nAn attacker would be able to inject arbitrary syntax and data into the SQL query, by crafting a malicious payload and providing it via the input q; this input is then read by the return method at line 3 of dbSchemaChallenge_1.ts. This input then flows through the code, into a query and to the database server - without sanitization.\nThis may enable an SQL Injection attack.\nSimilarity ID: 1520572051",
        "filePath": "dbSchemaChallenge_1.ts",
        "textRange": {
          "startLine": 3,
          "endLine": 3,
          "startColumn": 70,
          "endColumn": 71
        }
      },
      "effortMinutes": 90,
      "secondaryLocations": [
        {
          "message": "q",
          "filePath": "dbSchemaChallenge_1.ts",
          "textRange": {
            "startLine": 3,
            "endLine": 3,
            "startColumn": 69,
            "endColumn": 70
          }
        }..........
      ]
    }
   ]
}

### Actual Behavior

{
  "issues": [
    {
      "engineId": "Cx - SAST",
      "ruleId": "SQL_Injection",
      "severity": "CRITICAL",
      "type": "VULNERABILITY",
      "primaryLocation": {
        "message": "The application's return method executes an SQL query with query, at line 5 of dbSchemaChallenge_1.ts. The application constructs this SQL query by embedding an untrusted string into the query without proper sanitization. The concatenated string is submitted to the database, where it is parsed and executed accordingly.\nAn attacker would be able to inject arbitrary syntax and data into the SQL query, by crafting a malicious payload and providing it via the input q; this input is then read by the return method at line 3 of dbSchemaChallenge_1.ts. This input then flows through the code, into a query and to the database server - without sanitization.\nThis may enable an SQL Injection attack.\nSimilarity ID: 1520572051",
        "filePath": "dbSchemaChallenge_1.ts",
        "textRange": {
          "startLine": 3,
          "endLine": 3,
          "startColumn": 70,
          "endColumn": 71
        }
      },
      "effortMinutes": 90,
      
    }
   ]
}

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by itsKedar** [comment]
Fixed in 1.6.40 release
