### ISSUE TITLE
Pull Request scan results should refresh after a second push to the same pull request

### ISSUE THREAD

**Issue by MrIonic** [checkmarx-ltd/cx-flow#1172]
### Describe the problem

In GitHub using the Webhook integration, the Pull Request displays only the first scan results. Suppose the scan results show a new finding, so the developer fixes his code and pushes it to the same pull request to verify a clean scan.  The Pull Request scan results do not change from the original scan, even though the log shows a second scan completed.

### Proposed solution

Subsequent scans of the same pull request should update the scan results table (or add a new comment with the new scan results) in the Pull Request comment.

### Additional details

The time stamp is unchanged for subsequent scans in the GitHub pull request Checkmarx scan results comment.

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
