### ISSUE TITLE
NPE when using --parse mode and cx-flow.enabled-vulnerability-scanners is not defined

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1177]
### Description

When executing CxFlow to parse an XML report using the `--parse` option and a YAML configuration file, a NullPointerException is thrown when cx-flow.enabled-vulnerability-scanners is not defined.

### Expected Behavior

It should use SAST by default and not throw an exception.

### Actual Behavior

It throws an exception and stops processing.

### Reproduction

1. Create a YAML configuration that otherwise is verified as working
2. Do not include cx-flow.enabled-vulnerability-scanners
3. Execute CxFlow in parse mode to parse a SAST XML report

### Environment Details

Confirmed broken on 1.6.38.  
Confirmed as working on 1.6.28.

**Comment by itsKedar** [comment]
Fixed in 1.6.40 release
