### ISSUE TITLE
Team not created when using /scan endpoint

### ISSUE THREAD

**Issue by atheismann** [checkmarx-ltd/cx-flow#1184]
### Description

Teams are not created when using the /scan endpoint.

### Expected Behavior
When using CxFlow to trigger scans based on GitHub org/repo/branch, it is expected that the associated team would be created in CxSAST when a new Org is onboarded to CxFlow.

### Actual Behavior
Scans for Orgs which have not scanned before fail to create the team and require the team to be manually created in CxSAST.

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
https://github.com/checkmarx-ltd/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java#L76

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by itsKedar** [comment]
Fixed in 1.6.40 release
