### ISSUE TITLE
ScaResolver exclude command won't work when passed via the CLI with quotes

### ISSUE THREAD

**Issue by awesomeBreeze** [checkmarx-ltd/cx-flow#1185]
### Description
The ScaResolver exclude command won't work when it's passed via CLI and with quotes

### Expected Behavior

All the following patterns should work

--sca.sca-resolver-add-parameters.e="*/folders-to-exclude/*"

--sca.sca-resolver-add-parameters.e='*/folders-to-exclude/*'

--sca.sca-resolver-add-parameters.e=*/folders-to-exclude/*

### Actual Behavior

Only the last pattern without quotes works.

--sca.sca-resolver-add-parameters.e="*/folders-to-exclude/*" Doesn't work

--sca.sca-resolver-add-parameters.e='*/folders-to-exclude/*' Doesn't work

--sca.sca-resolver-add-parameters.e=*/folders-to-exclude/* Works

**Comment by itsKedar** [comment]
Fixed in 1.6.40 release
