### ISSUE TITLE
Support for GitLab 15.10.3 schema 

### ISSUE THREAD

**Issue by Cx-aschmit** [checkmarx-ltd/cx-flow#1226]
### Describe the problem

> Customers are looking to use the GitLab Security Dashboard bug tracker; however, the latest supported schema is 15.0.4. This means that when trying to add issues to GitLab Security Dashboard using newer schemas, e.g., 15.10.3, CxFlow fails.

### Proposed solution

> Add support for GitLab Security Dashboard schema version 15.10.3

### Additional details

> Example of the CxFlow error;

![image](https://github.com/checkmarx-ltd/cx-flow/assets/46612825/cf963d4b-0c11-481d-8840-1faafb2608d0)

**Comment by itsKedar** [comment]
Fixed in 1.6.42
