### ISSUE TITLE
Missing Vulnerabilities in Merge Request comments

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#1232]
### Description

If you have multiple vulnerabilities with the same source line, but different destination (lines / files), the Cx-SAST Summary counts them as separate vulnerabilities (same as the Checkmarx UI), however the Violation Summary and Cx-SAST Details sections report only 1 vulnerability instead of multiple (probably due to the vulnerability originating from the same line).

### Expected Behavior

The vulnerability count is exhaustive and consistent throughout the Merge Request comment. If the vulnerability propagates through the code, each propagation (destination) should be listed.

### Actual Behavior

The Violation Summary and Cx-SAST Details report a different count of vulnerabilities. Three of the vulnerabilities are unaccounted for and missing from the Merge Request comment.

### Reproduction

Easiest is with a Python project using argparse, then use a logger to log the parameters, you'll get a vulnerability graph from the parser to the logs (single source, multiple destination).

Screenshot, the vulnerability Log_Forging is actually 4 vulnerabilities in the Checkmarx's UI, they all originate from the same line (117) via argparse, but propagate to different destination. As you can see the vulnerability count is inconsistent between the sections. 

<img width="352" alt="image" src="https://github.com/checkmarx-ltd/cx-flow/assets/79320471/9db2131d-f5fb-4fdf-80a2-9e5ef4c4c776">

In the Checkmarx's UI 
<img width="230" alt="image" src="https://github.com/checkmarx-ltd/cx-flow/assets/79320471/f1c309a6-0f06-419d-a008-a59b868afa29">

### Environment Details

CxFlow 1.6.40-11
Checkmarx version 9.5.3.1001 HF5

**Comment by satyamchaurasiapersistent** [comment]
We are doing grouping of issues. Please try without clubbing of issues and try again Please refer : https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration disable clubbing 
![image](https://github.com/checkmarx-ltd/cx-flow/assets/102941840/d29af79a-74d2-4e11-b8e2-55dd011a15a1)
