### ISSUE TITLE
no documented values - filter-dependency-type in sca section

### ISSUE THREAD

**Issue by warrior8792** [checkmarx-ltd/cx-flow#1240]
### Description

There is no documentation on the "filter-dependency-type" range of values in CxSCA integration.

**Comment by satyamchaurasiapersistent** [comment]
https://github.com/checkmarx-ltd/cx-flow/wiki/Thresholds-and-policies
Its present 
![image](https://github.com/checkmarx-ltd/cx-flow/assets/102941840/1d051adc-20b4-4dda-9d12-fb84866a093f)

**Comment by warrior8792** [comment]
Besides "Direct" and "All" are there other values?

**Comment by satyamchaurasiapersistent** [comment]
No
