### ISSUE TITLE
Sarif Format: Mismatch information between 2 fields

### ISSUE THREAD

**Issue by marcandre-larochelle** [checkmarx-ltd/cx-flow#1251]
### Description

Within the rules, the `help` property has 2 fields, `text` and `markdown`, the `text` only has the link to the explanation of the rule and is missing the link to the scan.

### Expected Behavior

Both the `text` and the `markdown` provide the same information

### Actual Behavior

The `text` only has 1 of the 2 links.

### Reproduction

- Perform a SAST scan in Sarfit format
- Compare the fields underneath `help` within the rules

### Environment Details

CxFlow 1.6.40-11

**Comment by marcandre-larochelle-bell** [comment]
Issue still present in 1.6.45

**Comment by marcandre-larochelle-bell** [comment]
Still applies in 1.7.0

**Comment by satyamchaurasiapersistent** [comment]
Implemented in 1.7.06
