### ISSUE TITLE
Sarif Format: Incorrect Specification Implementation, missing artifacts object

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#1252]
### Description

Under the field `locations` -> `physicalLocation` -> `artifactLocation`, there is a field index which refers to an artefact in the run[0].artefacts, but run.artefacts is missing from the output.

### Expected Behavior

Artefact object found in `runs`-> `artifacts` as per the specification

### Actual Behavior

`runs`-> `artifacts` is missing

### Reproduction

- Perform a SAST scan with the Sarif format
- Verify the specification (see: https://sarifweb.azurewebsites.net/Validation)

### Environment Details

CxFlow 1.6.40-11

**Comment by marcandre-larochelle-bell** [comment]
Still present in 1.6.45

**Comment by marcandre-larochelle-bell** [comment]
<img width="600" alt="image" src="https://github.com/checkmarx-ltd/cx-flow/assets/79320471/56a2528e-3023-41e4-98f5-a5f3bb7df17a">

**Comment by marcandre-larochelle-bell** [comment]
Still applies in 1.7.0

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
