### ISSUE TITLE
Sarif Format: Use the region "snippet" instead of Location "message" for the affected lines of code.

### ISSUE THREAD

**Issue by marcandre-larochelle** [checkmarx-ltd/cx-flow#1253]
### Describe the problem

The specification has a `snippet` in the Location object for the affected lines of code, but the Sarif output uses the `Location` -> `message` property instead.

### Proposed solution

Use the `Location` -> `region` -> `snippet` for the affected code.

### Additional details

CxFlow 1.6.40-11

**Comment by marcandre-larochelle-bell** [comment]
Still applies to 1.7.0

**Comment by satyamchaurasiapersistent** [comment]
Implemented in 1.7.04
