### ISSUE TITLE
Sarif Format: Maven modules are not treated as different artifacts

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#1254]
### Describe the problem

Issues in maven modules are not treated relatively (in their locations).

### Proposed solution

Location of issues in modules are treated relatively to the modules they are in rather than relatively to the root project.

CxFlow 1.6.40-11

**Comment by marcandre-larochelle-bell** [comment]
Still applies to 1.7.0

**Comment by satyamchaurasiapersistent** [comment]
Hi @marcandre-larochelle-bell  can you please provide me specific example of what is the correct result and what is desired result in json file.

**Comment by marcandre-larochelle-bell** [comment]
@satyamchaurasiapersistent 

I was hoping for an `originalUriBaseIds` object for each modules with the `uri` / `uriBaseId` properties relative to the root `originalUriBaseId`. 

Example:
```
{
	...
	"originalUriBaseIds": { 
	 "SRCROOT": {
		"uri": "file:///C:/somepath/to/project/root/"
	 },
	 "MODULEA": {
		"uri": "modulea/"
		"uriBaseID": "SRCROOT"
	 },
	 "MODULEB": {
		"uri": "moduleb/"
		"uriBaseID": "SRCROOT"
	 }
	},

	...

	"results": [
		{
			...
			
			"locations": [
				{
					"physicalLocation": {
						"artifactLocation": {
						 "uri": "path/to/vulnerable/file",
						 "uriBaseId": "MODULEA"
						}
					}
				}
			]
		}
	]
}
```

This allows for an easy way to resolve modules independently of each others and separate vulnerabilities per modules via the `uriBaseId` when parsing the results.

**Comment by satyamchaurasiapersistent** [comment]
I have added the URI base ID for the upcoming release 1.7.01. Understanding this change would require a session with you. If we can have a session, I can quickly provide the desired results in the pre-build stage. Can you please raise an SF ticket for this?

**Comment by wuc-tooling-security-team** [comment]
@satyamchaurasiapersistent  I'm ok with having a session for this, I think there is a SF ticket open for this (on April 23rd 2024, I don't have the ticket number, but can reach out to figure it out if needed).

**Comment by marcandre-larochelle-bell** [comment]
@satyamchaurasiapersistent I'm ok with having a session for this, I believe there is a SF ticket open for this (April 23rd 2024, but I don't have the ticket number, I can reach out to figure it out if needed). Thanks

**Comment by satyamchaurasiapersistent** [comment]
HI @marcandre-larochelle-bell  please provide me ticket number. If you don't remember please raise new one and let me know here.

**Comment by marcandre-larochelle-bell** [comment]
@satyamchaurasiapersistent I managed to get a ticket, here is the number: #00222620

**Comment by satyamchaurasiapersistent** [comment]
Implemented in 1.7.06

**Comment by jeandominiclaroche** [comment]
Based on my tests with 1.7.06, the output looks like this :
```
{
	...
	"originalUriBaseIds": { 
	 "SRCROOT": {
		"uri": "file:///C:/somepath/to/project/root/"
	 },
	 "MODULEA": {
		"uri": "modulea/"
		"uriBaseID": "SRCROOT"
	 },
	 "MODULEB": {
		"uri": "moduleb/"
		"uriBaseID": "SRCROOT"
	 }
	},

	...

	"results": [
		{
			...
			
			"locations": [
				{
					"physicalLocation": {
						"artifactLocation": {
						 "uri": "modulea/path/to/vulnerable/file",
						 "uriBaseId": "MODULEA"
						}
					}
				}
			]
		}
	]
}
```

I don't think the uri in the artifactLocation should start by `modulea/` since that part is already defined in the uriBaseId. I think it should look like this :
```
	"physicalLocation": {
		"artifactLocation": {
			"uri": "path/to/vulnerable/file",
			"uriBaseId": "MODULEA"
		}
```

I tried setting `sarif.srcRootPath` to see if it would help but it didnt. Is this intended?

**Comment by satyamchaurasiapersistent** [comment]
It's intended but we can make it configurable for you. We will update on SF-00222620
