### ISSUE TITLE
Custom fields are not set on parent branch projects created when a child branch is scanned

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1262]
### Description

If a child branch (usually a feature/bugfix/etc) is scanned as a result of opening a PR targeting a protected branch AND there is not an existing project for a parent branch, both the parent and child branch projects are created.  When custom fields are defined in the config-as-code, the custom fields are not set in the parent branch.

### Expected Behavior

All defined custom fields should be set on any project created for any branch with the value provided in config-as-code or server-side configs at the time of the scan.

### Actual Behavior

The custom fields are set on the created child branch project but not set on any of the projects created for the parent branch.

### Reproduction

Observe config as code defining the custom field:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/1195ebc3-48bb-4670-8d2b-70ab3d686694)

No projects for the repo should exist in SAST.  Open a PR from a child branch that targets a parent branch.

Observe child branch project has been created and the custom field has had the config-as-code custom field value assigned:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/b8736ab8-a989-4e79-8334-5141b36534ca)

Observe the parent branch project has been created but does not have the custom field value assigned:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/67f9aaec-d3a8-438f-8a53-cdc28399ad8b)

### Environment Details

CxFlow 1.6.41 using webhooks

**Comment by itsKedar** [comment]
Hi @nleach999,

This issue was fixed in 1.6.44. Please test it on the same.

Thanks
