### ISSUE TITLE
First scan on parent branch project does not set custom fields defined in config-as-code

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1263]
### Description

This is related to issue #1262.

When the parent branch receives a push that initiates the first scan in the parent branch project, the custom field in config-as-code is not set on the parent project for the first scan,

### Expected Behavior

All defined custom fields should be set on any project created for any branch with the value provided in config-as-code or server-side configs at the time of the scan.

### Actual Behavior

Custom field is not set on the parent branch project.

### Reproduction
Note custom field configured in config-as-code:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/0b9b618d-83a7-45f0-aa67-2d290452a3ca)

Note that the child branch (myfeature) has had one scan (from opening a PR) and the parent branch (demo-master) has 0 scans.

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/595c5ff2-2793-4d6e-b17c-1cc537b6c8bb)

Note that parent branch does not have the custom field value set and has 0 scans:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/284251c8-d930-4534-82c7-8eb28b49a216)

Note that after 1 scan (due to PR merge), the parent branch (demo-master) still does not have the custom field set:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/6c152397-5631-40c2-9743-7bb39eb76e98)

### Environment Details

CxFlow 1.6.41 with webhooks

**Comment by itsKedar** [comment]
Hi @nleach999,

This issue was fixed in 1.6.44. Please test it on the same.

Thanks
