### ISSUE TITLE
Project custom field values are not updated with changes to custom field values in config as code

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1264]
### Description

Related to issue #1262.

If I have a custom field value in config-as-code on a branch, the branch project is created on PR open and the custom field value in config as code is set.  If I change the custom field value in config-as-code when the PR is still open, the custom field in the project is not updated with the new custom field value in config-as-code.

### Expected Behavior

All defined custom fields should be set on any project created for any branch with the value provided in config-as-code or server-side configs at the time of the scan.

### Actual Behavior

The custom field value remains set to the value it was at the first scan.  This appears to be the case for all projects - the custom field is only set on project creation and is never updated to new values in the config-as-code or server config.

### Reproduction

Observe the branch project that has the PR scan along with the latest scan from the parent branch project at the time the branch project was created.   The custom field in the branch project is set to the custom field value in config-as-code at the time the branch project was created.

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/733059c4-488e-433a-852e-e22d4a1daf8f)

Observe modifications to the branch (a_new_feature) config-as-code to change the custom field value:

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/d0b6d564-0769-4dfc-aeef-1a02faaed6bf)

After the scan resulting from the PR update, observe the project custom field has not changed to reflect the new value in the config-as-code custom field.

![image](https://github.com/checkmarx-ltd/cx-flow/assets/29153509/0b142fc9-2730-4313-b060-1134b7a63fbc)

### Environment Details

CxFlow 1.6.41 with webhooks

**Comment by itsKedar** [comment]
Hi @nleach999,

This issue was fixed in 1.6.44. Please test it on the same.

Thanks
