### ISSUE TITLE
Add support for SCA tags in Jira integration

### ISSUE THREAD

**Issue by antoniosilvacx** [checkmarx-ltd/cx-flow#1283]
### Describe the problem

SAST custom fields are available for Jira integration via the "cx" field type, but not for tags, the equivalent in SCA.

### Proposed solution

The idea would be to have a "cx-sca" field type where we could allow access to the SCA tags, by using the tag name as the field name.

### Additional details

A customer has mandatory fields in Jira that he can't fill when it's an SCA scan, although the required information is in the tags.

**Comment by itsKedar** [comment]
Fixed in 1.6.46 version
