### ISSUE TITLE
File filtering with local clone

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1288]
### Describe the problem

For teams that work on non-Windows OS as their development platform, they can make files that have names that are not compatible with the Windows OS.  When submitting a SAST scan, the clone executes on Windows and fails due to invalid filenames,

Files with invalid characters like "<" or ">" are part of the problem.  Windows also reserves names like "prn", "con", "lpt", and "aux" so that they are also invalid.

### Proposed solution

Add a feature that can work in conjunction with CxFlow's local checkout where filename globs can be defined. CxFlow does the following:

1. Clones the repo that has code to be submitted for scanning.
2. Removes files that match any of the glob parameters (like *<*, *aux*, etc)
3. Submits the Windows-compatible files for scan.

### Additional details

This affects users that are using CxFlow with webhooks.

**Comment by itsKedar** [comment]
Added docs for it in 1.7.01
