### ISSUE TITLE
Add DynamoDB Support in JAR for use in Sharding

### ISSUE THREAD

**Issue by atheismann** [checkmarx-ltd/cx-flow#1299]
### Describe the problem

We would like to have DynamoDB support added to the JAR so that we can use DynamoDB as part of our sharding implementation.

### Proposed solution

Add DynamoDB as a dependency in the JAR.

**Comment by satyamchaurasiapersistent** [comment]
Hi can you please specify your requirement in more detail .
How you are planning to use cxflow for dynamo.

**Comment by satyamchaurasiapersistent** [comment]
Adding DynamoDB support to cxflow JAR for sharding implementation sounds like a promising avenue to explore! However, to ensure we're on the same page and can move forward effectively, I need some additional information:

1. Current Sharding Approach:

How is sharding currently implemented in your system? (e.g., database sharding, code-based sharding)
What are the limitations or challenges you're facing with the current approach that necessitate DynamoDB integration?

2. DynamoDB Usage in Sharding:

How do you envision DynamoDB being used within your sharding setup? (e.g., storing shard metadata, routing requests to specific shards)
What specific DynamoDB features would be crucial for your sharding implementation? (e.g., secondary indexes, global secondary indexes),

4. Technical Environment:

What programming language and libraries are you using?
Which DynamoDB version are you targeting? (v1 or v2)
Are there any specific cloud platforms or infrastructure considerations?
5. Development Scope:

Do you have any existing code or prototypes related to this integration?
What is your desired timeline for implementing DynamoDB support?
By providing more details on these points, we can have a more productive discussion about the feasibility and specific steps involved in adding DynamoDB support to your JAR for sharding. I'm happy to offer guidance and suggestions based on your requirements and the relevant technologies.

Remember, the more information you share, the better I can tailor my assistance to your unique needs and help you achieve your desired sharding goals.

**Comment by atheismann** [comment]
@satyamchaurasiapersistent 

1. Sharding is a capability of CxFlow to allow for multiple instances of CxSAST to be used to increase scan capacity.
2. DynamoDB would be used instead of PostgreSQL, MySQL, or Redis to store the shard metadata and project assignments.  The move to DynamoDB is part of our desire to use cloud native and serverless technologies as much as possible.
3. Considering that CxFlow is a Java application with Groovy Scripts used in the sharding logic, we will be using the AWS Java SDK.  We are targeting DynamoDB v2 since v1 is being deprecated.
4. We are developing the implementation and integration and providing the issue and details for tracking.  We will open a PR when the integration is complete and tested.
