### ISSUE TITLE
Lack of Checkmarx Link in Merge Request Scanning Results

### ISSUE THREAD

**Issue by keethebest** [checkmarx-ltd/cx-flow#1303]
# Describe the problem
When generating a merge request in CD/CI on GitLab, an automatic checkmarx scan is initiated, and the results are generated. However, currently, there is no provided link in the scan results to navigate directly to Checkmarx for further inspection.

# Proposed solution
It would be highly beneficial to include a hyperlink within the scan results, facilitating a direct jump to the relevant section in Checkmarx. This enhancement would greatly improve the efficiency of result inspection and debugging.

# Additional details

Thank you for considering this improvement.

**Comment by satyamchaurasiapersistent** [comment]
If this issue sill persists please raise salesforce ticket.
