### ISSUE TITLE
GitLab Integration

### ISSUE THREAD

**Issue by shaputta** [checkmarx-ltd/cx-flow#1313]
### Description
GitLab integration using GitLab runner
> Provide a description of the issue
Hi Team,
My current requirement is to construct the GitLab CICD pipeline using GitLab runner. For which, I have followed the Cx official documentation and setup the pipeline, which running successful. 
The components at present in setup are:
1. GitLab runner -- we wanted to create the pipeline using GitLab runner
2. Containerized Cx Flow

Now, my question is how could I proceed to implement the same in real time.
Instead of containerized Cx-Flow, can we use in any other way, it must be triggered by GitLab runner.
If yes, could you please provide the detailed documentation, possible ways of GitLab integration
Through out the tutorial, I can see the setup by using containerized Cx-Flow.
### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details
Under environment variables, we are passing plain text Cx password. we would want to protect that instead of declaring plain text.
Please provide the possible ways of securing password of environment variable.
We are looking to see if AWS param store works for it.

**Comment by satyamchaurasiapersistent** [comment]
Yes you can use Cxflow Jar from latest  release and use jar in web mode and configure webhook for same. Please find below links for your reference 
https://github.com/checkmarx-ltd/cx-flow/releases/download/1.6.46/cx-flow-1.6.46.jar
https://github.com/checkmarx-ltd/cx-flow/wiki/WebHook-Registration#gitlab
https://github.com/checkmarx-ltd/cx-flow/wiki/Execution#webhook
