### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by shaputta** [checkmarx-ltd/cx-flow#1314]
### Describe the problem
We have setup the GitLab CICD where the Cx scans are resulting into GitLab issues. The results are having only source path, we would need the source to sink path in GitLab issues tab.

### Proposed solution
Source to sink path in GitLab issues

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by satyamchaurasiapersistent** [comment]
If Issue still persists please raise Salesforce ticket for same.
