### ISSUE TITLE
Issue with https://github.com/checkmarx-ltd/cx-flow/wiki/Tutorials#cicd-variablesBug Tracker Type "GitLabDashboard"

### ISSUE THREAD

**Issue by KafkaProServerless** [checkmarx-ltd/cx-flow#1326]
Hello team,

Following your document:
https://github.com/checkmarx-ltd/cx-flow/wiki/Tutorials#cicd-variables

It seems it is possible to use a bug tracker type "GitLabDashboard"
And there are many places which mention "GitLabDasboard"
```
    - if: '$CX_FLOW_BUG_TRACKER == "GitLabDashboard" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
```

However, in the code, we can see only those:

```
public class BugTracker {
    private Type type;

public enum Type {
        JIRA("JIRA"),
        BITBUCKETCOMMIT("BITBUCKETCOMMIT"),
        BITBUCKETPULL("BITBUCKETPULL"),
        BITBUCKETSERVERPULL("BITBUCKETSERVERPULL"),
        bitbucketserverpull("bitbucketserverpull"),
        ADOPULL("ADOPULL"),
        adopull("adopull"),
        GITHUBPULL("GITHUBPULL"),
        githubpull("githubpull"),
        GITHUBCOMMIT("GITHUBCOMMIT"),
        GITLABCOMMIT("GITLABCOMMIT"),
        GITLABMERGE("GITLABMERGE"),
        gitlabmerge("gitlabmerge"),
        EMAIL("EMAIL"),
        CUSTOM("CUSTOM"),
        NONE("NONE"),
        WAIT("WAIT"),
        wait("wait");

        private String type;

        Type(String type) {
            this.type = type;
        }

        public String getType() {
            return type;
        }
    }
```

There is no "GitLabDashboard"

Is that expected?

Can we change the Type, or remove this from the doc?

Also, could you please add more concrete documentation for :
https://github.com/checkmarx-ltd/cx-flow/wiki/Tutorials#security-dashboard

It is only three lines, while "merge request" for instance, has more descriptions, screenshots, etc

Thank you

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
