### ISSUE TITLE
Preset is never overridden when specified in WebHook parameters orin "sast" section in cx.config

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#134]
Checkmarx version: 8.9.0 HF13 (SDLC)
CX-flow version: 1.5.4

When having a project already created in Checkmarx SAST, and CXflow is setup to generate scans on Pull Requests, the Checkmarx preset specified in the Pull Request Webhook parameter is never used. Instead, the preset defined in the application.yml is always used.

Use case:
Say that we have a CXFlow instance listening to Github PRs that triggers scans. The "scan-preset" property in application.yml not specified (intentionally), so that one can override the preset in the WebHook Parameter (as specified in GitHubController.Java in method:
public ResponseEntity<EventResponse> pullRequest

Observations:

the "override" is never used (greyed out by the IDE)
No matter what preset I specify in the WebHook parameter, the Checkmarx Default is always used
While debugging through the code, I noticed that in file FlowService.java, method
private Integer determinePresetAndProjectId(ScanRequest request, String ownerId, String projectName ) {

it seems that the check is wrongly done (unless I understood #the code logic wrong), and the method fetches and sets the project's preset if the request has the scanPresetOverride as false.
image

By removing the negation before the "request.isScanPresetOverride()", it works as expected and the scan will use the project's defined Preset (that was set from within the Web Interface).

I might have not understood the code logic, or maybe this is just a bug and the negation needs to be removed.

**Comment by kmcdon83** [comment]
![](https://user-images.githubusercontent.com/19224447/81513092-18108e80-9326-11ea-9656-ef7996168ec2.png)

**Comment by kmcdon83** [comment]
@andreihincu FYI

**Comment by cx-imatlin** [comment]
Need this fixed for HCSC.
