### ISSUE TITLE
Gitlab/Github - Labels not applied to scan results of severity: informational / info

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#1340]
### Description

The labels  are not applied to scan results of severity: informational / info for the Gitlab Issue Tracker, potentially the same issue for Github.

### Expected Behavior

Labels are assigned to the Gitlab issues

### Actual Behavior

No labels assigned due to these lines of code:

https://github.com/checkmarx-ltd/cx-flow/blob/b2c3c930ebfb1d0bac8378f5238a452412e1291a/src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java#L402-L416

https://github.com/checkmarx-ltd/cx-flow/blob/b2c3c930ebfb1d0bac8378f5238a452412e1291a/src/main/java/com/checkmarx/flow/config/FindingSeverity.java#L3-L5

The FindingSeverity enum contains "INFO", but the scan results returns "Informational", thus when the compare is done on line 407: 
https://github.com/checkmarx-ltd/cx-flow/blob/b2c3c930ebfb1d0bac8378f5238a452412e1291a/src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java#L407

It doesn't match and no labels are applied later on.

### Reproduction

Run a scan for a Gitlab project with the --gitlab.issueslabel.info="any-label" parameter

### Environment Details
Docker image: CxFlow 1.7.0-17

**Comment by itsKedar** [comment]
Fixed in 1.7.02
