### ISSUE TITLE
CxFlow still generates "training" links to Codebashing despite discontinuing the feature

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#1342]
### Description

CxFlow still generates "training" links to Codebashing despite discontinuing the feature

### Expected Behavior

Feature is disabled and throws a warning / error

### Actual Behavior

Training links are still generated with some configuration.

### Reproduction

Provide a codebash-url as a parameter

### Environment Details

Docker image: CxFlow 1.7.0-17

**Comment by itsKedar** [comment]
Fixed in 1.7.02
