### ISSUE TITLE
Gitlab- Similarity ID metadata placed at the end of the issue' summary paragraph

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#1343]
### Description

Gitlab issues contain a Similarity ID string at the end of the issue's paragraph instead of being place at the very end or elsewhere, it gives the false impression it is part of the issue's summary text.

### Expected Behavior

Similarity ID is placed elsewhere in the Gitlab issue (on its own line)

### Actual Behavior

Similarity ID is placed at the end of an issue' summary paragraph

### Reproduction

Generate a Gitlab issue 
Open the Gitlab issue to read it

### Environment Details

Docker image CxFlow: 1.7.0-17

**Comment by itsKedar** [comment]
Fixed in 1.7.02
