### ISSUE TITLE
BitBucket Cloud Source link broken when branch contains forward slash

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#159]
The logic used to determine the link to the exact line of source in within the repository will break for BitBucket when the branch contains a forward slash (i.e. feature/branch).

**Comment by MithileshPawar** [comment]
The workaround for this problem is to use the commit hash instead of the branch name. The latest hash which is stored in the scan request can be used here.
Encoding the branch name also doesn't work.

**Comment by MithileshPawar** [comment]
Closing the issue since the fix has been merged to develop.
