### ISSUE TITLE
Block Merge after scan completion on PR/MR

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#160]
Add the ability to block merge based on scan results filter for:

- [x] GitHub - **Done**
- [x] GitLab
- [x] Azure DevOps

**Comment by MithileshPawar** [comment]
This implementation is completed for GitHub integration.
A new configuration option is now available per repo config block:
github: ... block-merge: true error-merge: true

block-merge will block the merge during scan execution.
error-merge will fail the status , therefore blocking the merge. Closing and opening the PR again would be required to trigger the flow again. In the event the filter criteria for issues in CxFlow has any results, then this is considered a violation and will be a failure (based on severity, vulnerability type, cwe, status in Checkmarx, etc).

Block Merge (during scan):
![image](https://user-images.githubusercontent.com/61288229/82061148-52678c00-9696-11ea-95f3-fa05cbaf45bd.png)

Error Merge (based on any results meeting filter criteria/policy):
![image](https://user-images.githubusercontent.com/61288229/82061170-5abfc700-9696-11ea-9d50-1e332d7f86f2.png)

**Comment by kmcdon83** [comment]
Work is completed
