### ISSUE TITLE
Add Codebashing integration/support

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#163]
Introduce support for direct links to CB lessons based on findings.

Currentl CxFlow allows for a global training link that is referenced within the body of a ticket/issue, which can be the high level URL of Codebashing if desired. CxFlow should allow for deeper integration with Codebashing to introduce a link to the exact lesson that would aid in developers fixing/learning about the issue.

**Comment by jbrotsos** [comment]
Is it possible to have something like the mitre links (i.e. mitre-url: https://cwe.mitre.org/data/definitions/%s.html) in the ticket/issue?

codebash-url: https://cxa.codebashing.com/courses/%s/lessons/%s where the first string is equal to the coding language and the second string is the vulnerability (i.e https://cxa.codebashing.com/courses/nodejs/lessons/reflected_xss)

**Comment by kmcdon83** [comment]
> Is it possible to have something like the mitre links (i.e. mitre-url: https://cwe.mitre.org/data/definitions/%s.html) in the ticket/issue?
> 
> codebash-url: https://cxa.codebashing.com/courses/%s/lessons/%s where the first string is equal to the coding language and the second string is the vulnerability (i.e https://cxa.codebashing.com/courses/nodejs/lessons/reflected_xss)

This is what was first attempted, but it was quickly realized that there is not 1 to 1 mapping between SAST output for languages and the URL crafted for CB.  This was discussed with PM.  I will bring this up again during our next call.

**Comment by AvivCx** [comment]
Done
Add codebashing lessons per CWE (#558)
