### ISSUE TITLE
Link JIRA ticket to findings in Checkmarx

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#165]
Currently CxFlow publishes/updates findings in JIRA. The ticket that is generated however does not get reflected in Checkmarx.

CxFlow should associate the ticket with the finding(s) on the Checkmarx side to allow for reconciliation and for a reference point within the Checkmarx console.

**Comment by jbrotsos** [comment]
Closing old features that will not be implemented with CxFlow.
