### ISSUE TITLE
Update existing comments in Pull Request Feedback

### ISSUE THREAD

**Issue by skoyev** [checkmarx-ltd/cx-flow#185]
Reflect scan details in Pull/Merge feedback within already existing comments if a scan has triggered a second time. This is applicable to all repository types.

Sample implementation:
https://github.com/danger/danger/blob/56286aab4d3b9644eb6da5e81d0ab5b32575e9d4/lib/danger/comment_generators/github_inline.md.erb#L3

In addition, I think there should be some options for configuring how additional commits added to an existing PR are handled. Right now, if a PR is created, every time additional commit(s) are pushed to the PR HEAD, a new "scan submitted" comment is added and, more importantly, a new scan is queued. The latter means that the scan queue can very quickly become completely consumed by scan requests for a single PR of a single project, especially if the project/PR consists of a large code base and/or requires a full scan. In our current production environment, a single project has one PR that has resulted in 30 additional scans in the queue; this is made worse in our specific case because this particular project has > 1M lines of code and can only be handled by a small subset of our scan engines.

I'd propose handling this by updating CxFlow's PR processing behavior to do one or more of the following:

If a scan request exceeds the configured timeout in CxFlow, optionally cancel the actual scan itself.
Allow setting a configurable per-project webhook queue limit. Behavior might be that the queue is handled such that existing scan closest to completion/greatest progress % is left in queue, and then remaining queue size is allocated with most recent scan request prioritized. In other words, attempt to minimize time-to-results (by ensuring first/closest to completion scan is not canceled) while also ensuring most recently committed changes are added to the scan queue and older scans that have been queued but not started are canceled to make room for newest commits.

**Comment by mathroule** [comment]
+1 for the comment feature.
I also had Danger in mind regarding how it handle PR comments. Instead of creating a new comment each time, it will simply update the existing one.
Having the same mechanism for CX Flow would be really appreciable.

**Comment by kmcdon83** [comment]
Closing as this has now been implemented.
