### ISSUE TITLE
Allow for external script (Groovy) for Issue Descriptions

### ISSUE THREAD

**Issue by skoyev** [checkmarx-ltd/cx-flow#188]
Allow for external script (Groovy) for Issue Descriptions

Where do we envision the configuration for this Groovy script to be?

I suggest under cx-flow or/and per bug tracker implementation to allow different issue descriptions per service (the second would take priority). This would be an optional property.

The per implementation is more for cases where organisations have multiple different services which require possibly their own description format for each service and don't need two separate CxFlow instances to achieve this. This could also be achieved if we pass in the bug tracking system into the Groovy data binding as run-time.

Proposed Example:

cx-flow:
  // ...
  // The name of the property is subject to change
  script-issueDescription: "IssueDescription.groovy"

**Comment by jbrotsos** [comment]
Closing old features that will not be implemented with CxFlow.
