### ISSUE TITLE
Validate TFS/Azure DevOps Implementations

### ISSUE THREAD

**Issue by skoyev** [checkmarx-ltd/cx-flow#193]
Ensure CxFlow WebHooks and WorkItems work with the various flavors of Azure DevOps / TFS Server

- [x] Azure DevOps Cloud
- [ ] Azure DevOps 2019 Server
- [ ] TFS/Azure DevOps 2018 Server
- [x] TFS/Azure DevOps 2017 Server
- [ ] TFS/Azure DevOps 2015 Server

**Comment by jbrotsos** [comment]
Not supported old versions of TFS/Azure DevOps
