### ISSUE TITLE
Cx-Flow Jira statuses are case sensitive

### ISSUE THREAD

**Issue by robemmerson** [checkmarx-ltd/cx-flow#212]
### Description
When configuring Cx-Flow, Jira statuses (open and closed) need to have the correct casing within the config file, otherwise they will not be matched and therefore tickets will not transition correctly.

### Behavior
The majority of our tickets are in the 'PRIORITISED BACKLOG' status within Jira (Jira capitalises these, so I have too), but when the comparison actually occurs, the name of the status determined by Cx-Flow (presumably which pulled it from the Jira API call) is: 'Prioritised backlog'. If anything other than this exact casing is set within the config, then no transition will happen.

### Environment Details
Using on-prem Jira (v8.8.0) with the latest CxFlow (v1.5.4).

**Comment by robemmerson** [comment]
PR raised: https://github.com/checkmarx-ltd/cx-flow/pull/213

**Comment by kmcdon83** [comment]
The JIRA API is what requires case sensitivity.  

Even if we match based on ignoring case, when applying the transition this will be a challenge.  Closing as we do not plan to fix.
