### ISSUE TITLE
Support Scan Re-submission for active running scans

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#229]
### Describe the problem

When triggering a scan based on Pull Request event, the scan triggers, and this is followed by an additional update to the source branch, which sends a new request for scanning.  This will cause multiple scans to run and possibly collide or fail.

### Proposed solution

When an active scan is running for a project, and a new event comes through to submit a new scan for the same project, the scan request should fail and optionally based on a configuration element, cancel the original scan and submit the new scan.

**Comment by MithileshPawar** [comment]
This feature is now available in cxflow. Hence closing the issue.
