### ISSUE TITLE
Typo/Wording on "Issue Still Exists" Github comment.

### ISSUE THREAD

**Issue by michaelholt1995** [checkmarx-ltd/cx-flow#279]
### Description

On the "issue still exists" Github issue comment, there is a typo and some wording which reads slightly unnaturally. I'd also recommend a change to the pluralisation - see below.

### Actual Behavior

> Issue still exists.
> 
> SUMMARY
> Issue has _total_ **1 vulnerabilities** left to be **fix** (Please scroll to the top for more information)

### Expected Behavior

> Issue still exists.
> 
> SUMMARY
> Issue has ~~total~~ **1 vulnerability/vulnerabilities** left to be **fixed** (Please scroll to the top for more information)

### Reproduction

Have a Github issue created for a vulnerability, don't fix it and have Checkmarx pick it up again on a subsequent scan.

Code needing to be changed is line 79 on GitHubIssueCommentFormatter.java (happy to PR this myself).

### Environment Details

N/A

**Comment by AvivCX** [comment]
fixed by commit 60878a9
fix typo on issue-still-exist github issue (#295)
