### ISSUE TITLE
Azure DevOps: Support for Work Item Areas

### ISSUE THREAD

**Issue by GeekMasher** [checkmarx-ltd/cx-flow#291]
### Describe the problem

Azure DevOps supports what is called [Work Item Areas ](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/about-areas-iterations) which allows teams to place Work Items into subgroups in the boards. This is used typically with large projects teams that have multiple code repos in the same Azure Project.

### Proposed solution

Adding support for Work Item Areas. A user should be able to set the Area path in either the `application.yml` or a webhook parameter override.

For example, the default behavior is that the Work Item is placed into the main Work Items path (currently the default) but if a user supplies the "Area Path" then it will place the issues in a sub path.

### Additional details

No other information needed.

**Comment by carllaw6885** [comment]
Hey

If I'm understanding this correctly, you can already do this by using the alt-fields property. You provide a comma separated list of key/value pairs (field name:field value) and away you go.

For example, and we've just used it, something like

--alt-fields="Area Path:ABC", in our case this was [ProjectName]\[TeamName]. 

You can get the field names by clicking on the field label in DevOps.

**Comment by jbrotsos** [comment]
Closing old features that will not be implemented with CxFlow.
