### ISSUE TITLE
CLI Project Name with / returns 400

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#314]
### Description

Customer is passing a project name with / in the middle:

java -jar cx-flow-1.3.2.jar --scan --cx-project=dctrn_hello-world-maven_demo/checkmarx

In version cx-flow-1.3.2.jar, Cxflow was able to take that name and change to : dctrn_hello-world-maven_demo-checkmarx
 
However they reported with this latest version it is failing because of the /
 
HTTP error code 400 BAD_REQUEST while creating project with name dctrn_javaapp_test/k8sCheckmarx under owner id b2252452-0a5f-42a0-8a37-ab803e1a40ac

### Expected Behavior
Special chars are replaced with -

### Actual Behavior
HTTP error after substitution did not take place

### Environment Details

Works with version 1.3.2 but not with current build

**Comment by AvivCX** [comment]
I added a task to the backlog to fix this

**Comment by AvivCX** [comment]
Fix is available in version 1.6.3
