### ISSUE TITLE
CxFlow overrides the pre/post scan email added to Project in Checkmarx

### ISSUE THREAD

**Issue by MithileshPawar** [checkmarx-ltd/cx-flow#318]
### Description

> If an email address is added to a Project in Checkmarx (as pre-scan/post scan), after any scan gets triggered  for this project will override the scan settings with blank values.

![image](https://user-images.githubusercontent.com/61288229/86174065-fb573280-baee-11ea-8c1a-c00bed4f1996.png)

### Expected Behavior
> CxFlow should preserve the original Scan Settings for each project.
### Actual Behavior
> CxFlow only updates the project, preset, and engine configuration in ScanSettings. All the post-scan actions and email notifications in ScanSettings are getting omitted/ignored as of now.
### Reproduction
1. Open any project in Checkmarx and click on 'Advanced' tab for this project.
2. Click the 'Edit' button at the bottom.
3. Add email address to 'pre-scan' or post-scan' text box and click on 'Update' button at the bottom to save the changes.
4. Trigger a scan for the same project through cxflow by Push/Pull request.
5. After the scan is finished, open the Project Settings (as mentioned in step 1) and check if the previously added email addresses are present.

> - Screenshots
Before : 
![image](https://user-images.githubusercontent.com/61288229/86174437-a49e2880-baef-11ea-9207-b2b88fdd4575.png)

After scan is finished:
![image](https://user-images.githubusercontent.com/61288229/86174488-bda6d980-baef-11ea-9835-431ab17bb00d.png)

### Environment Details

> SAST 8.9 running on Windows Server 2016.

**Comment by kmcdon83** [comment]
@AvivCX  fyi - I think we need to enhance the logic to fall back on existing project configuration if the project exists, to preserve post-actions and other project details that might exists.

**Comment by AvivCX** [comment]
@alex-ko-dev isn't is covered by PR: 
Use existing SAST project configuration instead of global CxFlow configuration #226 ?

**Comment by alex-ko-dev** [comment]
@AvivCX , no, PR #226 is only about the `preset` and `engine configuration` properties, as specified in [WI 110](https://dev.azure.com/CxFlow/CxFlow/_workitems/edit/110/).

**Comment by AvivCX** [comment]
OK, thank you. I'll share with Aviram how to add this

**Comment by cxflowtestuser** [comment]
@AvivCX, @alex-ko-dev 

SAST has developed APIs to override project setting for a specific scan. the APIs that are used today are doing override globally - am I right to understand the issue ?
Post action are not overridable today per scan - are we using this API in CxFlow at all ? do we set post actions ?

**Comment by alex-ko-dev** [comment]
> the APIs that are used today are doing override globally - am I right to understand the issue ?

Not sure... It's better to ask SAST API developers


> are we using this API in CxFlow at all ?

I wasn't able to find any usages of this API in CxFlow.

**Comment by kmcdon83** [comment]
This has been fixed
