### ISSUE TITLE
Add Checkmarx SAST Remediation Advice Link to Issue Body

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#336]
### Describe the problem

Checkmarx SAST results contain a link to Remediation Advice (Issue description).  This detail is not provided in the body of an issue in any feedback channels for CxFlow (GitHub Issue, Jira, Rally, etc)

### Proposed solution

Add the link to the issue body that is generated

### Additional details

Data is already available in the result ouput.

**Comment by AvivCX** [comment]
I added a task to the backlog
