### ISSUE TITLE
Branch deletion doesn't use cx.config overrides of CxSAST team and project names

### ISSUE THREAD

**Issue by mpogr** [checkmarx-ltd/cx-flow#345]
### Description

When a branch is deleted in GitHub, the Webhook is called, but the Project and the Team names to be used in CxSAST are not adjusted to the settings from cx.config of the repo. This causes incorrect Project and Team names used in an attempt to delete the CxSAST project which, most times, is not found.

### Expected Behavior
cx.config overrides should be used as with every other events (Push and Pull Request)

### Actual Behavior
Default values (auto-generated project name and team name from the YML file) are used

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by AvivCX** [comment]
@mpogr  thank you for notify this issue
Task added to the backlog

**Comment by mpogr** [comment]
When is this going to be fixed? The current functionality of branch deletion is completely broken, in fact, it has a potential of deleting unrelated projects unintentionally. It's better to disable project deletion functionality altogether until this is fixed!

**Comment by AvivCX** [comment]
this is going to be fixed this week, and the fix will be part of next cxflow version

**Comment by AvivCX** [comment]
issue is resolved
