### ISSUE TITLE
Bitbucket Server : Comments more than 32768 characters cannot be posted.

### ISSUE THREAD

**Issue by MithileshPawar** [checkmarx-ltd/cx-flow#374]
### Description

> If the Checkmarx scan results contain more than 32768 characters, Bitbucket Server throws an error and cxflow is unable to post the comment with the scan results.

### Expected Behavior
CxFlow should be able to split the scan results (or comment) into different parts if the total characters in the comment exceed 32768 characters.

### Actual Behavior
The comment with the scan results doesn't get posted on the PullRequest page. Also as a side effect, the build status of the pull request also doesn't get updated.

### Reproduction
Initiate a PullRequest flow through the Bitbucket Server webhook and make sure the code to be scanned has lot of vulnerabilities (You can remove the filters from cxflow configuration, to get a higher number of vulnerabilities in the scan results).

### Environment Details

> Bitbucket Server 7.2.1

**Comment by MithileshPawar** [comment]
The fix for this issue would involve limiting the comment to the size of 32.768 characters and/or splitting the existing comment into multiple comments. But these approaches are not suitable since the markdown formatting will also be affected as a result of reducing the characters from the comment.
Hence a workaround to avoid this issue would be
a) Use of the property 'filter-severity' in the application yml 
    e.g-   filter-severity:
                     - High
                     - Low
   
    OR
b) Use of the property 'detailed' to disable the Detailed section from the scan results.
e.g- 
      bitbucket:
              detailed: false

**Comment by MithileshPawar** [comment]
Marking this bug as 'won't fix' and closing.

**Comment by AvivCx** [comment]
Thanks @MithileshPawar 
can you add references to the relevant documentation in wiki?

**Comment by MithileshPawar** [comment]
> Thanks @MithileshPawar
> can you add references to the relevant documentation in wiki?

Yes updated the comment with the help links.
