### ISSUE TITLE
Project renaming script is executed, but the new project name is ignored.

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#378]
### Description

When a Groovy script is provided that implements custom project naming, it does execute but the string it returns is ignored.  The project name that is used follows the default naming logic to create the name of the project.

Example script provided: [source_repo_name.groovy.txt](https://github.com/checkmarx-ltd/cx-flow/files/5050593/source_repo_name.groovy.txt)

### Expected Behavior
The name of the project that is used should be the value provided by the script.

### Actual Behavior
The default CxFlow project naming convention is used.

### Reproduction

Configure checkmarx.project-script to point to the script, then execute a scan. Example:

```
project-script: /app/source_repo_name.groovy
```

### Environment Details

Appears to work in any environment where CxFlow can execute.

**Comment by AvivCX** [comment]
Thank you @nleach999 , we will look into it

**Comment by AvivCX** [comment]
Hey @nleach999 
we looked again, and we were able to run the use the groovy script to determine the project name - as expected
can you share more details on your flow, and share the relevant part of the logs?

**Comment by nleach999** [comment]
Attached are logs and the configuration yaml used.  The logs show execution for the following release binaries:

cx-flow-1.6.0.jar
cx-flow-1.6.4.jar 
checkmarx/cx-flow:latest (jar from the official docker push)

(The last two are clearly the same based on hashes at beginning of logs)

In each log, observe:
```
2020-08-12 17:54:51.340  INFO 16 --- [      flow-web1] c.c.f.s.ProjectNameGenerator              [9TSKubci] : executing external script to determine the Project in Checkmarx to be used (/app/source_repo_name.groovy)
************SCRIPT***********
EXTERNAL SCRIPT projectName: [GITHUB]nleach999-SimplyVulnerable-demo-master
************SCRIPT***********
2020-08-12 17:54:51.651 DEBUG 16 --- [      flow-web1] c.c.f.s.ProjectNameGenerator              [9TSKubci] : Namespace, repo name and branch are specified. Using them all.
2020-08-12 17:54:51.651  INFO 16 --- [      flow-web1] c.c.f.s.ProjectNameGenerator              [9TSKubci] : Project name being used: nleach999-SimplyVulnerable-demo-master

```
The project name created/used on the server is confirmed to be `nleach999-SimplyVulnerable-demo-master` when it should be `-GITHUB-nleach999-SimplyVulnerable-demo-master` (after normalizing out the square brackets).

The flow is a simple webhook receipt from GitHub that invokes a scan.

[ProjectName.zip](https://github.com/checkmarx-ltd/cx-flow/files/5064772/ProjectName.zip)

I worked a bit more on it and discovered why my example is not working.  The working script is here: [source_repo_name-working.groovy.txt](https://github.com/checkmarx-ltd/cx-flow/files/5064920/source_repo_name-working.groovy.txt)

The output object of Groovy scripts for both project and team naming should probably be converted to a `java.lang.String` instance with a `toString()` invoke.  In the case of the script that is not working, it is returning an instance of `org.codehaus.groovy.runtime.GStringImpl` as shown in the log below:

```
cxflow-webhook_1  | 2020-08-12 18:23:42.724  INFO 16 --- [      flow-web1] c.c.f.s.ProjectNameGenerator              [qjGPJKrq] : executing external script to determine the Project in Checkmarx to be used (/app/source_repo_name.groovy)
cxflow-webhook_1  | ************SCRIPT***********
cxflow-webhook_1  | EXTERNAL SCRIPT projectName: :GITHUB:nleach999-SimplyVulnerable-demo-master
cxflow-webhook_1  | org.codehaus.groovy.runtime.GStringImpl
cxflow-webhook_1  | org.codehaus.groovy.runtime.GStringImpl
cxflow-webhook_1  | java.lang.String
cxflow-webhook_1  | ************SCRIPT***********
cxflow-webhook_1  | 2020-08-12 18:23:43.131 DEBUG 16 --- [      flow-web1] c.c.f.s.ProjectNameGenerator              [qjGPJKrq] : Project name override is present. Using the override: :GITHUB:nleach999-SimplyVulnerable-demo-master.
cxflow-webhook_1  | 2020-08-12 18:23:43.131 DEBUG 16 --- [      flow-web1] c.c.f.s.ProjectNameGenerator              [qjGPJKrq] : Project name (:GITHUB:nleach999-SimplyVulnerable-demo-master) has been normalized to allow only valid characters.
```

It will be very common for someone to write a Groovy script that does something like so:

```
return "[${request.repoType}]${request.namespace}-${request.application}-${request.branch}"
```

But in order for it to work, they'd have to convert it to a `java.lang.String` instance like so:
```
return "[${request.repoType}]${request.namespace}-${request.application}-${request.branch}".toString ()
```

Since the Groovy string result causes it to fail silently, it will be difficult for people to understand that they are returning a string that is really not a string.

**Comment by AvivCX** [comment]
Thank you @nleach999. we will look into it to find the best solution for this
@alex-ko-dev FYI
