### ISSUE TITLE
Add SCA results to GitLab Security Dashboard

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#389]
### Describe the problem

> GitLab has the ability to add dependency scanning results to it's Security Dashboard.  Please refer to: [Dependency Scanning](https://docs.gitlab.com/ee/user/application_security/dependency_scanning/).  We already support adding SAST results to the Security dashboard so it will fit in with displaying those results as well.

### Proposed solution

> Need to create an artifact after SCA scans invoked from GitLab that match the expected json format.  Refer to [Dependency Format](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/dependency-scanning-report-format.json) for exact json format.

**Comment by kmcdon83** [comment]
@jbrotsos this is next in the queue for me.

**Comment by pkdcloud** [comment]
Yes please, this would help greatly given our current workflow.

**Comment by brenwhyte** [comment]
I'd love to see this too.

**Comment by kmcdon83** [comment]
@pkdcloud  @brenwhyte  this effort is currently underway.  Hoping to be completed within a couple of weeks.

**Comment by jbrotsos** [comment]
This has been pushed in:  https://github.com/checkmarx-ltd/cx-flow/pull/528
