### ISSUE TITLE
Update Solution and/or Description in GitLab Issues and Security Dashboard

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#390]
### Describe the problem

> Currently, when creating an Issue in GitLab, the Description of the vulnerability is just a generic vulnerability type (i.e. Reflected_XSS_All_Clients)

![gitlab2](https://user-images.githubusercontent.com/10178859/90472938-7cd24680-e0d6-11ea-8f84-779712339463.png)

This is the same for the Security Dashboard as well.

![gitlab3](https://user-images.githubusercontent.com/10178859/90473052-cde23a80-e0d6-11ea-98b2-6b7da8d3c16b.png)

### Proposed solution

> Instead of a generic vulnerability type or solution, we can leverage the 9.0 API endpoint to get the [Short Vulnerability Description](https://checkmarx.atlassian.net/wiki/spaces/KC/pages/1534427435/Get+Short+Vulnerability+Description+for+a+Scan+Result+GET+sast+scans+id+results+pathId+shortDescription+v9.0.0+and+up).  We can also keep the link into Checkmarx as well as it's pretty beneficial.

**Comment by kmcdon83** [comment]
@jbrotsos this is a screen shot of issues created out of the Security Dashboard.  This is not the CxFlow implementation of the Issue.

CxFlow creates an issue with the same content as Jira and others.  This is the result of clicking the create issue link from the dashboard which is out of our control.

**Comment by kmcdon83** [comment]
> @jbrotsos this is a screen shot of issues created out of the Security Dashboard. This is not the CxFlow implementation of the Issue.
> 
> CxFlow creates an issue with the same content as Jira and others. This is the result of clicking the create issue link from the dashboard which is out of our control.

We will dive in to see what we can do here, if anything.

**Comment by jbrotsos** [comment]
Closing old features that will not be implemented with CxFlow.
