### ISSUE TITLE
Bitbucket Cloud : Formatting issues in the PR comment.

### ISSUE THREAD

**Issue by MithileshPawar** [checkmarx-ltd/cx-flow#426]
### Description

> The PR feedback comment from cxflow contains a few of the html tags that not rendered properly in the PR comment.

### Expected Behavior
HTML tags should get rendered with correct formatting.

### Actual Behavior
The HTML tags are visible and formatting is disturbed.

### Reproduction
>Setup webhook in bitbucket Cloud using Cxflow.
> Create a PR and wait for the scan to complete. 
> Once the scan finishes, refresh the PR page and verify the comments.

> - Screenshots
![image](https://user-images.githubusercontent.com/61288229/93828600-b5b38d00-fc39-11ea-9c77-19f0e2aa653a.png)

### Environment Details

> CxFlow : 1.6.8
Checkmarx SAST : 8.9/9.0

**Comment by NimrodGolan** [comment]
FIxed.
BitBucket has a limitation regarding images alignments since it won't use a standard Markdown design. In that case images won't be part of the PR summary design.
