### ISSUE TITLE
Bug Tracker of NONE not functioning as expected

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#445]
### Description

Bug Tracker of NONE not functioning as expected

### Expected Behavior

Bug Tracker of NONE should be used as an Async mode of scanning (results will not be waited for/processed)

### Actual Behavior

When using the bug tracker NONE, an exception is thrown as the report/results retrieval is attempted, and this will fail as the scan would not be completed.  Also, there is no need to pull / process the results here.

### Reproduction

User NONE as bug-tracker.

### Environment Details

Version 1.6.9

**Comment by AvivCX** [comment]
Fixed in cxflow-1.6.11
