### ISSUE TITLE
CxGo scan showing misleading hints

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ltd/cx-flow#447]
When team is not configured based on correct semantics, we get the errors below.

**com.checkmarx.sdk.exception.CheckmarxException: Parent team could not be established. Please ensure correct team is provided.
Some hints:
	- team name is case-sensitive
	- trailing slash is not allowed
	_**- team name separator depends on Checkmarx product version specified in CxFlow configuration:
		Checkmarx version: 8.9**_
		Separator that should be used: \

	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determineTeamAndOwnerID(ScanRequestConverter.java:114)
	at com.checkmarx.flow.service.SastScanner.executeCxScan(SastScanner.java:182)**

Since this is a CxGo scan, "Checkmarx version: 8.9" is irrelevant here and the line above saying it depends on the product version.

**Comment by AvivCX** [comment]
@kmcdon83 what should be the correct message?

**Comment by kmcdon83** [comment]
This was raised by someone in the field, and simply the fact that we have specifics around 8.9, and they were running CxGo version.
