### ISSUE TITLE
Wiki/Readme - Provide List of Webhook URL Override Parameters

### ISSUE THREAD

**Issue by michaelholt1995** [checkmarx-ltd/cx-flow#458]
### Describe the problem

Good afternoon,

There is currently no information available for the override parameters that can be used in the Github repository webhook URL. This can make implementing bespoke requirements per repository (different branches to analyse, folders to exclud etc.) difficult at times. 

### Proposed solution

There was a list formerly available on the previous repository at https://github.com/checkmarx-ts/cx-flow/wiki/CxFlow_Configuration#webhook-url-override-parameters---details-related-to-above but this has now been taken offline.

If the files still exist for this, it would be great if this information could be restored into this repository.

### Additional details

Cheers,
Michael

**Comment by kmcdon83** [comment]
@michaelholt1995 It looks like the path changed with our recent documentation that was published.
https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#webhook-url-override-parameters---details

**Comment by michaelholt1995** [comment]
Perfect, thanks a lot @kmcdon83!
