### ISSUE TITLE
Be able to determine the CxFlow version from the startup log spam in a Docker container

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#462]
### Describe the problem

When using a Docker container, the CxFlow startup log spam tells you it is using the cxflow jar like so:

```
2020-10-15 17:07:36.692  INFO 15 --- [           main] c.c.f.CxFlowApplication                   [] : Starting CxFlowApplication 
on 798b0e222237 with PID 15 (/app/cx-flow.jar started by root in /app)

```

It is difficult to tell from the logs which version of CxFlow is being used.  Often all we have are logs for troubleshooting.  Having versioning/hash information of the jar would allow us to know *exactly* which version of the jar was used to produce the log.  On occasion, asking someone which version they were using results in the wrong information.

### Proposed solution

Build the containers with the actual release jars named as they are downloaded from GitHub.  Something similar to the entrypoint script implemented in [CxFlowDemoInstance](https://github.com/checkmarx-ts/CxUtils/blob/master/CxFlowDemoInstance/cxflow-docker/cxflow-exec.sh) would be helpful to not only match the version but also the hash of the jar in use.  

The hash might help detect when someone is using a pre-release version of the jar that is mismatched with the latest pre-release version of the jar when both jars have the same name.

**Comment by kmcdon83** [comment]
@nleach999 - this is a great idea.

@AvivCX perhaps we can introduce this quite easily.
