### ISSUE TITLE
Typo in results JSON produced by CxFlow REST API

### ISSUE THREAD

**Issue by gemgit7** [checkmarx-ltd/cx-flow#474]
### Description

This was reported by a customer: The JSON produced by the CxFlow REST API has a typo. 
The blob includes an element spelled "sastRestuls" instead of "sastResults"

This is caused by the typo in the isScanRestuls() method in the ScanResults DTO class in the Checkmarx Springboot SDK project:
[ScanResults.java](https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/blob/7adf576892070b0005ea2bf5ddcc95e434502f7b/src/main/java/com/checkmarx/sdk/dto/ScanResults.java#L188)

### Expected Behavior
The JSON element should be "sastResults"

### Actual Behavior
The JSON element is misspelled - "sastRestuls"

### Reproduction
Execute the GET /scanresults REST API

Notice the misspelled JSON element.

### Environment Details

None

**Comment by AvivCX** [comment]
fixed by PR #504
