### ISSUE TITLE
cx-flow and cxflow sections?

### ISSUE THREAD

**Issue by kollol2k** [checkmarx-ltd/cx-flow#475]
### Description

> It might be a trivial thing but due to sparse documentation of CxFlow SCA related configurations, an user using a SAST related configuration finds it difficult to adapt. The reason being for SAST scans, 'cxflow' section was required. However, to add SCA scanning, you need to use 'cx-flow' instead of 'cxflow'. Why don't we just have only one section and call is cxflow or cx-flow? I would prefer the former. 

### Expected Behavior

> Pass regression

### Actual Behavior

> Doesn't launch SCA scan if we have 2 sections cx-flow and cxflow. 

### Reproduction

>

### Environment Details

> SAST ver 9.0. SCA (as of today).

**Comment by AvivCX** [comment]
Hi @kollol2k 
can you point us to where in SCA documentation it says 'cxflow' should use instead of 'cx-flow'?
thanks

**Comment by kollol2k** [comment]
> Hi @kollol2k
> can you point us to where in SCA documentation it says 'cxflow' should use instead of 'cx-flow'?
> thanks

Sorry but I didn't say use cxflow instead of cx-flow for SCA. On the contrary, it is the other way around. Pls let me explain. When I started using CxFlow, I was doing SAST scans only and for some reason the template that I started using, don't remember where I got it, had a cxflow section and not cx-flow section. You can check that if you want to merely run a SAST scan only, using cxflow instead of cx-flow works. However, when I configured SCA today, I realized that the section name is actually cx-flow and not cxflow. Question is if cx-flow supports both SAST and SCA scans for CxFlow, then no point supporting cxflow as section title for SAST only. Does that clarify?

Check this sample YMLs. This has cxflow instead of cx-flow. In fact, this should be wrong. 
https://github.com/checkmarx-ts/cicd-examples/blob/master/cxflow/YML-templates/application.yml
https://github.com/checkmarx-ts/cicd-examples/blob/master/cxflow/YML-templates/application-8.9.yml

**Comment by kmcdon83** [comment]
@kollol2k , that sample is incorrect.  It has been cx-flow since moving here. 

Initially we only supported SAST, which is under the checkmarx block, we then added support for sca, which we then sca block.

In the cx-flow block if you specify no vulnerability scanners, it defaults to SAST only, but if you want SAST and SCA or SCA only, you need to reflect that in your enabled-vulnerability-scanners:
```
cx-flow:
...
  enabled-vulnerability-scanner:
    - sca
    - sast
```

The cx-flow block has purposes of defining protect branching patterns, and other utilities (branch scripts), and high level filtering.  I believe SCA has a separate filtering logic defined @AvivCX can confirm this.

We will update those samples you reference, but I am not seeing a "bug" here.

**Comment by kollol2k** [comment]
> @kollol2k , that sample is incorrect. It has been cx-flow since moving here.
> 
> Initially we only supported SAST, which is under the checkmarx block, we then added support for sca, which we then sca block.
> 
> In the cx-flow block if you specify no vulnerability scanners, it defaults to SAST only, but if you want SAST and SCA or SCA only, you need to reflect that in your enabled-vulnerability-scanners:
> 
> ```
> cx-flow:
> ...
>   enabled-vulnerability-scanner:
>     - sca
>     - sast
> ```
> 
> The cx-flow block has purposes of defining protect branching patterns, and other utilities (branch scripts), and high level filtering. I believe SCA has a separate filtering logic defined @AvivCX can confirm this.
> 
> We will update those samples you reference, but I am not seeing a "bug" here.

Thanks for your response. If cx-flow is the correct title of the block where you can perform both SAST and SCA scans, then why do you need to support a block named cxflow (without the '-')? Simply remove the support as it doesn't work for SCA anyway.
