### ISSUE TITLE
Add Config server to execuble jar

### ISSUE THREAD

**Issue by alexandrececchin** [checkmarx-ltd/cx-flow#479]
### Describe the problem

I would like to be able to configure my application using the PCF config server to pass the application yml configuration, in this way is possible to secure the configuration file inside a different git repository.

### Proposed solution

This can be easily done by adding the 'io.pivotal.spring.cloud:spring-cloud-services-starter-config-client' dependency to the project.

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
