### ISSUE TITLE
Assign a predefined label to issues created in GitLab

### ISSUE THREAD

**Issue by alexlednik** [checkmarx-ltd/cx-flow#484]
### Describe the problem

> The issues listing doesn't allow to discern issues by severity or which version (e.g. Prod or Dev, etc.) the issue belongs to.

### Proposed solution

> Need the capability to assign predefined labels to issues created in GitLab with CxFlow.
For instance, would like to discern issues coming from “release version” or from other version, or put a tag depending on severity.

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
