### ISSUE TITLE
Be able to set M&O Policy to the project

### ISSUE THREAD

**Issue by alexlednik** [checkmarx-ltd/cx-flow#485]
### Describe the problem

> The customers can't use the CxM&O policies in the CxFlow configuration - this feature would help the customer keep their policies centralized.

### Proposed solution

> Need the capability to apply the CxM&O policies directly in the CxFlow configuration (instead of the CxFlow filters). Instead of the filters - enter the list of policy IDs / names. Should be able to filter the issues based on the policy ID / name.

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by kmcdon83** [comment]
We have no plans to support M&O policies within CxFlow.  M&O is in maintenance mode and no future developments against it will take place
