### ISSUE TITLE
CxSCA does not honor branch configuration

### ISSUE THREAD

**Issue by ghost** [checkmarx-ltd/cx-flow#492]
### Description

CxSCA scans with CxFlow do not honor the branch configuration within the .yaml file

### Expected Behavior

CxSCA should scan the pull request branch instead of the master branch and delete the branch after merge.

### Actual Behavior

CxSCA will only scan master branch instead of the pull request branch

### Reproduction

Configure .yaml file with CxSCA block.
Configure .yaml file to only scan multiple branches
Trigger a pull request with a fix and notice that CxSCA does not scan the pull request branch.
Merge the PR and notice that the project is not deleted in CxSCA.

Detailed setup steps can be found here - https://checkmarx.atlassian.net/wiki/spaces/PTS/pages/2251063576/Dev+Centric+IDE+Demo 

Screenshot shows that a new project is created, but no fixes are made
<img width="1638" alt="Sca Branch" src="https://user-images.githubusercontent.com/25393185/97770976-e4a50480-1afd-11eb-9bc8-b806e67568dc.png">

### Environment Details

CxFlow 1.6.11
CxSAST 9.2 HF3
GitHub
Windows Server 2016

**Comment by kmcdon83** [comment]
Branch support did not exist in SCA when this feature was developed.  We will add this to the list of features to be implemented and review with Product team.

**Comment by jbrotsos** [comment]
This feature now exists
