### ISSUE TITLE
GitHub Pull Request MarkUp is not posted on subsequent pushes to a pull request

### ISSUE THREAD

**Issue by sqbush** [checkmarx-ltd/cx-flow#493]
### Description

GitHub PR MarkUp is not posted on subsequent pushes to a pull request

### Expected Behavior

After a push occurs to an existing pull request, CxFlow triggers another scan and the results are shown in the pull request markup.

### Actual Behavior

After a push occurs to an existing pull request, CxFlow triggers another scan, but the results are NOT shown in the pull request markup.

### Reproduction

Configure CxFlow and submit a pull request to trigger a CxSAST scan
Before merging the PR in GitHub, push another change to the branch
CxFlow trigger a scan, but will not post into the PR.
Screenshot below shows a new push, but no markup with CxFlow running

### Environment Details

CxFlow 1.6.11
CxSAST 9.2 HF3
GitHub
Windows Server 2016
<img width="1254" alt="No markup" src="https://user-images.githubusercontent.com/25393185/97771138-8547f400-1aff-11eb-9f90-29912bb15a6f.png">

**Comment by kmcdon83** [comment]
@sqbush a while back we introduced a change such that the existing PR comment was updated and no new comments would be added.  @AvivCX, please correct me if this is not the case.

We had several requests to stop spamming the comment section.  If this behavior is not working, then we need to address it.

**Comment by sqbush** [comment]
@kmcdon83 makes perfect sense to remove the spamming of the comment section.  Shouldn't we only be scanning once per pull request then?  The push to an open PR still currently triggers a CxSAST scan but does not post results to the PR.

**Comment by AvivCX** [comment]
@sqbush, the purpose is to override the original comment - if the results have changed, and to show only the latest scan results in the pull request comment
I verified, when I commit changes to open pull request, new scan is triggered and cxflow override the pull request comment with the new results
Isn't that what you see?

**Comment by kmcdon83** [comment]
> @kmcdon83 makes perfect sense to remove the spamming of the comment section. Shouldn't we only be scanning once per pull request then? The push to an open PR still currently triggers a CxSAST scan but does not post results to the PR.

The most common thing we see is that a PR is opened, and then updates are made to the branch afterwards.  The integrity of the scan on initial PR creation is in question at this point.  We can have a discussion around the use case to make sure we are aligned.

**Comment by sqbush** [comment]
@AvivCX - Just tested and I am seeing the PR markdown being updated.  This is great!!!  We should close this issue as rejected and add some documentation somewhere on this describing the functionality of how PR markdown is updated.

**Comment by AvivCX** [comment]
Thanks @sqbush 
I will update the relevant page
