### ISSUE TITLE
Add the ability to define the "Reporter"field in JIRA

### ISSUE THREAD

**Issue by checkmarxSE** [checkmarx-ltd/cx-flow#497]
### Describe the problem

> Currently, the reporter field in JIRA is listed as the service account e-mail that creates the ticket. Some organizations have internal policies that humans reporters must be associated with security bugs / issues in defect management tools. To address this, the fields must be changed manually after the fact.

### Proposed solution

> Either allow the reporter field to be a static value set in the config file or allow for certain fields in the github project to be pulled and then assigned to the reporter field.

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
