### ISSUE TITLE
Map and/or override JIRA field id/key to the field name

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#502]
### Describe the problem

> Be able to map and set a field's id or key in JIRA for a given field name, mainly for custom fields.
> In Jira, one can have the same field repeated/duplicated with the same name, but they will have different custom id's.
> Custom field names might change in time or be created to have same duplicate names, so being able to set the custom id can be useful to have the correct id for the custom field when fields end up being deprecated or changing names (but keeping the same id).

### Proposed solution

> 1) Simplest way would be to set the jira-field-key or jira-field-customid for each type on the fields block of the JIRA fields mapping.
> 2) Add a way of processing a set of tuples - for example, like in JSON [ {<custom field name>: <custom field id>} ] - on the _jira_ _yaml_ block that has the mapping of the current custom field nameand it's custom id for an issue created on that specific JIRA project. This could be achieved through overrides in webhooks or _cx.config_ file or through a file that would have a mapping in JSON and was read using a groovy script.

### Additional details

> N/A

**Comment by kmcdon83** [comment]
@cx-scord we already support providing custom field names and associated field types.  We also support static default values.  Is this not the use case you are looking for here?

**Comment by cx-scord** [comment]
> @cx-scord we already support providing custom field names and associated field types. We also support static default values. Is this not the use case you are looking for here?

Just to be clear, you referring to the "custom fields" under CxSAST defined in the Management->"Manage Custom Fields" option, correct?

If so, unfortunately CxGO doesn't support this (yet) at least, but if I map a field type/name that will never be received to a jira-default-value, that value will always be filled, no matter if it comes from CxSAST/CxGO, correct?

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
