### ISSUE TITLE
Cx-Flow --include-files option

### ISSUE THREAD

**Issue by mfeferman-cx** [checkmarx-ltd/cx-flow#507]
**Describe the Problem**
Currently, when using Cx-Flow in CLI mode, it is possible to exclude files (--exclude-files) from the scan.  However, it is not possible to specify files to ‘Include’, similar to several of our UI components (e.g., Jenkins plugin or the CxWebClient).  

**Proposed Solution**
Add the ability to specify file types (e.g., *.pl) as a command-line option in Cx-Flow, to be able to specify only files to 'include' in the scan.  Use an "--include-files" command-line option, so that a file type(s) can be specified, similarly to the "--exclude-files" option.

**Additional details**
When creating the zip file with "--include-files", it will be more efficient if the zip file created (by Cx-Flow) only contains the files specified, instead of zipping all files and having the manager handle the "--include-files" command.  The same logic should be applied to the "--exclude-files" command-line option.

**Comment by cx-scord** [comment]
Just in case it's not forgotten, there should also be a `--include-folders ` parameter.

**Comment by jbrotsos** [comment]
It is suggested to have a wrapper around CxFlow and remove any source file types you don't want to scan.

**Comment by mfeferman-cx** [comment]
Yes, that is functionality of the script that I wrote, but applying that same logic, why don’t we just take the “—exclude-files” option out of Cx-Flow and perform the same action in the wrapper?

Mark Feferman CISSP, CSSLP, CISM, CxCE | National Channel SE – North America | mark.feferman@checkmarx.com<mailto:mark.feferman@checkmarx.com> | +1 713 478-5150 | Checkmarx<https://www.checkmarx.com/>

https://calendly.com/mark-feferman

**Comment by jbrotsos** [comment]
Hey @mfeferman-cx,

An API is used:  https://checkmarx.atlassian.net/wiki/spaces/KC/pages/334168655/Set+Project+Exclude+Settings+by+Project+Id+-+PUT+projects+id+sourceCode+excludeSettings+v8.7.0+and+up

There is no equivalent for include pattern settings.

**Comment by cx-scord** [comment]
> Hey @mfeferman-cx,
> 
> An API is used: https://checkmarx.atlassian.net/wiki/spaces/KC/pages/334168655/Set+Project+Exclude+Settings+by+Project+Id+-+PUT+projects+id+sourceCode+excludeSettings+v8.7.0+and+up
> 
> There is no equivalent for include pattern settings.

At least For CxGO, you can ignore the CxSAST API since it's CxFlow that sends the zip, so the implementation of this feature `include-files/folders` could start from there if the only constraint is the API. Then, maybe work with product to include it in the API?

**Comment by cx-scord** [comment]
@jbrotsos I would like to rekindle discussion on this to add a request to add a `cx-flow.zip-includes` option to complement the `cx-flow.zip-excludes` option added a few months ago.

This option would have priority over `zip-excludes`, meaning that everything that would be excluded by `zip-excludes` should be re-added if it's included in `zip-includes` but, to simplify development, in a first phase the `zip-includes` could be mutually exclusive from `zip-excludes` but still having priority, meaning, if `zip-includes` and `zip-excludes` are both set, then it would be the `zip-includes` parameter to prevail.

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
