### ISSUE TITLE
cxflow is closing open (non-checkmarx) issues in GitLab

### ISSUE THREAD

**Issue by brenwhyte** [checkmarx-ltd/cx-flow#508]
### Description
As per title, cxflow is closing open (non-checkmarx) issues in GitLab 

### Expected Behavior
Issues that are created that are **not** related to CheckMarx are to remain as is, untouched by the CheckMarx integration.
### Actual Behavior
Non checkmarx related issue gets closed. 
### Reproduction

Create a fresh, un-scanned project in GitLab
Create a test  dummy issue and leave that open.
Commit an `cx.config` file in order to scan repo and commit the changes to default branch so issue are created.
Issues are created for each vulnerability found (as expected) but dummy issue gets closed.

If I re-open the issue and another checkmarx scan is run the issue gets closed again.

### Environment Details

GitLab.com (Gold)
CxFlow 1.6.11 (java)
WebHook configuration

**Comment by kmcdon83** [comment]
@brenwhyte I just wanted to check if your issue that was no raised by CxFlow started with the prefix of "CX "?

Currently, this is how the logic works.  We pull all issues that start with CX, so if this is part of your issue title, it gets included in the existing issue set.

**Comment by brenwhyte** [comment]
Correct, the issue was called "Test issue", or something to that effect.

Thanks Ken

**Comment by brenwhyte** [comment]
Another bit of testing this morning. 

Another issue called "test issue two" exhibits the same issue. Also, if I re-open the issues Checkmarx re-closes them on the next scan of default master branch.

**Comment by MithileshPawar** [comment]
The fix has been done, tested, and merged.
Closing the issue for now.

**Comment by kmcdon83** [comment]
@brenwhyte the fix can be found here:
https://github.com/checkmarx-ltd/cx-flow/releases/tag/1.6.13

It is pre-release status, and should be official release of 1.6.13 shortly.

**Comment by brenwhyte** [comment]
Thanks guys for the quick turnaround and fix. Happy to report the issue is now resolved.
