### ISSUE TITLE
Please ensure GIT is defined within Checkmarx

### ISSUE THREAD

**Issue by kollol2k** [checkmarx-ltd/cx-flow#526]
### Description

Trying to run a scan triggered for push to a repo hosted in ADO cloud (Cx domain accounts) but it fails with the following error:

com.checkmarx.sdk.exception.CheckmarxException: Error occurred while adding source details to project.  Please ensure GIT is defined within Checkmarx
	at com.checkmarx.sdk.service.CxService.setProjectRepositoryDetails(CxService.java:1237)
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1666)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scan(AbstractVulnerabilityScanner.java:101)
	at com.checkmarx.flow.service.FlowService.lambda$runScanRequest$3(FlowService.java:61)

SAST 9.2 HF4
Git is properly configured. git version 2.29.2.windows.2.
CxFlow 1.6.12 tried older version 1.6.9 (same issue)

The same token and repo URL is accessible from SAST UI. I could git clone too from a Git bash shell.  

### Expected Behavior

Scan completes in SAST.

### Actual Behavior

Scan fails to trigger. No project created.

### Reproduction

- Log files
[flow_azure.log](https://github.com/checkmarx-ltd/cx-flow/files/5525536/flow_azure.log)

- Application settings

The YML file that I used.
[application-azure-sample.zip](https://github.com/checkmarx-ltd/cx-flow/files/5525864/application-azure-sample.zip)

### Environment Details

- Windows server 2012 hosting CxFlow and SAST. ADO hosted in cloud.

**Comment by MithileshPawar** [comment]
Hi @kollol2k,

I have checked the mentioned scenario using ADO cloud and local SAST instance. And it seems to be working fine.

Also kindly provide the azure url in the application context as  'url: https://dev.azure.com'. The Org name at the end of the url is not needed anymore. Although this is not the reason for the error that you are seeing, it would have thrown an error when it would try to get the issues from ADO.

**Comment by kmcdon83** [comment]
@kollol2k as mentioned by Mith, we cannot reproduce this.  I believe we may need to dig into your SAST setup.  I believe if you tried to simply create a project/scan manually via API calls, you will see the same issue, which is not a CxFlow issue, but an API/Git Client issue.

Please take internal setup/config issues and bugs to our Teams channel internally in the future please.
