### ISSUE TITLE
Links to source code in PRs point to null file

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#527]
### Description

This is seen when using the CxFlow CLI mode in the supported docker container.  I haven't seen this in the Webhook mode.

When integrating the SAST scan results into the PR, the links to the source line points to a null file.  When clicking on the link, it takes you to the home page.

![image](https://user-images.githubusercontent.com/10178859/98873574-86e1b800-242d-11eb-8cc6-4edefd9aa3ec.png)

### Expected Behavior

When clicking on the link to the source line, it should take you to that line of source.

### Actual Behavior

It takes you to the home page or error page depending on the SCM. 

### Reproduction

- Using a GitHub Action or GitLab CI pipeline, submit a PR (must be via the CxFlow CLI mode)
- Review the PR
- Click on the link of the source file.

### Environment Details

GitHub & GitLab both see the same issue.

**Comment by AvivCX** [comment]
@jbrotsos , are you able to provide logs of this scenario?
Thanks

**Comment by jbrotsos** [comment]
@AvivCx Let me know the logs and the debug settings you want me to use to create the logs.
