### ISSUE TITLE
cx-flow - config-as-code - excludeFiles not working

### ISSUE THREAD

**Issue by mfeferman-cx** [checkmarx-ltd/cx-flow#543]
### Description

It seems that when using Cx-Flow in config-as-code mode, the specifier in the cx.config file does not actually exclude those files.  

### Expected Behavior
Even if all files are zipped and sent to the manager, where the exclusion should happen, it's not and the files are include in the LOC count, etc.

### Actual Behavior
Excluded files are being included...

### Reproduction

Add and remove the 'excludeFiles' and there's no difference in the scan results.

Using this repo:
https://github.com/mfeferman-cx/CxWorkshop

If you use the cx.config file as is, it does NOT exclude java files.

Are we using the correct key name for 'excludeFiles', because this shows a different name (excludeFilesPattern).
https://cxprivatecloud.checkmarx.net/cxrestapi/help/swagger/ui/index#!/GENERAL/ExcludeSettings_PutByidexcludeSettings

### Environment Details

Running ngrok on my laptop.  I have cx-flow-1.6.13 configured with webhooks for that repo above.  All of that plumbing works, however, with the excludeFiles specification in the cx.config, it still includes the vuln.java file...

**Comment by AvivCX** [comment]
@kmcdon83 , if I understand correctly, this property should set to 'true' in order to the exclude details override the project settings:

```
checkmarx
  ...
  settings-override: true
```

am I right?

**Comment by kmcdon83** [comment]
> @kmcdon83 , if I understand correctly, this property should set to 'true' in order to the exclude details override the project settings:
> 
> ```
> checkmarx
>   ...
>   settings-override: true
> ```
> 
> am I right?

Yes, though I believe the default value, when not provided, is true.

**Comment by mfeferman-cx** [comment]
Thank you Aviv and Ken.  Yes, by setting this value, my settings worked!
