### ISSUE TITLE
CxFlow hangs when including an external scripts, on Linux

### ISSUE THREAD

**Issue by agehring** [checkmarx-ltd/cx-flow#546]
### Description

When configuring CxFlow (1.6.13) to use a "branch", "Project" or "Team" groovy script, the process hangs after:
2020-11-25 11:59:26.393 DEBUG 18659 --- [           main] o.s.b.f.s.DefaultListableBeanFactory      [] : Creating shared instance of singleton bean 'cxGoProperties'

### Expected Behavior
Finish loading, process groovy script on event

### Actual Behavior
Process hangs, requires 'kill -9' to terminate 

### Reproduction
On Linux, include a branch-script, project-script or team-script entry in the config YAML, e.g.:

checkmarx:
    branch-script: /opt/CxFlow/branch.groovy

start CxFlow, e.g.;
java -jar cxflow-1.6.13.jar

Console (with 
### Environment Details

Distribution: 
Ubuntu 18.04 - Fully patched

Java: 
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

**Comment by AvivCx** [comment]
Hi @agehring 
was this resolved?
