### ISSUE TITLE
Provide PR ID or CommitID from GitHub with a scan request

### ISSUE THREAD

**Issue by kwdeike** [checkmarx-ltd/cx-flow#550]
### Describe the problem

> In order for customers to correlate scans, the PR ID or CommitID data needs to be retained and provided.  

### Proposed solution

> A clear description of what you want to happen.

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by jbrotsos** [comment]
@kwdeike do you mind adding more details and a use case please?  Please be specific on what type of scans you want to correlate.

**Comment by jbrotsos** [comment]
@kwdeike Would it be acceptable if the PR was to add the ability to add a scan comment?

**Comment by kwdeike** [comment]
@jbrotsos That's a good approach.   The Comment field could then be parsed to pull the PR ID and retain traceability to the initiating scan event.

**Comment by jbrotsos** [comment]
Add flag to add PR info to scan comment

**Comment by satyamchaurasiapersistent** [comment]
https://github.com/checkmarx-ltd/cx-flow/pull/1147
