### ISSUE TITLE
GitHub App support broken for Enterprise < 2.22

### ISSUE THREAD

**Issue by milo-minderbinder** [checkmarx-ltd/cx-flow#554]
### Description
GitHub App based integration does not work on GitHub Enterprise Server versions before 2.22 (the most recent point release), due to hard coded API version string sent in the `Accept` HTTP header sent by CxFlow in GitHub REST API requests. The GitHub App (aka integration) API has only been available in Enterprise as a feature preview until the most recent 2.22 release, and in [versions prior required a custom media type](https://docs.github.com/en/enterprise-server@2.21/rest/overview/api-previews#integrations) to be specified in the Accept header. Since [2.22 has only been available since September 2020](https://enterprise.github.com/releases/2.22.0/notes), this prevents use of GitHub app integration for a lot of enterprise deployments.

### Expected Behavior
Installing and configuring GitHub App integration should work for all (or at least 3 most recent) supported versions of Enterprise.

### Actual Behavior
GitHub App API calls from CxFlow fail due to missing/incorrect content type specified in Accept header.

### Reproduction
Install and configure GitHub App integration in GitHub Enterprise 2.21 or earlier and note that any parts of the flow which require calling out to GitHub API will fail (eg PR comments will not be posted, nor status set, etc.).

Then, checkout CxFlow source at most recent (as of this writing) 1.6.15 release tag and apply the patch below with `git am <path/to/patch-file.patch>` and rebuild and deploy CxFlow in web mode. Observe that the the CxFlow calls to GitHub Enterprise Server’s REST API now work successfully and App based integration for CxFlow works as expected.

Incidentally, the patch below has also been tested with public GitHub (github.com) and still works there too, since both the v3 and machine-man-preview media types are included. However, it would probably be better to get the version information for the configured GitHub server by calling the meta API instead of trying to hard code version specifiers.

### Environment Details
Issue has been observed/tested in GitHub Enterprise Server version 2.21.

### Patch for Workaround

```diff
From 014b37b38bf90d4d7a7ffa8d259f5f8616b11057 Mon Sep 17 00:00:00 2001
From: Milo Minderbinder <minderbinder.enterprises@gmail.com>
Date: Wed, 2 Dec 2020 16:25:23 -0500
Subject: [PATCH] fix Accept header to support GitHub Apps on GHE before 2.22

---
 .../java/com/checkmarx/flow/service/GitHubAppAuthService.java   | 2 +-
 src/main/java/com/checkmarx/flow/service/GitHubService.java     | 1 +
 2 files changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java b/src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
index fbd7bf6..ca3b63b 100644
--- a/src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
+++ b/src/main/java/com/checkmarx/flow/service/GitHubAppAuthService.java
@@ -96,7 +96,7 @@ public class GitHubAppAuthService {
 
         HttpHeaders httpHeaders = new HttpHeaders();
         httpHeaders.set(HttpHeaders.AUTHORIZATION, BEARER_HEADER.concat(jwtToken));
-        httpHeaders.set(HttpHeaders.ACCEPT, "application/vnd.github.v3+json");
+        httpHeaders.set(HttpHeaders.ACCEPT, "application/vnd.github.machine-man-preview+json, application/vnd.github.v3+json");
 
         ResponseEntity<JsonNode> response = restTemplate.exchange(
                 properties.getAppUrl().concat(INSTALLATION_TOKEN_PATH),
diff --git a/src/main/java/com/checkmarx/flow/service/GitHubService.java b/src/main/java/com/checkmarx/flow/service/GitHubService.java
index 3837f79..e7a94bd 100644
--- a/src/main/java/com/checkmarx/flow/service/GitHubService.java
+++ b/src/main/java/com/checkmarx/flow/service/GitHubService.java
@@ -97,6 +97,7 @@ public class GitHubService extends RepoService {
             );
             httpHeaders = new HttpHeaders();
             httpHeaders.set(HttpHeaders.AUTHORIZATION, "token ".concat(token));
+            httpHeaders.set(HttpHeaders.ACCEPT, "application/vnd.github.machine-man-preview+json, application/vnd.github.v3+json");
         }
         else{
             httpHeaders = new HttpHeaders();
-- 
2.29.2
```

**Comment by kmcdon83** [comment]
@milo-minderbinder we will externalize a property for this, defaulting to non-preview if not provided.
