### ISSUE TITLE
Fork based git flow broken in GitHub integration

### ISSUE THREAD

**Issue by milo-minderbinder** [checkmarx-ltd/cx-flow#555]
### Description
At least for GitHub (public and enterprise), CxFlow does not currently support webhook and/or GutHub App based integration for dev teams that use a fork based git flow — meaning, they create PRs by first forking the repo and then creating a PR from their fork.

Push events to default branch and/or branches that match CxFlow’s configured branch filter are processed correctly, but pull_request events have/cause numerous issues when PRs come from forks.

### Expected Behavior
Both push and pull request events are able to be processed correctly whether PR is from a branch in the same repo, or from a branch in a forked repo.

### Actual Behavior
The `pull_request`events are incorrectly/not processed in many common scenarios, for example:
1. If PR is from a branch in forked repo that is the same as an existing branch in base/source repo that has a Checkmarx project, PR will overwrite the existing Checkmarx project. Concrete example: default branch in source repo is “main”, dev forks repo and makes changes to the “main” branch of their fork, the creates a PR. CxFlow (in default project name config with no overrides/script) will overwrite the existing project config and scan results for the Checkmarx project, possibly then causing issues depending on configured issue integration with Jira, etc..
2. Branch/tag deletion events are never generated for from forked repos, so Checkmarx projects created by CxFlow from pull request events are never deleted by CxFlow, even if the forked repo itself is deleted.
3. Two or more PRs from separate forked repos but from the same branch name in those forks (e.g. two devs make changes in their own fork in a branch called “develop” and both create PRs) will result in a single Checkmarx being created and one will overwrite project config and scan results for the other.
4. I’ve not tested to confirm, but am pretty sure similar issues to 1 and 3 above would arise in the case where a PR is created from a forked repo with a different _repo name_ than the source. This happens, for example, if, as a dev, I work on repos in multiple orgs/namespaces and I try to fork a repo called “deployment” in org “foo”, and then fork a repo called “deployment” in another org called “bar”. The second forked repo is named “deployment-1” by default by GitHub.

### Reproduction
See above.

### Environment Details
CxFlow 1.6.15 with no overrides, config as code, or custom project naming groovy script.

**Comment by kmcdon83** [comment]
@milo-minderbinder we will take a closer look at this scenario

**Comment by kmcdon83** [comment]
@milo-minderbinder , we were not capturing the namespace (org) correctly, which causes team to be incorrect.  I am submitting a PR to correct this.

1,2,4 should be addressed here.  2 would be addressed if we deleted the project for a PR close event.  There is another issue open for that, so I would like to close this with the PR fix.  We will look at the feature for github PR closure with Product next.

**Comment by milo-minderbinder** [comment]
@kmcdon83 @AvivCx I think I gave this the thumbs-up prematurely. Since we've deployed the latest release, this fix is causing issues and after some more digging, it's not clear how to handle it. With #569 in place, when a developer creates a PR from a fork, no one besides the developer who created the pull request is actually able to review the scan results. Our high-level requirements for how CxFlow handles PRs are:
1. Anyone who has access to the Checkmarx team corresponding to the PR's base branch (e.g. the branch of the repo that the PR was created against) should have access to the PR scan kicked off by Checkmarx
2. Each unique repo + branch combination should have its own project in Checkmarx, so that Checkmarx projects don't get overwritten if, e.g., two PRs are opened from identically named branches in separate forked repos
3. Regardless of whether the PR came from a branch in the same repo or from a branch in forked repo, the rules above should still be met

To make this behavior work in our environment, we had been using a custom project name groovy script that set the project name to `<HEAD_ORG_NAME>-<BASE_REPO_NAME>-<HEAD_BRANCH_NAME>`. With the change from #569, our plan was to use a custom team name groovy script that would set the team name based on the PR base branch's org name (the old behavior before namespace was remapped to the head branch's org name). However, this didn't work because of differences in how the team name is handled when overridden as defined in [`ScanRequestConverter.determineTeamAndOwnerID(ScanRequest)`](https://github.com/checkmarx-ltd/cx-flow/blob/1.6.19/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java#L76).

As you can see, if no custom script is used to override the team name, the default behavior is to [combine the "base" team from cxProperties with the namespace](https://github.com/checkmarx-ltd/cx-flow/blob/1.6.19/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java#L94) to get the full team name, then, if multi-tenant mode is on, create the full team name in Checkmarx if it does not already exist. The team is also set in the ScanRequest.

However, if you use a custom team name groovy script to override the team name, your custom script will have to duplicate the above logic, because [these lines](https://github.com/checkmarx-ltd/cx-flow/blob/1.6.19/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java#L82-L87) set the team name to the output of the groovy script verbatim, and there is no check for multi-tenant mode to create the team if it doesn't already exist. This is especially challenging because the groovy script would need to import and configure an `ILegacyClient` instance to check if the desired team exists already and, if not, create it. Since the groovy scripts only have access to the `ScanRequest` object, I think it makes more sense for them to be as simple as possible, just returning the string value for the desired project/team/comment, and then CxFlow should handle any business logic necessary.

I created a small patch to reduce code duplication, clarify log messages, and tweak the behavior so it works as I described above - hopefully this is in line with what was intended in the first place. If not, let me know how we can achieve the desired behavior with minimal "magic" in the team groovy script.

```diff
diff --git a/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java b/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
index b3af5de5..307ef4bb 100644
--- a/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
+++ b/src/main/java/com/checkmarx/flow/sastscanning/ScanRequestConverter.java
@@ -75,32 +75,26 @@ public class ScanRequestConverter {
 
     public String determineTeamAndOwnerID(ScanRequest request) throws CheckmarxException {
         String ownerId;
-        String namespace = Optional.ofNullable(request.getNamespace()).orElse(EMPTY_STRING);
 
+        String baseTeam = cxProperties.getTeam();
+        if (!baseTeam.startsWith(cxProperties.getTeamPathSeparator())) {
+            baseTeam = cxProperties.getTeamPathSeparator().concat(baseTeam);
+        }
         String team = helperService.getCxTeam(request);
         if (!ScanUtils.empty(team)) {
-            if (!team.startsWith(cxProperties.getTeamPathSeparator()))
-                team = cxProperties.getTeamPathSeparator().concat(team);
             log.info("Overriding team with {}", team);
-            setShardPropertiesIfExists(request, team);
-
-            ownerId = determineOwnerId(request, team);
-
         } else {
-            team = cxProperties.getTeam();
-            if (!team.startsWith(cxProperties.getTeamPathSeparator()))
-                team = cxProperties.getTeamPathSeparator().concat(team);
-            log.info("Using Checkmarx team: {}", team);
-            String fullTeamName = cxProperties.getTeam().concat(cxProperties.getTeamPathSeparator()).concat(namespace);
-            setShardPropertiesIfExists(request, fullTeamName);
-
-            ownerId = determineOwnerId(request, team);
-            if (cxProperties.isMultiTenant() && !ScanUtils.empty(namespace)) {
-                ownerId = aquireTeamMultiTenant(request, ownerId, namespace, fullTeamName);
-            } else {
-                request.setTeam(team);
-            }
+            team = Optional.ofNullable(request.getNamespace()).orElse(EMPTY_STRING);
+        }
+        String fullTeamName = baseTeam.concat(cxProperties.getTeamPathSeparator()).concat(team);
+        log.info("Using Checkmarx team: {}", fullTeamName);
+        setShardPropertiesIfExists(request, fullTeamName);
+        if (cxProperties.isMultiTenant() && !ScanUtils.empty(team)) {
+            ownerId = acquireTeamMultiTenant(baseTeam, team);
+        } else {
+            ownerId = scannerClient.getTeamId(baseTeam);
         }
+        request.setTeam(fullTeamName);
 
         //Kick out if the team is unknown
         if (ownerId.equals(UNKNOWN)) {
@@ -123,19 +117,18 @@ public class ScanRequestConverter {
                 : scannerClient.getTeamId(team);
     }
 
-    private String aquireTeamMultiTenant(ScanRequest request, String ownerId, String namespace, String fullTeamName) throws CheckmarxException {
-        request.setTeam(fullTeamName);
-        String tmpId = scannerClient.getTeamId(fullTeamName);
-        log.info("Existing team with " + fullTeamName + " was not found. Creating one ...");
-        if (tmpId.equals(UNKNOWN)) {
+    private String acquireTeamMultiTenant(String baseTeamName, String teamName) throws CheckmarxException {
+        String fullTeamName = baseTeamName.concat(cxProperties.getTeamPathSeparator()).concat(teamName);
+        String ownerId = scannerClient.getTeamId(fullTeamName);
+        if (ownerId.equals(UNKNOWN)) {
+            log.info("Existing team with " + fullTeamName + " was not found. Creating one ...");
+            String baseTeamId = scannerClient.getTeamId(baseTeamName);
             try {
-                ownerId = scannerClient.createTeam(ownerId, namespace);
+                ownerId = scannerClient.createTeam(baseTeamId, teamName);
             }catch(Exception e){
-                log.error("Existing team with " + fullTeamName + " was not found.");
+                log.error("Existing team with " + baseTeamName + " was not found.");
                 ownerId = UNKNOWN;
             }
-        } else {
-            ownerId = tmpId;
         }
         return ownerId;
     }
```
