### ISSUE TITLE
GitLabController.java has a test endpoint with possible debug log output

### ISSUE THREAD

**Issue by gemgit7** [checkmarx-ltd/cx-flow#557]
### Description
The GitLabController.java file has a /test endpoint with possible debug log output

> The /test endpoint spits out the string "Build Info" every few seconds in the cxflow logs at the INFO level. If the endpoint is valid and debug logging is absolutely needed, this should be a TRACE.

### Expected Behavior
CxFlow logs should use the appropriate logging level for debugging/test entries.

### Actual Behavior
CxFlog logs contain the (what appears to be) debug string "Build Info" from the GitLabController every few seconds.

### Reproduction
Run CxFlow and tail the log file.

### Environment Details

> CxFlow 1.6.13

**Comment by kmcdon83** [comment]
@gemgit7 are they hitting this endpoint for a specific reason?  If you don't go to the endpoint you won't see the log.  We can move this to trace.

If they are monitoring for service health it should be /actuator/health endpoint.
