### ISSUE TITLE
Documentation: add required permissions to GitHub Apps wiki page

### ISSUE THREAD

**Issue by milo-minderbinder** [checkmarx-ltd/cx-flow#561]
### Describe the problem
The wiki page documenting [GitHub App configuration](https://github.com/checkmarx-ltd/cx-flow/wiki/WebHook-Registration#github-app) does not include the permissions required for the GitHub app to work as expected, and there are some quirks with the GitHub App permissions and non-intuitive differences with the GitHub OAuth scopes used for OAuth apps and personal access tokens. In particular, the requirement for the GitHub app to have both read _and_ write permissions for pull requests was a source of personal confusion before reading the GitHub API docs more carefully -- because the app needs to write/update comments on PRs, the [pull request write permission is required](https://docs.github.com/en/free-pro-team@latest/rest/reference/permissions-required-for-github-apps#permission-on-pull-requests), unfortunately.

### Proposed solution
Add the required permissions to the documentation for [GitHub app webhook registration](https://github.com/checkmarx-ltd/cx-flow/wiki/WebHook-Registration#github-app). Specifically, based on my own testing in public GitHub and in GitHub Enterprise Server 2.21, the below repository permissions are required to support all of the same features of the standard webhook + access token model (sorry, would have added this info myself, but Wiki edits are restricted for outside contributors):

**_Repository Permissions_**
1. **Contents**: Read-only
2. **Issues**: Read & write (**NOTE**: not 100% sure about this one -- we don't use, nor have I tested, [GitHub issues as the bug-tracker implementation](https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#github-issues) for CxFlow, but it looks like it creates new issues, and if so, these permissions would be required.
3. **Metadata**: Read-only
4. **Pull requests**: Read & write
5. **Commit statuses**: Read & write

### Additional details

Strictly speaking, only those permissions listed above are required to get everything to work as expected, and no Organization or User permissions are needed. However, it might be advisable to consider adding a suggestion to additionally grant read-only permissions to certain other resources that might be useful in the future. For example, I don't believe CxFlow currently checks if the webhook was manually added to an org or repo when processing GitHub app events, but it might make sense to grant the app read only access to repository and organization webhooks to check if webhook is already configured for the repo/org and if so, only handle events from one or the other so they aren't processed twice by CxFlow for every commit/pr/deletion. Similarly, other events & permissions that would likely be valuable in the future include, e.g. "Repository" and "Organization" events in order to catch/handle cases where repos/orgs are deleted or archived, renamed, etc., and possibly "Member" events to automatically manage team membership in Checkmarx based on the users with push access to the org/repo where the GitHub app is installed.

**Comment by satyamchaurasiapersistent** [comment]
https://github.com/checkmarx-ltd/cx-flow/wiki/WebHook-Registration#github-app we have already updated required permissions to GitHub Apps in this wiki page.
