### ISSUE TITLE
Re-open a closed ticket vs opening a new one

### ISSUE THREAD

**Issue by lgarciaackcent** [checkmarx-ltd/cx-flow#563]
### Describe the problem

I'd like to comment a situation that's happening in a customer installation (in production).

Their SDLC does not allow to re-open tickets once the ticket is solved. If the same problem appears, a NEW ticket must be open. And their Jira workflow explicitly does not allow to re-open a ticket. Once it is closed, there's not transition to any other state.

In our case, if the vuln re-appears, CxFlow will try to re-open the ticket. But there's not any valid transition, so CxFlow fails (Jira returns an error) and exits, leaving the remaining tickets without processing. This forced us to continuously monitoring for such situations, and when it happens to make some manual operations to make CxFlow works again.

BTW, we are using CxFlow to open issues from CxSAST and CxOSA (applies to both).

### Proposed solution

A possible solution to this use case (i'm afraid that must be quite common) would be to have some customizable flag to select between these two options:
* re-open a closed ticket 
* create a new ticket if the ticket is closed

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by AvivCx** [comment]
Hi @lgarciaackcent 
Thanks for raising this issue. 
I understand the request, my concern is that CxFlow has a strict format to create the ticket key, and it is built from the vulnerability details (name, project, file, etc.), so if CxFlow would try to open a new vulnerability it will use the same key and this flow would fail
Changing the key logic would add more complexity and I would prefer to avoid it

Do you know if in this case it would be possible to delete the old ticket and create a new one?
would it solve the issue for this use-case?

**Comment by jbrotsos** [comment]
Rejecting this FR as it would require a complete redesign of the automation of ticket creation.
