### ISSUE TITLE
Reduce Merge Requests comment noise and/or disable commenting on MR

### ISSUE THREAD

**Issue by brenwhyte** [checkmarx-ltd/cx-flow#565]
### Describe the problem

Users are complaining about getting too many comments and emails from GitLab from the Checkmarx SCA scanning.

CxFlow/GitLab "Bot" account comments on the Merge Request on each and every SCA scan.

If you have a moderately busy PR, you can easily end up with a wall of comments from checkmarx scans, and those comments can be huge.  Any developer comments are impossible to find among all of those.

With GitLab's default user setting, this can get very noisy for end users too. By default, any user who has participated in a repo will get an email from GitLab for each of the comments created by the scans. 

https://docs.gitlab.com/ee/user/profile/notifications.html#issue--epics--merge-request-events

One possible solution is covered above ^

> "To minimize the number of notifications that do not require any action, from GitLab 12.9 onwards, eligible approvers are no longer notified for all the activities in their projects. To receive them they have to change their user notification settings to Watch instead."

But that requires user action.

We've had user resort to creating tampermonkey scripts to hide the Checkmarx comments in the browsers. (tampermonkey addon is available for both chrome and firefox through their addon stores.)

### Proposed solution

Is there a way to configure CxFlow? to be less "noisy" in a GitLab environment?

Maybe only adding a single initial `Cx-SAST Summary` comment and edit that on each scan? 
It appears any edits to a comment in GitLab do not trigger a notification/email.

Or an option to disable commenting on MRs completely and rely on issues for tracking?
This ideally would be an optional setting that users can pass in via configuration-as-code `cx.config`

User would track the vulnerabilities in issues manually, as "New issue", "Close issue" and "Reopen issue" don't fire off notifications from the looks of it too.

### Additional details

GitLab.com (13.6 as of today)
Webhook setup
CxFlow 1.6.15
Checkmarx 9.2.0 HF3

**Comment by jbrotsos** [comment]
Hey @brenwhyte

Thanks for this feedback, this is exactly the type of issues we want to hear about - directly from the developer.

Are you filtering the SCA results - https://github.com/checkmarx-ltd/cx-flow/wiki/Integration-with-CxSCA#filters ?  Is that an option to reduce the noise?  This will only filter what is displayed in the MR and not remove it from the end report.

James

**Comment by kmcdon83** [comment]
Just to confirm @brenwhyte you would like us to implement the logic such that we create 1 comment, and continually update it.  Including the event a MR is updated and additional scans take place?

This logic was implemented for GitHub.  We can look to see how we can port it to GitLab logic as well.

**Comment by brenwhyte** [comment]
Hi Jame/Ken o/

Apologies for the late reply.

> Are you filtering the SCA results
Yes/no I suppose. We do intend to filter on the High's only as a default, where users can opt-in to the other levels within cx.config. But I'd imagine we'd still get the same _number_ of checkmarx comments to the MR for each scan that gets run.
You'll get the usual `Scan submitted to Checkmarx` comment and a second scan summary comment irrespective of the configured filtering. (That's my assumption)

>you would like us to implement the logic such that we create 1 comment, and continually update it. Including the event a MR is updated and additional scans take place?
Yes that sounds like a workable solution for sure. I think the devs would welcome that here.
Also, possible to disable commenting too (in cx.config?), I imagine some folks would like to see where they can opt-out of the Checkmarx commenting on a per-project basis.

Thanks a mill
Bren

**Comment by pconcepcioncimpress** [comment]
Hi, this is Pablo, working with @brenwhyte on this. 

> Are you filtering the SCA results

@jbrotsos , one important remark, the current issue is with CxSAST results, we are on the process of integrating also with CxSCA, but if CxSCA results work the same way it will also be desirable to be able to incorporate them all on one comment to prevent sending a lot of mail notifications and be able to disable the commenting form the `cx.confg` file for the folks that want to opt-out of the commenting.

Thanks!
   Pablo

**Comment by AvivCx** [comment]
Hi @pconcepcioncimpress and @brenwhyte 
In order to eliminate the comments on specific repo, you can use config-as-code to set up the bug-tracker to 'None' (this is available from 1.6.16)

We are aware ofthe need to 'override existing comment' intsead of creating more and more comments on the same PR. as Ken mentioned we implemented it for Github and Azure PR
We plan to implement it to GitLab as well, and put it in cxflow backlog

we will update this ticket once it's done for GitLab

Thanks,
Aviv

**Comment by brenwhyte** [comment]
Hi Aviv,

I had a chance to test the bug-tracker set to 'None' today. 
The Scan summary in Merge Requests and the posting of Issues to GitLab's issue tracker have been disabled as expected but I wanted to mention the `Scan submitted to Checkmarx` comment is still there. Not sure if that was also intended to be disabled too.

Thanks for this new feature. 

Bren

**Comment by AvivCx** [comment]
ok. thanks for the update. we will handle this as well

**Comment by AvivCx** [comment]
Fixed by PR #626 
Available in cxflow-1.6.18

**Comment by brenwhyte** [comment]
Hi Aviv,

I was wondering would it be possible to have the bug-tracker stay as `GitLab` but disable the commenting on Merge Requests ??

Thanks
Bren

**Comment by AvivCx** [comment]
Hi @brenwhyte. I don't think there is such option
@AsafCX  can you confirm?

**Comment by AsafCX** [comment]
Hi @brenwhyte ,
Unfortunately, there isn't an option to disable Gitlab system comments, Gitlab is making sure we won't be able to disable it cause they think all these system actions are important and must be registered.
In our new feature, CxFlow instead of duplicating Scan results will update previous scan results comment this will reduce comment volume.
