### ISSUE TITLE
ChatOps notifications and reporting support (Slack, Teams, Mattermost, Skype, ...)

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#572]
### Describe the problem

CxFlow is missing ChatOps notifications and reporting support (Slack, Teams, Discord, Mattermost, Skype, etc...)
This is must have in a fast DevSecOps world where constant feedback is required.

### Proposed solution

**Implement ChatOps through a yaml block with the ability to send messages to multiple types of Chat apps:**
  * Multi-channel  - ability to add config for multiple channels for multiple chat apps types, not just for one of each type
    * One should be able to configure multiple accounts and multiple channels for account for the same app type
  * Notifications - Send summarized info about security scans like:
    * Scan passed/failed according to thresholds
    * Scan total findings by vulnerability
    * Warn if build breaks or not
    * Use icons like semaphores and OK/NOK for visual impact
    * ...
  * Reporting - Select if you want to send summarized, detailed reporting, or none to keep it simple
    * Each channel should be configured with notifications or reporting or both
  * Bots - Create a bot tutorial for each app with quick examples/templates of ready-to-deploy on each app

**Comment by jbrotsos** [comment]
Thanks for the details, this FR is already being prioritized but you brought up some great edges.

**Comment by cx-scord** [comment]
@jbrotsos Any news on this FR? Slack integration would be a great first implementation 😃

**Comment by jbrotsos** [comment]
Hey @cx-scord ,

This will be supported with AST and not with CxFlow.  Rejecting any new feedback channels.
