### ISSUE TITLE
SCA do not follow-up when creating an issue

### ISSUE THREAD

**Issue by svevia** [checkmarx-ltd/cx-flow#574]
### Description

When CxFlow create an issue (on GitLab) or a ticket (in Jira) it did not follow it up on next scan, for exemple if the vulnerability disepear and the issue is till Open CxFlow will not close it

### Expected Behavior

CxFlow should close the issue if vulnerability does not exist anymore

### Actual Behavior

CxFlow do not change the Issue state

### Reproduction

Configuration : https://gitlab.com/svevia/cxflow-front-api/-/blob/master/.gitlab-ci.yml
On this repo, the issues are solved but are still open.

### Environment Details

Tested for Gitlab and Jira with SCA.

**Comment by AvivCx** [comment]
Thanks @svevia. 
from your description it looks like a real issue. we will look into it

**Comment by fredericmalo** [comment]
Hello Aviv, 

I have the opposite issue on my repo. Steps to reproduce: 

- Moving SAST and SCA ticket from "Open" to "Closed" status
- running a new SAST+SCA scan
- SAST ticket is reopened
- SCA ticket is **_NOT_** reopened

https://gitlab.com/fredericmalo/appsec/cxflow-in-gitlab-pipeline/-/boards

Thanks !

**Comment by svevia** [comment]
Hi !
We need to reopen this issue, the correction duplicate tickets rather than follow them, have a look on this repo : https://gitlab.com/svevia/cxflow-front-api/-/boards/2244867
I ran the pipleine twice and I get 2 issues for same vulnerability (#3 and #4), also the 2 others tickets (#1 et #2) are now solved but CxFlow do not closed the tickets, the one that is close is a manuel action...

**Comment by AvivCx** [comment]
Hi @svevia 
we had some misalignments with the fixes on the latest cxflow version. it is fixed now
can you please verify again  on latest version (1.6.16)
If the issue persist we will look into it
Thanks.

**Comment by svevia** [comment]
Hello I was running on the last docker version, in logs I can see that it is the verison 1.6.16

![image](https://user-images.githubusercontent.com/11472269/103527631-f353c300-4e82-11eb-8a21-20c243e7ca2f.png)

Now, after every start it create a new ticket

See on this screenshot for issu 3, 4 and 5  : 
![image](https://user-images.githubusercontent.com/11472269/103527741-19796300-4e83-11eb-9b45-af3b7c97015b.png)

**Comment by svevia** [comment]
Ok no, after a restart if finally works but only on the last ticket starting with "CX", you change the Issue title and so can't follow the previous, noted !

Thank you
