### ISSUE TITLE
SCA tenant wasn't provided on Gitlab Merge Request

### ISSUE THREAD

**Issue by fredericmalo** [checkmarx-ltd/cx-flow#575]
Hello

CxFlow returns a "SCA tenant wasn't provided" error on Merge Request, but works on protected branches

Steps to reproduce: please fork this repo: https://gitlab.com/svevia/cxflow-front-api

- Have a look at the logs of a successful scan on protected branch: 
https://gitlab.com/svevia/cxflow-front-api/-/jobs/915553580

- Logs of the error on Merge Request : 
https://gitlab.com/svevia/cxflow-front-api/-/jobs/915549625#L65

- But the SCA_TENANT is correctly set on application.yml that is used for both types of scan: 
https://gitlab.com/svevia/cxflow-front-api/-/blob/master/.gitlab-ci.yml#L31

What is missing here ? 

CC: @svevia

Thanks ! frédéric

**Comment by AvivCx** [comment]
@fredericmalo, it doesn't look like a real issue, but environment conditions that need to be investigated
I don't want to handle such discussions as github issue. let's continue the discussion in the team channel as you started it already with James
I'll close this issue for now. Thanks.
