### ISSUE TITLE
Batch Process with Jira: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Apipia** [checkmarx-ltd/cx-flow#603]
### Description
Using: `java -jar cx-flow-1.6.16-java11.jar --batch`
This should iterate over all projects and grab the most recent scan, create/update/delete tickets in our Jira project. 
We are only using one Jira project. It seems that the code is attempting to modify a map on multiple threads to add the custom_fields for jira to it. Since they are all using the same project, I believe the code is trying to modify some data on multiple threads with no protection.

Currently I have written a script to grab all projects and their fullTeam name using the API, then call this JAR file with `--project` and run it against each project one after the other. This works, but is a silly workaround.

### Expected Behavior
No ConcurrentModificationException error and all projects are updated.

### Actual Behavior
Fails very quickly during the first project or two.

### Reproduction
From what I can tell, all projects in Checkmarx having results put in the same single Jira Project should cause this problem. 

[cx-flow.log](https://github.com/checkmarx-ltd/cx-flow/files/5797834/cx-flow.log)
[application-sharable.txt](https://github.com/checkmarx-ltd/cx-flow/files/5797848/application-sharable.txt)

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

cx-flow-1.6.16-java11.jar

Java versions tested:
ON MAC:
java --version
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

ON UBUNTU:
java --version
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

**Comment by Apipia** [comment]
Please see the log for the exceptions/stack traces.

**Comment by AsafCX** [comment]
Hi @Apipia,
I wasn't able to reproduce the mentioned problem (CxFlow 1.6.17), However, We did recognize a potential problem with the existing code (thanks to your feedback).
Please try to reproduce it using cx-flow-1.6.18_batch_mode_fix.java temporary version located at:
[https://github.com/checkmarx-ltd/cx-flow/releases/tag/1.6.17](https://github.com/checkmarx-ltd/cx-flow/releases/tag/1.6.17)
In the above version CxFlow, using ConcurrentHashMap manage to prevent ConcurrentModificationException.
Please test your case and update if you are facing additional problems in batch mode
