### ISSUE TITLE
Application spaces replaced with underscores (Jira automation)

### ISSUE THREAD

**Issue by Apipia** [checkmarx-ltd/cx-flow#609]
### Description
I'm using CxFlow to automate Jira ticket creations. We have a custom field single-select with values like "product A".
I'm trying to map "Application" to a custom field "Module" that's a single-select.

When I run the command:
java -jar cx-flow-1.6.16-java11.jar --spring.config.location=application-stp.yml --project --cx-project="CX-Project A" --cx-team="CxServer/Web Services/Project A" --app="Project A"

The log file shows:
```
com.checkmarx.flow.service.JiraService   : Getting custom field Module
com.checkmarx.flow.service.JiraService   : application: Project_A
com.checkmarx.flow.service.JiraService   : single select field
```

Notice that it replaced the space with an underscore.
It then _fails_ to find an Option ID for it (go figure, since it replaced my space!) and I get:

```
com.atlassian.jira.rest.client.api.RestClientException: [ErrorCollection{status=400, errors={customfield_12748=Option id 'null' is not valid}, errorMessages=[]}]
```

Can we please remove whatever code is replacing those spaces with underscores? If I wanted an underscore, I would have put one in there, no?

### Expected Behavior
Application name stays exactly how I've put it, spaces included.

### Actual Behavior
Application name has spaces replaced with underscores.

### Reproduction
This seems pretty straight forward. 
1. Put in an application with a space
2. Add a Jira field mapping of type Single Select that has the same name (space included)
3. Run automation and watch it fail miserable to find an option, since it adds an underscore.

**Comment by AvivCx** [comment]
Hey @Apipia 
Did you try to use values without spaces? for example 'Project-A' or 'Project_A'
I wonder if this would resolve this issue, and if yes what would be the implications overall implications

Thanks, Aviv

**Comment by Apipia** [comment]
Hey @AvivCx ,

I'm not entirely sure what you mean. Using values without spaces works fine, but I _need_ this value to have a space in it. As I stated in the issue, it will be used to map to an option in a single-select field in Jira. The single-select field has "Project A" in it. I do not have the power to change the name of this option in Jira. 

To explain again:
Checkmarx App Field (command-line supplied) -> Jira Option (single-select) Field.
I need the app to have a space in it because the option for the single-select field has a space in it.

Am I making sense?

Thanks,
Anthony

**Comment by Apipia** [comment]
Supply the App value here:
![Screen Shot 2021-01-19 at 8 42 32 AM](https://user-images.githubusercontent.com/17787069/105057396-6b4cec00-5a32-11eb-9a43-1de25c2dab53.png)

Map it to Jira field here:
![Screen Shot 2021-01-19 at 8 41 30 AM](https://user-images.githubusercontent.com/17787069/105057412-7011a000-5a32-11eb-89e1-11a2ff221477.png)

Jira field (single-select with the value we need as an option) here:
![Screen Shot 2021-01-19 at 8 40 11 AM](https://user-images.githubusercontent.com/17787069/105057428-730c9080-5a32-11eb-9ed2-d5493f288932.png)

**Comment by Apipia** [comment]
I'm not sure but this might be the line:
https://github.com/checkmarx-ltd/cx-flow/blob/b0d6425c89b1b157075df33929ad3719af508293/src/main/java/com/checkmarx/flow/service/JiraService.java#L1379

**Comment by AvivCx** [comment]
Hi @Apipia. thanks for pointing it out.
We will look into it more closely. the challenge here is to keep backward computability and not break the integration with Jira for other existing customers.
If this is urgent for you we can find a quick turn around to resolve it for you. anyway I added it to the backlog
Thanks

**Comment by AvivCx** [comment]
Hן @Apipia 
I compiled a quick version of cxflow with the fix for this issue.
you can take it from here: [cx-flow-1.6.18_jira_underscores.jar](https://github.com/checkmarx-ltd/cx-flow/releases/tag/1.6.18)
if it works for you I'll add it to the main stream of the release. let us know

Thanks
