### ISSUE TITLE
Dynamically Assign Jira Tickets To Users

### ISSUE THREAD

**Issue by jgresh22** [checkmarx-ltd/cx-flow#610]
### Describe the problem

Background: CxFlow is integrated with Bitbucket cloud using a webhook. The integration is configured to run a SAST scan when there is a pull request. We are using config-as-code so we can override repository/project specific settings. 

Problem: When a developer submits a pull request via bitbucket cloud, using config-as-code, CxFlow should assign any new Jira tickets to the developer who submitted the pull request.

### Proposed solution

In the POST body of the Bitbucket Cloud webhook request, there is a json property "Actor" which contains a "display_name". Use this display name value to populate the Jira 'Assignee' field.

**Comment by jbrotsos** [comment]
Hey @jgresh22,

JIRA tickets are only created on Pushes and not Pull Requests.

James
