### ISSUE TITLE
Create Jira ticket & PR Feedback

### ISSUE THREAD

**Issue by jgresh22** [checkmarx-ltd/cx-flow#611]
### Describe the problem

Background: CxFlow is integrated with Bitbucket Cloud using a webhook. The integration is configured to run a SAST scan when there is a pull request. We are using config-as-code so we can override repository/project specific settings. 

Problem: When we have CxFlow configured to create a Jira ticket we no longer get scan feedback in Bitbucket Cloud Pull Requests. We would like to be able to submit a Jira ticket and get feedback in the pull request as it allows us to better manage and visualize defects at a PR level.

### Proposed solution

Support ability to get scan result feedback in a Pull Request while also creating a Jira ticket.

**Comment by AvivCx** [comment]
Hi @jgresh22 
CxFlow designed to work in the following cases:
 1. On Pull request event, CxFlow initiate a scan and publishing the result as a pull request comment in the relevant pull-request. there no Jira\bug-tracker tickets opened in this flow
 
 2.  On Push event, CxFlow initiate scan and publishing the results as tickets in the configured bug-tracker. in this case there is no specific pull request, and there is no pull request data in the created ticket
 
Let me know if you have more questions
Thanks, Aviv

**Comment by jgresh22** [comment]
Hi Aviv, 

Thanks for the feedback. Understood what the current use cases are for CxFlow. I'm using it a little differently as my organization would like to submit Jira tickets for findings earlier on - during a pull request. I have CxFlow configured to run a scan on a pull request and then open up Jira tickets for any High/Medium risk findings. I have this setup working successfully. My enhancement request is to allow CxFlow to create both a Jira ticket and publish results to the pull request comments. This gives me ability to assign tickets at pull request and also give developers feedback directly in the pull request.

**Comment by jbrotsos** [comment]
Hey @jgresh22,

We will only support creating tickets during the push event and not the PR event.

Thanks,
James
