### ISSUE TITLE
Associate Pull Request to Jira Tickets

### ISSUE THREAD

**Issue by jgresh22** [checkmarx-ltd/cx-flow#612]
### Describe the problem

Background: CxFlow is integrated with Bitbucket cloud using a webhook. The integration is configured to run a SAST scan when there is a pull request. We are using config-as-code so we can override repository/project specific settings.

Problem: When CxFlow creates Jira tickets for new bugs, there is no easy way to correlate the ticket to a bitbucket pull request. CxFlow should create a Jira label or populate a custom Jira field containing the pull request link.

### Proposed solution

In the POST body of the Bitbucket Cloud webhook request, there is a json element "pullrequest" which contains an array named "links". The value of "html" in that array contains a link to the pull request. Use the value of 'html' to populate a Jira label or custom Jira field.

**Comment by AvivCx** [comment]
Hi @jgresh22 
as I mentioned in issue #611, CxFlow design to send a pull request comment on pull-request event, or to open tickets in push events
There is no flow that CxFlow both update pull request and open tickets
Let me know if you need more details

Thanks, Aviv

**Comment by jgresh22** [comment]
Hi Aviv, 

In my use case, we perform the following steps:
1. CxFlow runs a scan when there is a pull request. 
2. CxFlow creates a Jira ticket for new High/Medium risk findings. 

I have the above working successfully. So I've been able to have CxFlow submit jira tickets on pull-request. It sounds like this use case is not currently supported despite it being technically possible to configure CxFlow the way I describe above?

**Comment by jbrotsos** [comment]
Hey @jgresh22,

We will only support creating tickets during the push event and not the PR event.

Thanks,
James
