### ISSUE TITLE
Checkmarx Not Creating Gitlab MR Discussions 

### ISSUE THREAD

**Issue by Huseyinnurbaki** [checkmarx-ltd/cx-flow#613]
Hi,

Working on Gitlab & Checkmarx integration. Regular scanning is fine. I would like use features such as automatically issue opening, creating merge request discussions . Git url is set correctly.  Regular scanning works .

### Expected Behavior
I am opening a merge request to the target branch which is the main branch which checkmarx always scans. I expect cx-flow successfully  create issues/mr discussions. I have webhook configured correctly, webhook token matches the one in the config. 

### Actual Behavior
Scanning part succeeds. No mr discussion or issue is created.

### Reproduction

CX_FLOW_CONFIG

`
cx-flow:
  bug-tracker: GitLab
  bug-tracker-impl:
    - CxXml
    - Json
    - GitLab
  break-build: true
  branches:
    - master
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  wiki-url: https://checkmarx.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://cxa.codebashing.com/courses/

checkmarx:
  username: ${CHECKMARX_USERNAME}
  password: ${CHECKMARX_PASSWORD}
  client-id: resource_owner_client
  client-secret: {CLIENT_SECRET}
  team: ${CHECKMARX_TEAM}
  url: ${CHECKMARX_SERVER}/cxrestapi
  base-url:  ${CHECKMARX_SERVER}
  portal-url: ${CHECKMARX_SERVER}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${CHECKMARX_SERVER}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${CHECKMARX_SERVER}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${CHECKMARX_SERVER}/SDK/CxSDKWebService.asmx?wsdl
  scan-resubmit: true
  portal-package: checkmarx.wsdl.portal
  preserve-xml: true
  multi-tenant: true
  incremental: true
  scan-preset: Checkmarx Default
  configuration: Default Configuration

gitlab:
  webhook-token: ${W_TOKEN}
  token: ${GITLAB_TOKEN}
  api-url: ${GITLAB_URL}/api/v4/
  false-positive-label: false-positive
  url: ${GITLAB_URL}
  block-merge: true
`

### Environment Details

Chekmarx version: 8.9.0.210
Hotfix version: 14
cx-flow-1.6.16
Gitlab 13.6.1-ee

I can provide more information if required.

**Comment by AvivCx** [comment]
Hi @Huseyinnurbaki. thanks for raising this issue
A similar issue was resolved in cxflow-1.6.17
can you try run it with 1.6.17 and see if this is resolved?

Thanks

**Comment by Huseyinnurbaki** [comment]
Hi @AvivCx ,

Thank you for your suggestion but that didn't work either.

Here are some of the logs. Can't decide what's wrong.

![Screen Shot 2021-01-19 at 03 33 03](https://user-images.githubusercontent.com/22790534/104973824-0c25b200-5a07-11eb-8f66-d7cbc5396ea3.png)

According to the logs, complete method called after getIssues.

I read the code written in the [GitLabIssueTracker.java](https://github.com/checkmarx-ltd/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/custom/GitLabIssueTracker.java)


Any suggestions on that ?

Regards

**Comment by jbrotsos** [comment]
Hey @AvivCx ,

I'm seeing the same issue.  We are using the CxFlow Docker and it pulls the latest version of CxFlow - which is currently 1.6.16.  

@Huseyinnurbaki 1.6.17 will be released shortly.  We will close this issue once we release it.

James

**Comment by AvivCx** [comment]
Resolved in cxflow-1.6.17
