### ISSUE TITLE
restrict what fields can be modified via cx.config

### ISSUE THREAD

**Issue by N3D4U2C** [checkmarx-ltd/cx-flow#627]
### Describe the problem

From customer: Developers will be able to change or add fields to the cx.config file.  Doing so, could allow them to circumvent what's on the applicaion.yml file.

### Proposed solution

Can we add the feature we want to CxFlow (add code to allow us to set yml file not to allow all, none, or certain fields from being overridden by the json file (cx.cofig))

### Additional details

For example: the application.yml file says that all highs and mediums will generate a ticket.  A developer could change that behavior via the cx.config which they'll have access to.

**Comment by jbrotsos** [comment]
After careful consideration and researching how other config as code solutions work, we will not be implementing this enhancement request.  I haven't found any other config as code solutions that work in the way of restricting certain fields.  It would also be very specific to your security needs vs a user who might want other fields "protected".  We appreciate the idea but logistically it doesn't make sense for the product.
