### ISSUE TITLE
CxFlow creates duplicate tickets/issues when ran in batch mode.

### ISSUE THREAD

**Issue by ghost** [checkmarx-ltd/cx-flow#628]
### Description

> The original problem is that cxflow is processing the scan results twice if we run it in a batch mode (using --project parameter).
This is evident from the log as well as if there is any bug tracker configured, there are duplicate tickets getting created.

### Expected Behavior

CxFlow should process the latest scan results only once.

### Actual Behavior

Scan Results getting processed twice.

### Reproduction

1) Run cxflow in cmd mode using the --project paramter.

For example : java -jar cxflow.jar --project --cx-team="\Demo\CxFlow\" --cx-project="AnySASTProjectName" --bug-tracker=AnyBugTracker(Sarif or Jira)
--app="AnyAppName"

2) Check the log output and repeated result processing or issue creating can be observed.

**More Details** : 

1) The issue seems to be occurring as a result of the method 'processResults' (From ResultsService) gets called on two different occasions.
2) Refer to the method 'publishLatestScanResults' from CxFlowRunner.java, add the breakpoints, and observe the behavior.

### Environment Details

> CxFlow version : 1.6.17

**Comment by itsKedar** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
