### ISSUE TITLE
Include commit hash in request object

### ISSUE THREAD

**Issue by agehring** [checkmarx-ltd/cx-flow#647]
### Describe the problem

The commit hash is not included in the request object, which can be used to identify the commit.

### Proposed solution

Include the commit hash in the request object, so it can be used in the comment or other groovy uses

**Comment by jbrotsos** [comment]
Hey @agehring, can you talk a little bit more of the use case?  And are you talking push events or pull requests?  What is the exact field you want to add from this request object?

**Comment by milo-minderbinder** [comment]
@jbrotsos all events should include the git hash in the ScanRequest object. The exact field from the Event DTO is going to depend on the event type (push, pull, delete), but regardless, there should be a way to reference the exact commit hash that is being dealt with in the ScanRequest. Our use case is so we can add the commit hash of the code being scanned to the Checkmarx scan comment.

**Comment by cx-scord** [comment]
@jbrotsos I believe this can be closed.
