### ISSUE TITLE
Bitbucket Server third party webhooks plugin "Post Webhooks" support

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#651]
### Describe the problem

Customer requests the ability to support [Post Webhooks](https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket?hosting=server&tab=overview).

Mainly this is due to the ability to define webhooks on the global, team, and project level.  They want to set a single global webhook (BB Server doesn't support this) and use Config As Code to configure each repo.

### Proposed solution

The Post Webhook even names clash with both BB Cloud and BB Server implementations.  The handler will perform the same workflow as the current BB Server capability.  The `/postwebhook` path will allow the events to be handled without clashing with existing BB handlers.

**Comment by nleach999** [comment]
I have a complete implementation, PR will come this week.

**Comment by AvivCx** [comment]
Thanks @nleach999
