### ISSUE TITLE
Incorrect default return value in GitLabIssueTracker.getProjectId()

### ISSUE THREAD

**Issue by gemgit7** [checkmarx-ltd/cx-flow#653]
### Description

The GitLabIssueTracker's getProjectId() method returns the default value '0' if the repo project ID cannot be found.

It should be GitLabIssueTracker.UNKNOWN_INT.

```
    private Integer getProjectId(ScanRequest request) {
        try {
            int projectId = 0; 
            ... 
            return projectId; // This will be returned if the GitLab project cannot be found.
        }
        ...
```
### Expected Behavior

GitLabIssueTracker.getProjectId() should return GitLabIssueTracker.UNKNOWN_INT if the repo project ID cannot be found.

```
    private Integer getProjectId(ScanRequest request) {
        try {
            int projectId = UNKNOWN_INT; 
            ...
            return projectId;
        }           
        ...
```

### Actual Behavior

GitLabIssueTracker.getProjectId() returns 0 if the repo project ID cannot be found.

### Reproduction

Provide incorrect repo, namespace, etc and notice that the getIssues call uses projectID 0 instead of throwing a  MachinaException in the GitLabIssueTracker.init() method.

```
            Integer projectId = getProjectId(request);
            if (projectId.equals(UNKNOWN_INT)) {
                log.error("Could not obtain GitLab Project Id for {}/{}/{}", request.getNamespace(), request.getRepoName(), request.getBranch());
                throw new MachinaException("Could not obtain GitLab Project Id");
            }

           // If projectId is NOT UNKNOWN_INT, 
           // the repoProjectId will be incorrectly set to 0 (that's the bug),
           request.setRepoProjectId(projectId);

```
### Environment Details

GitLab issue tracking.

**Comment by jbrotsos** [comment]
Hey @gemgit7, when does this happen?  When GitLab issues are being created?  Can you attach your configs?

**Comment by cx-scord** [comment]
Might/can be related to #780 
Also, if the project isn't found, at least there should also be an error message sent to the log saying the project wasn't found, which is not currently happening, returning 0 as the id might not be correct as well.

**Comment by satyamchaurasiapersistent** [comment]
if this issue still occurs please raise salesforce ticket.
