### ISSUE TITLE
CxFlow Filter and Group by Result Severity to raise Jira Issues doesn't work / not supported

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#654]
### Description

Would like to be able to raise Jira issues (aggregate and filter) based on the updated Result Severity (similar to Result State)

### Expected Behavior
When Issues are marked as High/Medium (in the updated Result Severity and not by the checkmarx OOTB CWE/Category) we would like to raise Jira's just for them
### Actual Behavior
Even issues which are marked as low are raising Jira's
![image](https://user-images.githubusercontent.com/1933763/108792412-4de0e400-75d5-11eb-9817-951207d38cf4.png)

Would like to be able to filter and aggregate (with focus on filter unless we can have both) as we do for Result State:

![image](https://user-images.githubusercontent.com/1933763/108792509-8b457180-75d5-11eb-907b-b5d8a160d1b9.png)

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by jbrotsos** [comment]
To reproduce:

If there are two High reflected XSS results and one is manually changed to Low. If CxFlow runs, it will still send both results because to CxFlow they are still both high.

What is likely going on:

We are looking at the Query Severity and not the Results Severity.

**Comment by jbrotsos** [comment]
Fixed here: https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/99
