### ISSUE TITLE
Gitlab Merge Request ID is null (fails to update comment)

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#655]
### Description

The noteable_id is invalid and when debugging, I can see the merge request ID is "null", I am confident it is due to the following code:

[https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/service/GitLabService.java#L355](https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/service/GitLabService.java#L355)

The mergeId in scanRequest is set as a variable and is never put into map of additional metadata , but in the gitlab service, it fetches it using: `scanRequest.getAdditionalMetadata(MERGE_ID)`, which result in null instead of the actual mergeId.

### Expected Behavior

Merge ID is not null (noteable_id is valid)

### Actual Behavior
I blanked out the projectId and noteId, but essentially it tries to update this:

`https://gitlab.ca/api/v4/projects/----/merge_requests/null/notes/------`

```
021-02-23 16:44:02.517 ERROR 37 --- [           main] com.checkmarx.flow.service.RepoService   : Error while adding or updating GITLAB repo pull request comment
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"error":"noteable_id is invalid"}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:581)
	at com.checkmarx.flow.service.GitLabService.updateComment(GitLabService.java:127)
	at com.checkmarx.flow.service.RepoService.sendMergeComment(RepoService.java:41)
	at com.checkmarx.flow.service.GitLabService.processMerge(GitLabService.java:115)
	at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:148)
	at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.checkmarx.flow.service.ResultsService$$EnhancerBySpringCGLIB$$1c02db5e.processResults(<generated>)
	at com.checkmarx.flow.CxFlowRunner.processResults(CxFlowRunner.java:526)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:504)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:406)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:83)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

### Reproduction

Re-scan an already existing merge request (either by committing again or rerunning it)

### Environment Details

Checkmarkx 8.9

**Comment by marcandre-larochelle-bell** [comment]
Additional Information, this is performed with the CxFlowRunner, not the git clone, [https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/controller/GitLabController.java#L161](https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/controller/GitLabController.java#L161) you can see that in the GitLabController it is added as additional metadata, but not in [https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/CxFlowRunner.java](https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/CxFlowRunner.java
)

**Comment by jbrotsos** [comment]
Hey @marcandre-larochelle-bell,

Can you explain your workflow?

**Comment by marcandre-larochelle-bell** [comment]
Basically followed the Gitlab Integration tutorial: [https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1929937052/GitLab+Integration]( https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1929937052/GitLab+Integration), minus the SCA (only SAST)

Issue happens if you re-run the CI job (or commit) on an existing Merge Request (at creation of the Merge Request there is no issues). Or whenever it tries to update an existing comment.

I analyzed the code from the GitHub and what I found is: the scan request doesn't have the merge request ID in the additional metadata, but rather in a private field, so when the GitLabService does [https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/service/GitLabService.java#L358](https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/service/GitLabService.java#L358) it receives null instead of the value stored in the private field called `mergeNoteUri`. 

If you change the CxFlowRunner to work like the GitLabController: 

[https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/controller/GitLabController.java#L162](https://github.com/checkmarx-ltd/cx-flow/blob/79eac0908197700ebc964e33ae2ee26256caada8/src/main/java/com/checkmarx/flow/controller/GitLabController.java#L162)

It should fix the issue, but I would recommend a different approach, a getter for the merge id to be used instead of the additional metadata map (and uniformizing the GitLabController to pass the merge id to the ScanRequest too, as it does not currently in the code).

Checkmarx version: 8.9 and self-hosted gitlab (without gitlab security dashboard)
Docker image: docker.io/checkmarx/cx-flow:79eac09 (the one with the unparseable date fix)

**Comment by jbrotsos** [comment]
Are you adding a config that is outside those directions?  I don't see that error happening and I'm wondering if we are missing an edge case.

**Comment by marcandre-larochelle-bell** [comment]
I enabled debugging for the .jar, but that is pretty much it, we also have a few stages before the scan, but it should not impact it

**Comment by marcandre-larochelle-bell** [comment]
```
logging:
  file:
    name: cx-flow.log

cx-flow:
  bug-tracker:  ${BUG_TRACKER}
  bug-tracker-impl:
    - GitLab
    - GitLabDashboard
  filter-severity:
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  break-build: true
  enabled-vulnerability-scanners:
    - sast

checkmarx:
  version: 8.9
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: ${CHECKMARX_SERVER}
  url: ${CHECKMARX_SERVER}/cxrestapi
  portal-url: ${CHECKMARX_SERVER}/cxwebinterface/Portal/CxWebService.asmx
  multi-tenant: true
  incremental: true
  scan-preset: Checkmarx Default
  configuration: Default Configuration
  scan-timeout: 120
  
gitlab:
  api-url: https://---------------.ca/api/v4/
  false-positive-label: false-positive
  url: https://---------------
  file-path: ./gl-sast-report.json
```

and

```.checkmarx_sast:
  stage: sast-compliance
  tags:
    - sast
  image:
    name: docker.io/checkmarx/cx-flow:79eac09
    entrypoint: ['']
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - cat ${LOCAL_CA_CERT} > localcert.cert
    - keytool -importcert -trustcacerts -alias localca -file localcert.cert -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt
    - |
      if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then 
        java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
          --scan \
          --cx-team="${CHECKMARX_TEAM}" \
          --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
          --app="${CI_PROJECT_NAME}" \
          --project-id=${CI_PROJECT_ID} \
          --merge-id=${CI_MERGE_REQUEST_IID} \
          --bug-tracker=GITLABMERGE \
          --cx-flow.break-build=false \
          --logging.level.com.checkmarx.flow.service=DEBUG \
          --f=.
      else
        java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
          --scan \
          --cx-team="${CHECKMARX_TEAM}" \
          --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
          --app="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
          --branch="${CI_COMMIT_REF_NAME}" \
          --repo-name="${CI_PROJECT_NAME}" \
          --namespace="${CI_PROJECT_NAMESPACE##*/}" \
          --cx-flow.break-build=false \
          --logging.level.com.checkmarx.flow.service=DEBUG \
          --f=.
      fi
  artifacts:
    when: on_success
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
```

**Comment by marcandre-larochelle-bell** [comment]
I tried using the new "v2" Gitlab template (and tutorial), but there are multiple issues:

- Wrong docker image name, should be `cx-flow` not `cxflow`, but anyway had to use `cx-flow:79eac09`, due to the date issue
- Can't specify which checkmarx version (we are using 8.9 and the CX_TEAM separators are different, thus prevents authenticating against the server), had to modify slightly the template to override the config (using the old method with 
`spring.config.location=./application.yml`) which enables to override the checkmarx version (fixing that specific issue). An argument should probably be added to be able to override it.

Even with the new template and modification to override the checkmarx version, the issue persists. (Also enabled the debugging `--logging.level.com.checkmarx.flow.service=DEBUG` through out that).

**Comment by jbrotsos** [comment]
@marcandre-larochelle-bell The issue of this specific bug (GitLab Merge Request ID is null) was not fixed.  We will look to fix it soon.

I did just update the template to have the version and renamed the Container, thanks for pointing this out.

**Comment by marcandre-larochelle-bell** [comment]
Thanks for the update!

**Comment by marcandre-larochelle-bell** [comment]
I saw the PR for the template, it also needs (or the tutorial needs it) the CHECKMARX_CLIENT_SECRET and I also had to keep the following lines too in the "old" way of doing it with CX_FLOW_CONFIG:

```
  url: ${CHECKMARX_SERVER}/cxrestapi
  portal-url: ${CHECKMARX_SERVER}/cxwebinterface/Portal/CxWebService.asmx
```

I was also wondering, are there variables or what is the best way to define a custom self-hosted gitlab instance, previously it was also using the CX_FLOW_CONFIG, but is there a application arguments (for the .jar) to do it? Thanks

**Comment by jbrotsos** [comment]
I updated https://checkmarx.com/gitlab, let me know if that helps.

**Comment by marcandre-larochelle-bell** [comment]
I mean, yes and no, the tutorial itself doesn't talk about CHECKMARX_CLIENT_SECRET environment variable, so unless the person following the tutorial and is aware he/she needs it, they'll have to figure out how to set it up properly and where to find it (either with the environment variable, which is somewhat hidden in the doc: [here](https://github.com/checkmarx-ltd/cx-flow/blob/ed5a7fde6d5958874fb89c4a9311c1cb0ed89d3f/docs/Labs.md) and [here](https://github.com/checkmarx-ltd/cx-flow/blob/42582894c5356ee18929d8e97c88ddeaf6b549b4/docs/Execution.md) or using the overriding settings from [here](https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration). 

Other thing that wasn't really clear was that if I use the override on command line as described [here](https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration), and for example put `--checkmarx.url="${CHECKMARX_BASE_URL}/cxrestapi"` in order for it to be read, I still need to specify: `--spring.config.location=./application.yml` (even if I didn't output anything into application.yml). This part is what I mean about if there was application arguments to override the gitlab configuration (just found it in the doc).

**Comment by bohregard** [comment]
So I did some digging in this because I had the same issue and it looks like when the comment needs to be updated it calls a routine in the `GitLabService.java` called `getCommentUrl`. The problem from what I see is that it calls `scanRequest.getAdditionalMetadata(MERGE_ID)` but that is not being set anywhere.

The `addComment` routine is working because it uses `request.getMergeNoteUri()` which builds in the merge id as part of the request.

What I did to temporarily fix the issue was put `request.putAdditionalMetadata(GitLabService.MERGE_ID, mergeId);` after the `ScanRequest.Builder` in the `CxFlowRunner.java` file. A better solution would probably be to just replace the `getCommentUrl` method with the `mergeNoteUri` and then append the note id to the end of that uri since it's valid.

**Comment by marcandre-larochelle-bell** [comment]
Yep, still waiting for a fix for this, only "blocking" issue for us to use CxFlow right now. Wanted to fork it and create a PR, but didn't get the time.

**Comment by AsafCX** [comment]
Hi,

Currently, we'll keep using getAddtionalMetadata( We use it in several locations throughout the code)
Can you please try this image:
checkmarx/cx-flow:57d4c6c
And update if your problem solved
Thanks

**Comment by marcandre-larochelle-bell** [comment]
Yes, it is fixed in` checkmarx/cx-flow:57d4c6c`, thansk a lot!

**Comment by AsafCX** [comment]
I'll push the update to master.
Thanks for the update

**Comment by v-marx** [comment]
Hey guys,

Just to report i encountered the same issue (_noteable_id is invalid_) with the image 
checkmarx/cx-flow@sha256:5147c656461544f58b5f333bf837ba7e40fd1ddda4a3169b12e2188c89f50869

The image _checkmarx/cx-flow:57d4c6c_ did fix it, but it would seem as per today the fix is not yet in the latest cx-flow image ?

Cheers,
Vincent

**Comment by cx-scord** [comment]
@jbrotsos Shouldn't this be closed?
