### ISSUE TITLE
exclude folders with a single folder doesn't work if the folder is trailed with a '/'

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#658]
### Description

When using the exclude-folders option from CLI and passing through a single folder for example:
java -jar cx-flow-1.6.18.jar --scan --cx-team="CxServer/team1" --cx-project="project1" --app="MyApp" --spring.config.location=C:\Dev\cxflow\application.yml --f=C:\Dev\WebApplicationTest --exclude-folders=”**Pages/**”
 
The Pages folder doesn't get excluded as expected
When adding the Exclude Folder filter of “Pages/” directly in Checkmarx Web Portal it scans correctly.
From CxFlow it still includes this folder and reports findings. 
Furthermore the project  which is showing in the portal does reflect this exclude:
 
But still shows results from this folder:

As a workaround removing the trailing / from the exclude-folders and using just "Pages" works.
If this is the expected behaviour than the documentation should be updated at least as it's currently using the '/' which doesn't work for a single folder:
![image](https://user-images.githubusercontent.com/1933763/109089472-697af480-7765-11eb-8129-3e0c4dd7d9dc.png)

### Expected Behavior
The files in the folder called Pages shouldn't be scanned, and no results should be displayed for these files 
### Actual Behavior
![image](https://user-images.githubusercontent.com/1933763/109089271-10ab5c00-7765-11eb-8f8b-e4d2c21ea0fd.png)

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)
![image](https://user-images.githubusercontent.com/1933763/109089140-d80b8280-7764-11eb-9fbc-ff7a0f404012.png)

**Comment by itsKedar** [comment]
Fixed in 1.6.25
