### ISSUE TITLE
Async mode is not implemented for CxSCA scan

### ISSUE THREAD

**Issue by fredericmalo** [checkmarx-ltd/cx-flow#666]
Hello, 

### Description

In a Gitlab pipeline with latest cx-flow image, async mode is not implemented for CxSCA. What we tried: 

* NONE bug-tracker works for CxSAST
* WAIT bug-tracker works for CxSCA
* but NONE bug-tracker provides no error with CxSCA, but also does not run a SCA scan
 
### Expected Behavior

A SCA scan should run in aSync mode 

### Actual Behavior

No SCA scan has been run, as cx-flow ends successfully

### Reproduction

Just run a SCA scan with bug-tracker NONE.

### Environment Details

- Gitlab pipeline
- European SCA tenant
- latest cx-flow Docker image

Thanks

**Comment by AvivCx** [comment]
Resolved
