### ISSUE TITLE
Issues are not closed in Gitlab on remediation scan

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#677]
### Description

When merging a feature branch that contains fixed issues to the master branch, and scanning the master branch after the merge request, issues are not closed in Gitlab.

### Expected Behavior
fixed issues are closed in Gitlab

### Actual Behavior
issues remain open

### Reproduction
Basically follow the steps outlined in the CxFlow Gitlab lab: https://github.com/checkmarx-ltd/cx-flow/wiki/Labs#cliprep
The issue occurs for both Webhook and pipeline scans

> Detail the steps taken to reproduce the issue
> 
Pipeline project: https://gitlab.com/jurgen-cx/gitlab-cxflow/gitlabpipelinetest
This works as is

Webhook project: https://gitlab.com/jurgen-cx/gitlab-cxflow/cxflow_gitlab_webhook_lab
This requires setting up webhooks and running CxFlow on a separate machine
>

This is a regression. When I did the Gitlab lab in May 2020, it worked perfectly. Pse see this project here
https://gitlab.com/jurgen-cx/gitlab-cxflow/cxflowgitlab

**Comment by jbrotsos** [comment]
I was unable to reproduce this, it closes tickets for me.  Can you please try to reproduce with a small unit test.

**Comment by juegge** [comment]
Hi,
I know why. In fact it goes back to the question why there is a discrepancy of findings between CxSast and findings shown in gitlab. I found the answer. In Gitlab one type of issue is shown for each source file concerned. I am not sure whether is is intended behavior or not. 
So if some issues are fixed but there are still more issues of the same type in that specific file the issue is not closed. 
So I guess this issue can be closed

**Comment by juegge** [comment]
see previous comment
