### ISSUE TITLE
Link for Checkmarx.gitlab-ci.yml is wrong

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#680]
### Description

The links for Checkmarx.gitlab-ci.yml the on the labs page
https://github.com/checkmarx-ltd/cx-flow/blob/8e4c8024a1051fa55653c9e53548ea183520bd53/docs/Labs.md

are wrong 
they  should be replaced by this one
https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/master/src/main/resources/samples/gitlab-config.yml
Thanks

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by jbrotsos** [comment]
It's been update, it will be in the next release.  You can see it in the "develop" branch.
