### ISSUE TITLE
Feature to replace Checkmarx logos, decorations and text in PR comments using custom template

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#683]
### Describe the problem

PR reports on the SCM arrive with Checkmarx logos, decorations and Checkmarx references like any direct links to the Checkmarx product "Checkmarx SAST" or "Cx-SAST") that are not customizable. 

There are times where one doesn't want to give out the AppSec scanning tool's brand or specific products to the developers, for example, like when one has outsourced development to an external company and don't want to give out the technology being used to scan so or even link to the AppSec UI.

### Proposed solution

Create a markdown properties file to be placed on the same directory as the _application.yml_, to be read by CxFlow to customize strings and logo references (local files or remote based),  regarding Checkmarx products (Cx-SAST/CxSAST, CxSCA/Cx-SCA).

These will replace the PR comments' references on the Markdown Helper and comment source code files, or even have boolean values to be enable/disable displaying direct links to the UI app.

I found a few source files having references to Checkmarx wording, like:

- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/utils/MarkDownHelper.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/PullRequestCommentsHelper.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/BugTrackerEventTrigger.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/utils/HTMLHelper.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/ThresholdValidatorImpl.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/GitHubService.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/BitBucketService.java
- https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/ADOService.java

I understand this would require some overhaul on the Service files way of building these strings, but I leave the idea and some screenshots below with some situations where we can find the references (just) here in GitHub.

### Additional details

A few screenshot examples of the references I mention:

Scan sent to Checkmarx comment:
![image](https://user-images.githubusercontent.com/68207834/111147199-1e911780-8582-11eb-9ee0-da7a4f5b2353.png)

---
Scan status "checkmarx" check message name:
![image](https://user-images.githubusercontent.com/68207834/111146663-9a3e9480-8581-11eb-858f-74de6d2f062f.png)

---
Scan Initiated message:
![image](https://user-images.githubusercontent.com/68207834/111147041-002b1c00-8582-11eb-9d65-9189c5bd1fb4.png)

---
Scan report message:
![image](https://user-images.githubusercontent.com/68207834/111146545-7a0ed580-8581-11eb-8995-f0687e8c67bb.png)

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
