### ISSUE TITLE
Add comment when CxFlow blocks a merge request

### ISSUE THREAD

**Issue by jharriscx** [checkmarx-ltd/cx-flow#685]
### Customer would like comments added when CxFlow blocks a merge request

When merge request is blocked, return a reason why .. such as 'requirements not met' or 'High severity vulnerabilities detected in scan executed prior to MR'

### Proposed solution

Add a comment to the blocked MR

### Additional details

> Add any other details / contexts / screenshots about the feature request.
![image](https://user-images.githubusercontent.com/60802052/111673654-6f01b280-87d8-11eb-897a-2cfab7b9755e.png)

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
