### ISSUE TITLE
Password exposure using debug option

### ISSUE THREAD

**Issue by cyberfrenz** [checkmarx-ltd/cx-flow#691]
### Description

When utilizing the cx flow cli option --project and adding on the debug option, the cleartext password is written as console output and within the cx-flow.log

### Expected Behavior

Authentication mechanism can be specified but password should be obfuscated in log file such as username=blah password=*****

### Actual Behavior

Password is exposed as part of the console output and written into log file.

### Reproduction

> Detail the steps taken to reproduce the issue
<img width="1871" alt="CX FLOW password debug vuln" src="https://user-images.githubusercontent.com/8942759/112535023-059a1a80-8d69-11eb-82ef-78091932eb5a.PNG">

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

Command: java -jar cx-flow-1.6.18-java11.jar --spring.config.location="path" --project --branch=master --cx-team="team" --cx-project="project" --repo-name="repo" --namespace="namespace" --debug 
OS: Alphine Linux with JRE 11, ran as docker container

**Comment by rupesh571** [comment]
This is true, not only for --project, also true for --web or any other methods. In fact, in --debug option, it outputs body data of POST, PUT, etc calls. So It exposes other information like the GitHub access token when a new project is created via Github hook. Per log, this issue is from "o.s.web.client.RestTemplate" Class.

**Comment by itsKedar** [comment]
Fixed in 1.6.35
