### ISSUE TITLE
PDF Report

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#692]
### Describe the problem

The CLI Plugin has an option to generate a PDF report, it would be nice to be able to generate such a report from CxFlow too.

### Proposed solution

A "bug tracker" which generates a PDF Report.

### Additional details

Can be seen at this link: [https://checkmarx.atlassian.net/wiki/spaces/SD/pages/914096139/CxSAST+CxOSA+Scan+v8.9.0](https://checkmarx.atlassian.net/wiki/spaces/SD/pages/914096139/CxSAST+CxOSA+Scan+v8.9.0)

**Comment by jbrotsos** [comment]
Hello @marcandre-larochelle-bell, 

Can you walk me through your workflow?  Do you want a report emailed to someone specific?  How is the PDF used?  Who is reviewing the PDF?

James

**Comment by marcandre-larochelle-bell** [comment]
1. We are using the CLI plugin in a docker as of right now and migrating to CxFlow, I want to offer the same possibilities as the
    CLI plugin. Some team prefer having a PDF.
2. No, an artefact in GitLab would be enough (but that does sound like a interesting/useful feature)
3. Yes. the pipeline would most likely be set to manual so when the scan is done it would generate a report
4. Offer a human readable alternative to Gitlab/Jira tracking
   4.1. Side Note: I wasn't able to get the Json bug tracker to work properly, it didn't use the data folder / file name format args, it 
         only gave the default tmp folder and file name format. 
5. Developers

Also have a question, is it currently possible to use multiple bug trackers (say create Gitlab Issues and generate a Json report)?

Thanks

**Comment by jbrotsos** [comment]
This is a first, I have never heard developers wanting results in a PDF file.

You can, however, use post-scan actions to create a PDF file after a scan:

https://checkmarx.atlassian.net/wiki/spaces/KC/pages/1170346238/Configuring+Pre+Post+Scan+Action+v9.0.0+and+up

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.

**Comment by charlykno64** [comment]
A lot of organizations require documentation (most cases in pdf) because at any time they must respond to an audit. So developers must upload their reports to meet this requirement. With DevOpsSec not all developers have access to Checkmarx Console. 

First time I have heard developers don't need a PDF or document. 
Sadly this will not be implemented with CxFlow but we can buy another solution next year for our 200+ devs/projects.

**Comment by cx-scord** [comment]
@jbrotsos do you know if it's possible to revisit this on @charlykno64's feedback?
