### ISSUE TITLE
Adding custom labels breaks cxflow standard functionality

### ISSUE THREAD

**Issue by geetanadkarni** [checkmarx-ltd/cx-flow#695]
### Description

1. Adding custom labels breaks the cxflow functionality. Cxflow adds the two labels automatically "CX" and "app:PROD", however, if we define additional labels, it does not work. this looks to be a bug that breaks the normal functioning of cxflow, it that it does not create the tickets. 

> Provide a description of the issue

### Expected Behavior
after adding custom labels to the yaml file, when the file is triggered, it should run appropriately and create the tickets by adding the standard labels "CX" and "app:PROD" and the custom labels that we added. 

### Actual Behavior

after adding custom labels to the yaml file, when the file is triggered, it does not run, nothing happens. 

### Reproduction

> Detail the steps taken to reproduce the issue
> java -jar ./build/libs/cx-flow-1.6.18-cvent.jar --spring.config.location=./YAML/conference-application.yml --project --cx-team="CxServer/SAST/xxxx" --cx-project="xxxx" --app=PROD

**Comment by geetanadkarni** [comment]
@jbrotsos  In our testing we tried to pass an array of labels as "CX app:PROD Appsec-SASTFinding" but due to Jira defaults app:PROD was converted to app_PROD since ":" is an illegal character for Jira labels.
[conference-application (1).zip](https://github.com/checkmarx-ltd/cx-flow/files/6239205/conference-application.1.zip)

**Comment by itsKedar** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
