### ISSUE TITLE
Push tickets grouped based on destination files

### ISSUE THREAD

**Issue by geetanadkarni** [checkmarx-ltd/cx-flow#696]
### Describe the problem

> Currently CxFlow lets us create tickets grouped based on the source file. However, with regards to how remediation is applied to a lot of major findings like SQLi and XSS that are based on destination files. It would be very helpful if we can group the tickets based on destination files as well. This also is a request for enhancement.

### Proposed solution

> currently we are able to group tickets based on source files. I would like to be able to group tickets based on destinations files.

**Comment by itsKedar** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
