### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#697]
### Description

1. https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#transitions 
- "`" in the end of all lines
	
2. https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#jira
- indentation problem & lower case:
	
3. https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#priorities
- Lower case for "information"

4. https://github.com/checkmarx-ltd/cx-flow/wiki/Config-As-Code#future-specs
- What Future Specs mean ? When they will be available ?
	
5. https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#application-properties-sample
- ServiceNow, GitlabDashboards and other are not listed in bug-tracker-impl field
- Typo in Jira properties Low and Lower case for "information":
	
6. https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#bugtrackers
- Missing BugTrackers: Rally, ServiceNow, GitlabDashboards and other...
	
7. https://github.com/checkmarx-ltd/cx-flow/wiki/Execution#docker
- Missing CxFlow CLI commands examples with Docker
- "`" should be removed from the docker command
- Can we please include CLI mode examples for Bitbucket Pipelines, Github Actions, ADO piplines, Jenkins pipelines ?
	 	
8. https://github.com/checkmarx-ltd/cx-flow/wiki/Integration-with-CxSCA#adding-the-cxsca-configuration
- Need to mention some SCA Urls are for the NA tenant and other for the Europe tenant			
	
9. https://github.com/checkmarx-ltd/cx-flow/wiki/Integration-with-CxSCA#bug-trackers
- Does it supports Rally, Servicenow and other bug trackers not mentioned ?
- "team" key should be added to Default configurations presented, it can only be seen in the end of the page	
	
10. https://github.com/checkmarx-ltd/cx-flow/wiki/Labs#requirements-for-labs		
- Labs should be updated to the latest version, or specify version agnostic labs and define pre-requisites
	
11. https://github.com/checkmarx-ltd/cx-flow/wiki/Prerequisites-and-Requirements
- Missing mention of 9.2 and 9.3		
- Do we support Bitbucket as Issue Tracking ? I don't think so	
- We provide details on how you can generate tokens for ADO and Github, but not for JIRA, Gitlab and Bitbucket
- No mention of when using CLI mode, CxFlow might use the token that is available already on the pipeline as best practice - so no need of generating new tokens	
	
12. https://github.com/checkmarx-ltd/cx-flow/wiki/WebHook-Registration#bitbucket-cloud
- Missing details & images on how you create a webhook in Bitbucket Cloud

13. https://github.com/checkmarx-ltd/cx-flow/wiki/YML-Example-Files
- Need for Examples with more combinations like: Github + JIRA or Gitlab + CSV or ADO + JIRA....

### Expected Behavior

Fix docs

**Comment by marcandre-larochelle-bell** [comment]
Also missing information as how to setup codebashing correctly: https://github.com/checkmarx-ltd/cx-flow/wiki/CodeBashing
(no mention of what is the API secret, where to locate it, etc., maybe an example?)
