### ISSUE TITLE
Cosmetic errors issues with Jira description

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#701]
### Description

A recent release has the "Addition Info" near the bottom of the description, which is grammatically incorrect.

All descriptions also appear to have "[Training|null]" added as some sort of logic that fails to prevent invalid CodeBashing links.

### Expected Behavior

The term should be "Additional Info".

"[Training|null]" should not appear if there are no CodeBashing links to provide.

### Actual Behavior

"Addition Info" is hard coded in the code, so it will always be that way.

There may be a configuration that would allow "[Training|null]" to show something useful, but it always shows up.

### Reproduction

No specific configuration for CodeBashing with CxFlow 1.6.20.

### Environment Details

CxFlow 1.6.20
Jira 8.16 and Jira Cloud

**Comment by itsKedar** [comment]
Codebashing is currently not supported with cx-flow closing this issue.
