### ISSUE TITLE
Cosmetic Issues with ADO on-prem PR decorations

### ISSUE THREAD

**Issue by AntGarSil** [checkmarx-ltd/cx-flow#702]
### Description

Line breaks are not being rendered as such, which makes for an ugly display.

![breaklines](https://user-images.githubusercontent.com/1711399/113908934-1e60f200-97a5-11eb-8565-6f8041b2a458.png)

### Expected Behavior
Break lines are shown as expected - CRLF

### Actual Behavior
HTML is not rendered and tags are displayed as text

### Reproduction

1) Configure ADO to work with CxFlow via service hooks to conduct SAST scans
2) Submit a PR
3) Trigger a SAST scan
4) Observe decorated results

### Environment Details

Azure DevOps 2020.1 with latest CxFlow

**Comment by AntGarSil** [comment]
#703

**Comment by satyamchaurasiapersistent** [comment]
This issue has been already fixed.
