### ISSUE TITLE
Gitlab: SAST Preset not getting overridden 

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#711]
### Description

SAST Preset not getting overridden even with settings override set to true

**Note: The settings override works for the excluded files/path, but not for the preset.**

### Expected Behavior

Regardless of the remote checkmarx preset for the project, it should be overridden by the preset specified in CxFlow

### Actual Behavior

Uses the remote checkmarx preset instead of the preset specified in CxFlow (Gitlab CI), similar to CxConsolePlugin.

### Reproduction

Re-scan an already existing project in Checkmarx, but change the specified preset in the CxFlow CI (tested using GitLab)

Tried the following ways to enable the settings override:

- ` CHECKMARX_SETTINGS_OVERRIDE: "true"`
- Passing the settings override to the command line args: `--checkmarx.settings-override="true"`

combined with the following ways to specify the preset:

- `CHECKMARX_SCAN_PRESET: ${SAST_PRESET}`
- Passing the preset override to the command line args using: `--checkmarx.scan-preset="${SAST_PRESET}"`
- Passing the preset override to the command line args using: `--preset="${SAST_PRESET}"`

**The settings override works for the excluded files/path, but not for the preset.**

### Environment Details

Checkmarx 8.9.0
CxFlow: 57d4c6c (after the update comment on merge request fix)

**Comment by jbrotsos** [comment]
@marcandre-larochelle-bell are you using the GitLab template?

**Comment by marcandre-larochelle-bell** [comment]
No, but our template is heavily-based on the Gitlab template (since we have a self-hosted gitlab/checkmarx, had to add some of the params + excluded files/paths, etc.).

**Comment by marcandre-larochelle-bell** [comment]
@jbrotsos any news on this? thanks!

**Comment by itsKedar** [comment]
Fixed in 1.6.42
