### ISSUE TITLE
Cx-Flow not creating issues on GitLab CE

### ISSUE THREAD

**Issue by charlykno64** [checkmarx-ltd/cx-flow#713]
Description
CX-Flow is executed but the issues are not created on GitLab CE.

Expected Behavior
CX-Flow creates issues and I can see them on GitLab Issues

Actual Behavior
Checking the Troubleshooting section "Command Line Arguments" I found a sample output behavior with the message "Processing Issues with custom bean" and my execution has one of this message but after that a couple of "Creating new issue with key" messages are expected but there is no one. Instead I found a "Executing getIssues GitLab API call" message from "GitLabIssueTracker" may be called from "IssueService.java" (line 107) and after that the following messages:

- Response 200 OK
- Reading to [com.checkmarx.flow.dto.gitlab.Issue[]]
- Finalizing GitLab Processing
- ####Checkmarx Scan Results Summary####
- Team: [I removed this]
- The vulnerabilities found for the scan are: high: 0, medium: 1, low: 1, info: 23
- To view results use following link: [I removed this]
- ...
- ...
- Completed Successfully

Reproduction and Environment:
Checkmarx 8.9.0 HF14
Cx-Flow 1.6.9
GitLab 13.0.14 CE over Ubuntu 18.04 LTS

Tried the following ways to get the expected behavior:
- Changing the project from private to public
- Changing the filter severity explicitly
- Deleting the project on Checkmarx Web
- Setting incremental to false
- Creating a new project on GitLab and using it
- Tested with commit and MR

This is my first issue so if I did something wrong, excuse me.
[raw_log.txt](https://github.com/checkmarx-ltd/cx-flow/files/6368482/raw_log.txt)

**Comment by jbrotsos** [comment]
@charlykno64 There is a filter to only create issues for only HIGH results.  You can override this setting if you wish...

if following the directions here:  checkmarx.com/gitlab

Add a variable:

CX_FLOW_FILTER_SEVERITY: 

And add the severity you wish.

**Comment by charlykno64** [comment]
@jbrotsos I tested it previously with the following values for the CX_FLOW_FILTER_SEVERITY variable:

- High,Medium,Low,Informational
- Low

The result was the same but your observation was in the right direction. I did a search in the log for the word "severity" with the following relevant results:

- Severity="Medias"
- Severity="Bajas"
- Severity="Información"

One more test with the variable CX_FLOW_FILTER_SEVERITY with the value as "Bajas" confirmed that the results are showing as expected. The words are in spanish language and I think that there is a config behind them replacing the expected words in english language (Low, Medium", etc.).

I can continue my work now but some mention of this issue is missing from the documentation or it is indeed a bug.

Thanks for your help @jbrotsos

**Comment by jbrotsos** [comment]
Hey @charlykno64 ,

Sorry for the delayed response.  I'm confused on the issue.  Can you let me know:

- What exactly worked
- What exactly didn't work

I'll then determine if it's a bug fix or a documentation fix. 

And are you saying there was an issue with Spanish words?

Thanks again for your feedback - much appreciation.
James

**Comment by charlykno64** [comment]
Sure.

As you can see in the attached file there are a few lines with te type of severity, example:

`2021-04-23 21:02:50.325 DEBUG 9 --- [           main] o.a.http.wire                             [UioRiINq] : http-outgoing-0 << "  <Query id="1670" categories="PCI DSS v3.2;PCI DSS (3.2) - 6.5.8 - Improper access control,OWASP Top 10 2013;A4-Insecure Direct Object References,OWASP Top 10 2017;A5-Broken Access Control" cweId="36" name="Absolute_Path_Traversal" group="Java_Medium_Threat" **Severity="Medias"** Language="Java" LanguageHash="0125956323748501" LanguageChangeDate="2020-04-17T00:00:00.0000000" SeverityIndex="2" QueryPath="Java\Cx\Java Medium Threat\Absolute Path Traversal Versi[0xc3][0xb3]n:1" QueryVersionCode="68121957">[\r][\n]"`

Look at that Severity=Medias . The instance of Checkmarx that we are using is configured in spanish and I thought: Is it possible that instead of filtering for "Medium" I need to filter for "Medias" in Spanish?

So I changed the CX_FLOW_FILTER_SEVERITY from "Medium" to "Medias" and It worked, the issues are created now. I don't know how is it designed but I'm thinking: 

1. The type of severity should be always "Medium" regardless of the language or
2. The docs should be updated with a note saying the severity types by language or 
3. The guys in my company misconfigured checkmarx.

**Comment by jbrotsos** [comment]
Ok, I understand a little bit more so "Medias" does indeed work.

Thanks,
James

**Comment by jbrotsos** [comment]
Marking as closed.
