### ISSUE TITLE
Show "New" or "Recurrent" state in PR comments

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#729]
### Describe the problem

Customer requests a feature to show which issues have been introduced by the PR in the PR comment.

### Proposed solution

Show the "New" or "Recurrent" state in the PR comment.  

### Additional details

This would be a best effort attempt to show what was found in new code and is classified as "New".  Vulnerabilities that were re-introduced will show "Recurrent".  Subsequent scans invoked due to source branch updates would also show prior "New" vulnerabilities as "Recurrent".

**Comment by jbrotsos** [comment]
The thought is to compare the PR branch and the target branch and determine the delta.  We are doing this for the AST integration and will potentially use the logic for that here.

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
