### ISSUE TITLE
Enable Project level Custom Fields

### ISSUE THREAD

**Issue by agehring** [checkmarx-ltd/cx-flow#730]
### Describe the problem

Metadata is simply information or data about data. It’s a way to find out what your data means or represents. It typically contains a description of the data and provides important context.

An implementation of Metadata in CxSAST is the Custom Fields for each project, which allow for the projects to have up to 10 custom fields defined, in a key:data format.

Updating or populating the data in the Custom Fields permits a customer to add or update that context, however in the current implementation the functionality isn't currently supported.

The Metadata is/can be used for reporting since the field is accessible through OData and APIs ( e.g.; Release type, Branch Name, correlation data),  and if included in the "Request" object can also be use in external (groovy) scripts for management of Project names, Team names, Branch scripts, and Comments.

### Proposed solution
Provide Config-as-code support for Custom Fields:
 {
  "version": 1.0,
  "project": "XYZ-${repo}-${branch}",
  "team": "/a/b/c"
  "customFields":{
    "key1":"value",
    "key2":"value"
  },
...

When included, update the custom field in the project (REST API), and include the fields in the "Request" object

### Additional details
Additional context in the Checkmarx Knowledge Center in 'IP Pages' :: Configuration as Code in CxFlow

**Comment by PhilP-CBA** [comment]
Upvoting this feature

**Comment by cx-scord** [comment]
@satyamchaurasiapersistent I believe this was completed in PR #872 and documented on the Execution page and referenced in the sample of Config-as-Code :

https://github.com/checkmarx-ltd/cx-flow/wiki/Config-As-Code
https://github.com/checkmarx-ltd/cx-flow/wiki/Execution#command-line
