### ISSUE TITLE
Generate HTML and/or PDF report files using templates

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#735]
### Describe the problem

Only machine readable files are currently generated and there's a need to have simple reporting using report artifacts in HTML and PDF format that could be used to display in other platforms or to be sent by e-mail or being copied to shared folders.

### Proposed solution

I propose generating HTML files using a few simple HTML report templates.

These can be based on the already existing implementations of [HTMLHelper.java](https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/utils/HTMLHelper.java) that produces PR Markdown comments and the [EmailService.java](https://github.com/checkmarx-ltd/cx-flow/blob/master/src/main/java/com/checkmarx/flow/service/EmailService.java) that generates the simple HTML vulnerabilities list for the bug-tracking's e-mail feature.

Having a PDF report generation feature that would also use one these HTML templates and transform it in a PDF would be useful as well.

### Additional details

These HTML templates could also be tweaked to show some basic graphic charts and other metrics similarly to how other Checkmarx CI/CD plugins, like the Jenkins/Bamboo ones provide.

Sample of the current EmailService simple HTML report used for the EMAIL bug-tracking feature:

![image](https://user-images.githubusercontent.com/68207834/118637090-55c3b500-b7cd-11eb-9e9f-35b6c9ac4258.png)

**Comment by jbrotsos** [comment]
Closing old feature requests that will not be implemented with CxFlow.
