### ISSUE TITLE
Default JIRA Labels product tag is always CX for both SAST and SCA

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#742]
### Description

When creating a JIRA issue, the default tags are not differentiating CxSAST from CxSCA tickets like it does with CxOSA, it's always `CX` for both and `CXOSA` for CxOSA.
I'm reporting this as a bug since if CxOSA has a different tag, then it makes sense CxSCA also has its own.

### Expected Behavior

The default JIRA "Labels" label set for each CxSCA issue should show `CXSCA`.

**EDIT [14-01-2022]** - It makes more sense to keep the `CX` label to mark tickets as coming from Checkmarx products and add new labels like `product:SAST`, `product:SCA`, `product:IAST` to split tickets by each different product.

### Actual Behavior

The default JIRA "Labels" label set for each CxSCA issue is showing `CX` instead:

![image](https://user-images.githubusercontent.com/68207834/119341774-0f1e0100-bc8c-11eb-9b73-36a2b8899a30.png)

### Reproduction

Scan a project with both CxSAST and CxSCA, the code should have vulnerabilities in both so the tickets are created for both and check how both issues have CX in the JIRA Issue "Labels" label

### Environment Details

CxSAST 9.3
CxFlow 1.6.20
JIRA Cloud

**Comment by cx-scord** [comment]
After the recent developments and new versions of CxFlow, it makes more sense just leaving the old `CX` label just to tell the ticket came from a Checkmarx product and add separate labels for different products, like `product:SAST`, `product:SCA`, `product:IAST`, etc...

**Comment by DhavalPatelPersistent** [comment]
This issue is fix as part of below PR:
https://github.com/checkmarx-ltd/cx-flow/pull/945
