### ISSUE TITLE
Add "--scan-timeout" as a CLI parameter

### ISSUE THREAD

**Issue by ebickle** [checkmarx-ltd/cx-flow#744]
### Describe the problem

CxFlow does not provide a parameter for controlling the timeout of a CxSAST scan. We have a few scans that take longer than 120 minutes and need the ability to configure the timeout when CxFlow is invoked as part of a GitHub action (https://github.com/marketplace/actions/checkmarx-cxflow-action).

The other methods of configuration (e.g. JSON and YAML) are not available when invoked through the GitHub action. 

### Proposed solution

Add a `--scan-timeout` CLI parameter to CxFlow.

**Comment by jbrotsos** [comment]
Hey @ebickle, you can use this option at the command line:

--checkmarx.scan-time=120

Or whatever time you want to change it to.

You can use any configuration option listed here: https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration by using the format key.value=

example:

cx-flow.filter-severity=High
checkmarx.exclude-files="test"
