### ISSUE TITLE
Undocumented/Poorly documented features need improvement in Wiki

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#752]
### Description

There are two features that are poorly documented that should be better documented:

**checkmarx.post-action-postback-id**: sets the SAST project's post-scan action to use the post-scan action with the provided ID defined in SAST .  (There is currently no documentation for this anywhere in the wiki.)  If not provided, the project does not get configured to use a post-scan action.

**checkmarx.settings-override**: defaults to false, if set to true the projects settings are re-written when each scan is invoked from CxFlow.

It is unknown if either of these is overridable via config-as-code.

**Comment by itsKedar** [comment]
Please check our latest documentation if required please reopen issue.
