### ISSUE TITLE
CxFlow uploads cx-flow.jar to CxSast instance with the current Checkmarx.gitlab-ci.yaml

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#769]
### Description

using the current Checkmarx.gitlab-ci.yaml, Cx-Flow also uploads CxFlow-jar. This can considerably increase zip file size and consequently unpacking time, i. e. total scan time. 

### Expected Behavior
Cx-Flow.jar is not uploaded

### Actual Behavior
Cx-Flow.jar is uploaded

### Reproduction

You can run any CxFlow Sast scan using the current Checkmarx.gitlab-ci.yaml file. 
You can add a 
before_script:
  - ls -al $CI_PROJECT_DIRECTORY
to check directly in the pipeline or look at the CxSrc directory of CxSast. 

I also created a pull request here so that it gets fixed for gitlab
https://github.com/checkmarx-ltd/cx-flow/pull/768

**Comment by jbrotsos** [comment]
You can currently override params field to exclude files from the zip (--cx-flow.zip-exclude).  If the project already exists, make sure you allow for overrides.

I'm also going to add it as a variable so you can override it in a new template.
