### ISSUE TITLE
CxFlow log file is not created where expected

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#775]
### Description

The configuration manual indicates that CxFlow can write log files. This is here
https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#main

using the following entries in athe application.yml file
logging:
  file: flow.log
  level:
    -web: debug
CxFlow successfully starts in webhook mode however no log file is created 

### Expected Behavior
log file is created in the same directory where the CxFlow jar file is located

### Actual Behavior
no log file is created

### Reproduction

start CxFlow 1.6.21 in webhook mode using the above logging config in the application yml

### Environment Details

windows 10 cmd line prompt

**Comment by cx-scord** [comment]
@juegge The correct syntax should had a `name:` property after `file:` to have the filename in it:

```yaml
logging:
  file: 
    name: flow.log
```

**Comment by juegge** [comment]
Hi,
that makes sense. However in this case you need to update the documentation. You have examples of the the wrong syntax all over the place (including no error message in CxFlow itself).
https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#main
https://github.com/checkmarx-ltd/cx-flow/wiki/CxSAST-Version-9.0#ninedotzero

**Comment by cx-scord** [comment]
@juegge Yes, there are a few places where the documentation misses the `name:` probably derived from an update to the syntax structure I believe, this might be something @jbrotsos can have a look at.
