### ISSUE TITLE
Thresholds for cx-flow not loaded using environment variables

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#781]
### Description

> When trying to set CxSAST vulnerability thresholds counts by severity through environment variables `CX_FLOW_THRESHOLDS_HIGH`, `CX_FLOW_THRESHOLDS_MEDIUM`, `CX_FLOW_THRESHOLDS_LOW`, `CX_FLOW_THRESHOLDS_INFO` they are not loaded and are kept null.

### Expected Behavior
When setting the thresholds using environment variables we should expect seeing the thresholds being respected and logged like this in the log file, like this:

`c.c.flow.service.ThresholdValidatorImpl  : Using CxSAST thresholds: {"HIGH":3,"MEDIUM":5}`

Here we are using High threshold to 3 and medium to 5.

### Actual Behavior

No thresholds are read when setting them through environment variables and we get this information:

`c.c.flow.service.ThresholdValidatorImpl  : Checking Thresholds exists. sast thresholds: false. sca thresholds: false`

It works if we set them on the `application.yml` config file or using `--cx-flow.thresholds.high=3`, `--cx-flow.thresholds.medium=5`  CLI parameters.

### Reproduction

Set the environment variables and run a CxFlow CLI to do a regular scan or using project mode to get results and using a bug-tracker.

### Environment Details

Latest CxFlow server running in either Windows or Linux

**Comment by cx-scord** [comment]
> Hi @cx-scord,
> 
> configured name for environment variables are incorrect.
> 
> It needs to be CXFLOW_THRESHOLDS_HIGH . This is also mentioned in https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration page.
> 
> Thanks

@itsKedar I find this odd, I would like to ask you if you tested or was it fixed? On my tests at the time it didn't work with either.

Regarding environment variables, all of them always started by `CX_FLOW_***` or at least have in the past, a good example is the GitLab template that works:
- https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v3/Checkmarx.gitlab-ci.yml

Also, the underscore `_` in `CX_FLOW` matches the hyphen in the correct config `cx-flow` property keyword of the YAML configuration, but I believe it works without too, but the correct notation should be with the underscore to match the original config.

I understand it could work without the underscore as well, but should definitely work with and would be good if it works with both.

**Comment by itsKedar** [comment]
Hi 

This issue was tested and works with CXFLOW_THRESHOLDS_HIGH. 

Thanks
