### ISSUE TITLE
Add JAVA_OPTS as an ENV variable in Docker image

### ISSUE THREAD

**Issue by cx-leonelsanches** [checkmarx-ltd/cx-flow#785]
### Describe the problem

Today we had a client not getting to upload a zip file due to `Java Heap Space` problem (`OutOfMemoryException`). 

### Proposed solution

To make it work, we had to customize several steps of their CircleCI configuration, like adding an executor with a certain amount of memory, and a custom JAVA_OPTS configuration. I believe this can be simplified with an ENV exposed in the Dockerfile. 

### Additional details

Latest version of CxFlow requires at least 1.5Gb of Heap Space in order to work without crashing.

**Comment by jbrotsos** [comment]
This is planned for 8/2021.

**Comment by JavierTobar** [comment]
Any updates on this? I've noticed that it was [added in v1.6.29 in the following MR](https://github.com/checkmarx-ltd/cx-flow/pull/889) but it was promptly removed in subsequent versions. Can we recycle this MR?
