### ISSUE TITLE
Allow severity count thresholds to be override in webhook's payload URL

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#795]
### Describe the problem

Allow severity count thresholds to be override using webhook's payload URL so a repo admin can define at least the number of Highs/Medium/Lows in order to fail builds.

### Proposed solution

Add @RequestParam properties to allow thresholds to be set, like thresholdHigh, thresholdMedium, thresholdLow and thresholdInfo to be similar to the following property:
```yaml
cx-flow:
  thresholds:
    high: <int | empty/null>
    medium: <int | empty/null>
    low: <int | empty/null>
    info: <int | empty/null> 
```
To be similar as described in the [Configuration wiki page's list of webhook URL overridable parameters](https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#webhook-url-parameters---code) that would translate in this webhook's URL parameters' example `?thresholdHighs=1&thresholdMediums=3` (a threshold of 1 High and 3 Mediums and no lows or informational) :

_@RequestParam(value = "thresholdHigh", required = false) Integer thresholdHigh,
@RequestParam(value = "thresholdMedium", required = false) Integer thresholdMedium,
@RequestParam(value = "thresholdLow", required = false) Integer thresholdLow,
@RequestParam(value = "thresholdInfo", required = false) Integer thresholdInfo_

Another alternative would be to just call the property "thresholds" and figure out how to pass the parameters all at once to map each of them later on the code to the thresholds' CxFlow object, like this: `?thresholds=high:1,medium:3` and doing the same exercise as above for the Configuration's webehook URL overridable parameters documentation:

_@RequestParam(value = "thresholds", required = false) List<String> thresholds_

This would allow more flexibility to map the values to their counts if custom vulnerability severity levels were to be introduced (like for example, adding `Critical` to the list of severity level types).

NOTE: I believe it's possible to map values directly from the payload URL into `Map<Object>` object types in Spring from GET request values like this one from the GtiHub's webhook payload, or using @RequestMapping but I'm not sure if it's possible, I found this interesting source if it helps to understand what I'm trying to say:
- https://stackoverflow.com/questions/7312436/spring-mvc-how-to-get-all-request-params-in-a-map-in-spring-controller/18489124#18489124

**Comment by satyamchaurasiapersistent** [comment]
This issue has been fixed in Release 1.6.29
![image](https://user-images.githubusercontent.com/102941840/210324751-893d6c0a-4534-4ad5-b373-a5816596629f.png)
