### ISSUE TITLE
Gitlab merge request: SCA recommended version column is empty

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#805]
### Description

When SCA issues are created during a Gitlab merge request, the column "Recommended version" in the merge request deciration is empty.

### Expected Behavior
"Recommended Version" should be filled in

### Actual Behavior
"Recommended Version"  is empty
### Reproduction

> Detail the steps taken to reproduce the issue
Create a merge request in Gitlab that also has a SCA scan with issues 
> 
> Where applicable, please include (exclude sensitive information):
Screen shot attached
![Gitlab_mr_rec_vers_empty](https://user-images.githubusercontent.com/64655256/130612623-674cdd12-ab90-4452-8ad8-a194388def9e.JPG)

### Environment Details
Gitlab cloud

**Comment by itsKedar** [comment]
Fixed in 1.6.42
