### ISSUE TITLE
Log always indicates team was not found and one is being created, even when team is there.

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#828]
### Description

When validating a SAST team exists, there is always a log entry such as the one below indicating the team is being created:

`Existing team with /CxServer/foo/bar was not found. Creating one...`

### Expected Behavior

If the team exists, don't emit the log line.

### Actual Behavior

The log line is always emitted.  This makes it difficult to troubleshoot issues.

### Reproduction

Handle a web hook event, it will show in the log.

The code at `src\main\java\com\checkmarx\flow\sastscanning\ScanRequestConverter.java` is as follows:

```
    private String aquireTeamMultiTenant(ScanRequest request, String ownerId, String namespace, String fullTeamName) throws CheckmarxException {
        request.setTeam(fullTeamName);
        String tmpId = scannerClient.getTeamId(fullTeamName);
        log.info("Existing team with " + fullTeamName + " was not found. Creating one ...");
        if (tmpId.equals(UNKNOWN)) {
            try {
                ownerId = scannerClient.createTeam(ownerId, namespace);
            }catch(Exception e){
                log.error("Existing team with " + fullTeamName + " was not found.");
                ownerId = UNKNOWN;
            }
        } else {
            ownerId = tmpId;
        }
        return ownerId;
    }
```

The log call that emits the log entry should in the the `if` statement and emitted only when tmpId is `UNKNOWN`.

### Environment Details

version 1.6.24

**Comment by itsKedar** [comment]
Fixed in 1.6.41 pull request https://github.com/checkmarx-ltd/cx-flow/pull/1230
