### ISSUE TITLE
ADO PR comment when "Active scan" reported is left Active

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#830]
### Description

Release 1.6.24 had a modification where PR comments were closed in the event there were no issues detected.  This works fine.

When a commit is made to the repo while a PR scan is active and the configuration is such that it blocks starting a new scan when one is active, a new comment "Scan not submitted to Checkmarx due to existing Active scan for the same project." is add to the PR and left "Active".  This causes issues when the repo policy is set to block merges if there are unresolved comments.

Not tested, but the configuration option to abort scan and start a new one may also have the same behavior.

### Expected Behavior

Comment regarding new scan (or aborted scan as the case may be) should be marked "Closed" since they are not part of the block merge validation thresholds.

### Actual Behavior

Comments are left "Active" and thus block merges when the "no unresolved comments" policy is enforced.

### Reproduction
1. Enable block-merge
2. Enable no unresolved comments policy on the repo
3. Configure web hooks for "PR Create" and "PR Update"
4. Open a PR, observe scan created.
5. Before the scan completes, commit an update to the repo.
6. Observe that a PR comment related to "new scan not started due to existing scan" is made, status is "Active"
7. Merge can't be completed due to "Active" comment status even if no issues were found in the scan.

### Environment Details

ADO with CxFlow 1.6.24

**Comment by TomKalmus** [comment]
Is there any update on this?

**Comment by itsKedar** [comment]
Fixed in 1.6.41 pull request https://github.com/checkmarx-ltd/cx-flow/pull/1236
