### ISSUE TITLE
Add labels to Gitlab's issues per severity

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#837]
Hi,

Currently, we can assign labels to issues to be  skipped/ignore/not updated after a scan:

` --gitlab.false-positive-label="false-positive"`

but there are no ways to specify labels to be added based on the severity of the detected vulnerability.

```
--gitlab.issues.severity.info="very low"
--gitlab.issues.severity.low="low"
--gitlab.issues.severity.high="high,must fix" #assigns 2 labels, high and must fix
```

etc.

Thanks

**Comment by itsKedar** [comment]
Fixed in 1.6.41
