### ISSUE TITLE
Gitlab MR Checkmarx results - link to view in Checkmarx broken

### ISSUE THREAD

**Issue by antesaj** [checkmarx-ltd/cx-flow#839]
### Description

When Checkmarx scan results are posted as comments in the merge request, the hyperlinks that should lead to the Checkmarx results are in this form:

`http://ec2amaz-052c4a8/CxWebClient/ViewerMain.aspx?scanid=1000658&projectid=61&pathid=1`

Clicking these links lead nowhere because the actual Checkmarx endpoint is:

`dev.checkmarx.mycompany.com`

### Expected Behavior

Expect these links to point to ``http://dev.checkmarx.mycompany.com/CxWebClient/ViewerMain.aspx?scanid=1000658&projectid=61&pathid=1``

### Actual Behavior

Links point to `http://ec2amaz-052c4a8/CxWebClient/ViewerMain.aspx?scanid=1000658&projectid=61&pathid=1`

### Reproduction

Include the .yml template in project's `.gitlab-ci.yml` file, open merge request, wait for scan results to post to MR

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

- Checkmarx 9.2.0
- Hosted on AWS EC2 with Route53 defining the A Record dev.checkmarx.mycompany.com pointing to the EC2 IP address

**Comment by jbrotsos** [comment]
Hello @antesaj ,

This is not specific to GL but rather how the hostname is configured.  The links come from the results - I believe you need to update the hostname in your DB:

https://checkmarx.atlassian.net/wiki/spaces/KC/pages/1312063567/Changing+Protocols+the+Hostname+and+Ports+for+Checkmarx+Components+v9.0.0+and+up

Can you contact support or PS for help setting this up?

Let me know,
James Brotsos
