### ISSUE TITLE
Authentication Failure on bitbucket when username contains @

### ISSUE THREAD

**Issue by sarapremashish** [checkmarx-ltd/cx-flow#856]
### Description

When a bitbucket username contains @ in the username the git client needs to have url encoded username to function as expected but this creates an issue once the cx flow tries to put a comment in the PR.  Since bitbucket uses basic authentication it fails to authenticate the with a url encoded version of the username.

### Expected Behavior

CX Flow to successfully put a comment on PR.

### Actual Behavior

Authentication fails when CX Flow tries to put a comment on PR.

### Reproduction

1. Create a bitbucket user which contains @ in the username.
2. Configure application.yml file with the username:personalaccesstoken for the token field.
3. Authentication fails at git client if username is not url encoded.
4. Authentication fails when CX Flow tries to put a comment on the PR. 

### Fix

in BitBucketService class, method createAuthHeaders should perform a url decode of token.

try {
            token = java.net.URLDecoder.decode(token, StandardCharsets.UTF_8.name());
        }
        catch (UnsupportedEncodingException e) {
            log.debug(LOG_COMMENT, "exception occurred");
        }

**Comment by gvocstr** [comment]
This also happens when the token itself has special characters. Bitbucket Server can generate tokens with at least plus (+) and forward slash (/) characters. When this happens, Cx-Flow encodes the token in the JSON payload that is sent to CxSAST, resulting in the REST API not being able to decode it, thus failing to browse the Git repository.

**Comment by itsKedar** [comment]
Hi @sarapremashish @gvocstr 

 Cx-Flow uses Basic Authentication internally to authenticate with bitbucket .

 As per bitbucket cloud docs bitbucket works with username:app_password which can be confused with personal access token.

https://developer.atlassian.com/cloud/bitbucket/rest/intro/#basic-auth

 where as bitbucket server works with username:password

https://developer.atlassian.com/server/bitbucket/how-tos/example-basic-authentication/#supplying-basic-auth-headers

 We will improve our documentation for this.

 

Thanks

**Comment by itsKedar** [comment]
Hi @sarapremashish @gvocstr

Cx-Flow uses Basic Authentication internally to authenticate with bitbucket .

As per bitbucket cloud docs bitbucket works with username:app_password which can be confused with personal access token.

https://developer.atlassian.com/cloud/bitbucket/rest/intro/#basic-auth

 
where as bitbucket server works with username:password

https://developer.atlassian.com/server/bitbucket/how-tos/example-basic-authentication/#supplying-basic-auth-headers

 We will improve our documentation for this.

 Thanks

**Comment by itsKedar** [comment]
fixed in 1.6.42
