### ISSUE TITLE
 I/O error on POST request for sourceCode/attachments nested NoHttpResponseException

### ISSUE THREAD

**Issue by charlykno64** [checkmarx-ltd/cx-flow#861]
### 
A few months ago I integrated CxFlow with my GitLab and Checkmarx (working very nice).
Previous config was working with GitLab 13 CE and Checkmarx 8.9 but now we have Checkmarx 9.4 so I updated the scope variable, team with slash and runner is executing and creating the project in Checkmarx (SAST) but throws an exception.

> Relevant lines in log
```
2021-10-27 00:44:51.302  INFO 9 --- [           main] c.c.s.s.CxAuthService                     [FkbCpXy1] : Logging into Checkmarx https://[domain]/cxrestapi/auth/identity/connect/token
2021-10-27 00:44:55.955  INFO 9 --- [           main] c.c.s.s.CxService                         [FkbCpXy1] : Retrieving Cx teams
2021-10-27 00:44:55.979  INFO 9 --- [           main] c.c.s.s.CxService                         [FkbCpXy1] : Found team /CxServer/SP/Company/INTEGRACION DE APLICACIONES PARA MAC2 with ID 15
2021-10-27 00:44:55.980 DEBUG 9 --- [           main] c.c.f.s.AbstractVulnerabilityScanner      [FkbCpXy1] : Auto profiling is enabled
2021-10-27 00:44:56.036  INFO 9 --- [           main] c.c.s.s.CxService                         [FkbCpXy1] : Creating scan...
2021-10-27 00:44:56.037  INFO 9 --- [           main] c.c.s.s.CxService                         [FkbCpXy1] : Updating Source details for project Id 11349
2021-10-27 00:55:11.500 ERROR 9 --- [           main] c.c.f.CxFlowRunner                        [FkbCpXy1] : An error occurred while processing request
```

According to the log the URL throwing the error is https://[domain]/cxrestapi/projects/11349/sourceCode/attachments

### Expected Behavior
The runner continues without error and I can review the security issues with GitLab (Issues)

### Actual Behavior
Throws an error [FkbCpXy1] : Finished with exit code: 10

### Reproduction

> Detail the steps taken to reproduce the issue
I am using a yml file with GitLab and the following code launches de job:

```
checkmarx-scan-sprint:
  stage: test
  rules:
    - if: '$CX_FLOW_BUG_TRACKER != "GitLabDashboard" && $CI_COMMIT_BRANCH =~ /sprint-\w+/ && $CI_COMMIT_MESSAGE =~ /checkmarx/' 
  image:
    name: checkmarx/${CHECKMARX_DOCKER_IMAGE}
    entrypoint: ['']
  variables:
    CHECKMARX_INCREMENTAL: "true"
  script:
    - ${CX_FLOW_EXE}
      --scan
      --app="${CI_PROJECT_NAME}"
      --namespace="${CI_PROJECT_NAMESPACE}"
      --repo-name="${CI_PROJECT_NAME}"
      --branch="${CI_COMMIT_BRANCH}"
      --repo-url="${CI_REPOSITORY_URL}"
      --cx-team="${CX_TEAM}"
      --cx-project="${CX_PROJECT}"
      --project-id=${CI_PROJECT_ID}
      --spring.profiles.active="${CX_FLOW_ENABLED_VULNERABILITY_SCANNERS}"
      --logging.level.com.checkmarx.flow.service=DEBUG
      --f=.
      ${PARAMS}
```

> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issu
[runner.log](https://github.com/checkmarx-ltd/cx-flow/files/7422391/runner.log)
e
### Environment Details
GitLab 13 running inside Docker
Runner 14.3.0 running inside Docker
Docker running inside Windows 10

Any suggestions?

**Comment by charlykno64** [comment]
> @charlykno64 Quick question are you developing in MacOS/Linux?
> 
> If no, please ignore.
> 
> If yes, do you have special MacOS/Linux characters in any file/folder names inside the source code directory structure like these?:
> 
> ```
> \ / : * ? " < > |
> ```
> 
> If you do have, you should use the `--cx-flow.zip-exclude=<regex_pattern>` parameter ([documented here](https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration#excluding-files-from-zip-archive)) to exclude those files from being sent to CxSAST, then try again, here's the documentation for that param:

Yes, we are using a few MacBook Pro, let me try it.

**Comment by charlykno64** [comment]
Good news. 

The zip exclude param did the trick. This is my YML file now:

`checkmarx-scan-sprint:
  code...
  script:
    - ${CX_FLOW_EXE}
      --scan
      --app="${CI_PROJECT_NAME}"
      --namespace="${CI_PROJECT_NAMESPACE}"
      --repo-name="${CI_PROJECT_NAME}"
      --branch="${CI_COMMIT_BRANCH}"
      --repo-url="${CI_REPOSITORY_URL}"
      --cx-team="${CX_TEAM}"
      --cx-project="${CX_PROJECT}"
      --project-id=${CI_PROJECT_ID}
      --spring.profiles.active="${CX_FLOW_ENABLED_VULNERABILITY_SCANNERS}"
      --logging.level.com.checkmarx.flow.service=DEBUG
      --logging.level.org.springframework.web.client.RestTemplate=DEBUG
      --logging.level.org.apache.http.wire=WARN
      --cx-flow.zip-exclude="[\+\/:\*\?\"<>\|], \.git/.*, .*\.png, .*\.mp4, .*\.jpg"
      --f=.
      ${PARAMS}
`
Thanks a lot guys, you are the best. I would never have solved it.
By the way I got a new error at mid way and it will be useful for someone to know about it:


`org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://172.19.78.205/api/v4/projects/2/issues": Connect to 172.19.78.205:80 [/172.19.78.205] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to 172.19.78.205:80 [/172.19.78.205] failed: Connection refused (Connection refused)`

What is doing that IP over here? This GitLab instance was working previously on Ubuntu with the IP 172.19.78.205 and now is working with Docker (inside Windows) with the IP 172.17.0.2, I used the the backup and restore feature. With the command "gitlab-ctl show-config" I found that the original IP (refused in the previous log) was there in some config params. So I decided:

1. Update the config.toml of the Runner (url, and url_clone params).
2. Update the gitlab.rb (external_url param) to explicitly declare the IP of Docker
3. **Clear** the GitLab Runner Cache.
4. Execute gitlab-reconfigure.

Now it's working with my first project.

**Comment by charlykno64** [comment]
The result for my second project (ios app) is: Failed
Relevant log info:

`http-outgoing-0 << "[read] I/O error: Read timed out"
http-outgoing-0 >> "GET /cxrestapi/sast/scans/1037592 HTTP/1.1[\r][\n]"
http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
http-outgoing-0 << "Cache-Control: no-cache[\r][\n]"
http-outgoing-0 << "Pragma: no-cache[\r][\n]"
http-outgoing-0 << "Content-Type: application/json; charset=utf-8[\r][\n]"
http-outgoing-0 << "Expires: -1[\r][\n]"
http-outgoing-0 << "Server: Microsoft-IIS/10.0[\r][\n]"
http-outgoing-0 << "api-version: 1.2[\r][\n]"
http-outgoing-0 << "X-AspNet-Version: 4.0.30319[\r][\n]"
http-outgoing-0 << "X-Powered-By: ASP.NET[\r][\n]"
http-outgoing-0 << "Date: Tue, 09 Nov 2021 18:08:22 GMT[\r][\n]"
http-outgoing-0 << "Content-Length: 1259[\r][\n]"
http-outgoing-0 << "[\r][\n]"
http-outgoing-0 << "{[\r][\n]"
http-outgoing-0 << "  "id": 1037612,[\r][\n]"
http-outgoing-0 << "  "project": {[\r][\n]"
http-outgoing-0 << "    "id": 11342,[\r][\n]"
http-outgoing-0 << "    "name": "credencial-digital-ios-sprint-3-2021-acc-y-disenio-responsivo",[\r][\n]"
http-outgoing-0 << "    "link": {[\r][\n]"
http-outgoing-0 << "      "rel": "project",[\r][\n]"
http-outgoing-0 << "      "uri": "/projects/11342"[\r][\n]"
http-outgoing-0 << "    }[\r][\n]"
http-outgoing-0 << "  },[\r][\n]"
http-outgoing-0 << "  "status": {[\r][\n]"
http-outgoing-0 << "    "id": 9,[\r][\n]"
http-outgoing-0 << "    "name": "Failed",[\r][\n]"
http-outgoing-0 << "    "details": {[\r][\n]"
http-outgoing-0 << "      "stage": "No engine can reserve memory for this scan",[\r][\n]"
http-outgoing-0 << "      "step": ""[\r][\n]"
http-outgoing-0 << "    }[\r][\n]"
http-outgoing-0 << "  },[\r][\n]"
http-outgoing-0 << "  "scanType": {[\r][\n]"
http-outgoing-0 << "    "id": 0,[\r][\n]"
http-outgoing-0 << "    "value": "AllScans"[\r][\n]"
http-outgoing-0 << "  },[\r][\n]"
http-outgoing-0 << "  "comment": "CxFlow Automated Scan",[\r][\n]"
http-outgoing-0 << "  "dateAndTime": {[\r][\n]"
http-outgoing-0 << "    "startedOn": "2021-11-09T12:01:55.243",[\r][\n]"
http-outgoing-0 << "    "finishedOn": null,[\r][\n]"
http-outgoing-0 << "    "engineStartedOn": null,[\r][\n]"
http-outgoing-0 << "    "engineFinishedOn": null[\r][\n]"
http-outgoing-0 << "  },[\r][\n]"
http-outgoing-0 << "  "resultsStatistics": null,[\r][\n]"
http-outgoing-0 << "  "scanState": {[\r][\n]"
http-outgoing-0 << "    "path": null,[\r][\n]"
http-outgoing-0 << "    "sourceId": null,[\r][\n]"
http-outgoing-0 << "    "filesCount": 0,[\r][\n]"
http-outgoing-0 << "    "linesOfCode": 1613879,[\r][\n]"
http-outgoing-0 << "    "failedLinesOfCode": 0,[\r][\n]"
http-outgoing-0 << "    "cxVersion": null,[\r][\n]"
http-outgoing-0 << "    "languageStateCollection": null[\r][\n]"
http-outgoing-0 << "  },[\r][\n]"
http-outgoing-0 << "  "owner": "me",[\r][\n]"
http-outgoing-0 << "  "origin": "CxFlow",[\r][\n]"
http-outgoing-0 << "  "originURL": null,[\r][\n]"
http-outgoing-0 << "  "initiatorName": null,[\r][\n]"
http-outgoing-0 << "  "owningTeamId": 15,[\r][\n]"
http-outgoing-0 << "  "isPublic": true,[\r][\n]"
http-outgoing-0 << "  "isLocked": false,[\r][\n]"
http-outgoing-0 << "  "isIncremental": false,[\r][\n]"
http-outgoing-0 << "  "scanRisk": 0,[\r][\n]"
http-outgoing-0 << "  "scanRiskSeverity": 0,[\r][\n]"
http-outgoing-0 << "  "engineServer": null,[\r][\n]"
http-outgoing-0 << "  "finishedScanStatus": {[\r][\n]"
http-outgoing-0 << "    "id": 0,[\r][\n]"
http-outgoing-0 << "    "value": "None"[\r][\n]"
http-outgoing-0 << "  },[\r][\n]"
http-outgoing-0 << "  "partialScanReasons": null,[\r][\n]"
http-outgoing-0 << "  "customFields": null[\r][\n]"
http-outgoing-0 << "}"
c.c.f.s.AbstractVulnerabilityScanner      [pYdoKP10] : Error occurred

com.checkmarx.sdk.exception.CheckmarxException: Scan was cancelled or failed
`
Of course I used the same config as the android app, I tested incrementing timeouts but it did not work and I don't know what to do now... Any ideas? 

this message is spinning in my head: "No engine can reserve memory for this scan".

**Comment by itsKedar** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
