### ISSUE TITLE
Supporting scan based level custom fields

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#873]
### Describe the problem

Staring 9.4 CxSAST introduced scan based level CF's (which are similar to what's described in https://github.com/checkmarx-ltd/cx-flow/issues/730 but on the scan level rather than the project.

Using this key/value pairs on the scan and including metadata such as git commit hash or any others is expected to be introduced in other plugins 

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by cx-scord** [comment]
@satyamchaurasiapersistent  I believe this was completed in PR #1094
