### ISSUE TITLE
Add SCA filter for vulnerabilities that break Policy Violations

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#904]
### Describe the problem

Currently there is no way to filter only SCA vulnerabilities that breach Policy Violations

### Proposed solution

Add a `filter-policy-violation` config to the `sca` block that only validates vulnerabilities that breach Policy Violations:

```yaml
sca:
  - filter-policy-violation: true|false
```

This will allow to create bug-tracking tickets only in cae SCA vulnerabilities breach policies.

**Comment by jbrotsos** [comment]
Released in 1.6.33
