### ISSUE TITLE
Scan queuing not working - regression from 1.6.29

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#910]
### Description

Scan queuing is not possible anymore starting from CxFlow 1.6.29 onwards, the condition for having the property checked was removed.

### Expected Behavior

When setting `checkmarx.scan-queing` to true, scans are note being queued in CxSAST and should take priority over `cx-flow.scan-resubmit`, meaning that scan-resubmit should be ignored if scan-queuing is set.

### Actual Behavior

Queuing is not working with `checkmarx.scan-queuing: true`, that condition is only used later on the code's logic and only when `cx-flow.scan-resubmit: true` and that's wrong. These settings should be mutually exclusive with queuing having priority/precedence over scan resubmission, meaning if `checkmarx.scan-queuing` is `true` then the `cx-flow.scan-resubmit` feature code shouldn't even be used.

With both `checkmarx.scan-queuing` and `cx-flow.scan-resubmit` set to true the problem is that resubmission is not ignored and the current scan will be canceled first instead of being queued and a new one will start immediately, that is wrong as the current scan shouldn't be cancelled with `checkmarx.scan-queuing` set to `true`.

This regression was introduced in [#884](https://github.com/checkmarx-ltd/cx-flow/pull/884) when the if condition `if(!getCxPropertiesBase().getScanQueuing()) (...)` that checked for the `checkmarx.scan-queuing` active condition **was removed**.

I also found that queuing is internal to the [checkmarx-spring-boot-sdk](https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/blob/19384c305cb01156d86d0b36da75012edfcf5162/src/main/java/com/checkmarx/sdk/service/CxService.java#L2395), and because of this, there should be:

1. Informative logging each 5 minutes or so telling the scan of the current project hasn't finished yet and;
2. Send a markdown feedback message to the PRs saying that the scan is still in CxFlow queue (and not CxSAST queue) to be sent to CxSAST to be scanned, or else no one knows the status of the scan request. This is also reflected in #905 

### Reproduction

Setting `checkmarx.scan-queuing` to true and resubmitting multiple scans to the same project shouldn't work.
If there's a scan in queue and `checkmarx.scan-resubmit` is `true`, the current scan should be cancelled and a new one starts, if it's false then Cxflow will cancel (as expected) the scan re-submission and never put it in queue.

### Environment Details

CxFlow 1.6.29, 1.6.30+

**Comment by DhavalPatelPersistent** [comment]
* #857 PR (added scanQueuing and scanQueuingTimeout  size/M)  changes were overridden by
#884 (Add scanResubmit property to config-as-code) are fixed in PR 911 (Scan Queuing Change)
