### ISSUE TITLE
cx-branch is not working if there is a /(slash) in the naming

### ISSUE THREAD

**Issue by enginates** [checkmarx-ltd/cx-flow#928]
### Description

We were trying to implement cx-branch 
if I create a branch **test** it is created as a branch of default and does not add to my project count.
But if I name my branch "**feature/test**" is creating this new scan as a new project and increasing my project count.

### Expected Behavior

if cx-branch set true, it should create as a branch project.

### Actual Behavior

if cx-branch set true, and naming contains /(slash) it adds as a new project

### Reproduction
Create branch name feature/test

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details
CxFlow as Windows service and version 1.6.30

PR that introduced this feature
https://github.com/checkmarx-ltd/cx-flow/pull/877

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by nleach999** [comment]
I confirmed this issue.  In this case, it is ADO where the issue manifests.  This may apply for other SCMs too, but I will be opening other defects for GitHub as I have test scenarios that demonstrate that branching doesn't work consistently the same on ADO as it does on GitHub.

You can observe a repository where this was recreated [here](https://dev.azure.com/CxNLeach/_git/Simply%20Vulnerable%20React).

The test has the following setup:

1. Default branch for the repo is master.
2. A branch named "demo-master" is listed in the config-as-code as a protected branch.
3. A licensed project "SimplyVulnerableReact-demo-master" exists in the target SAST system. 
4. No projects named "SimplyVulnerableReact-feature-testado" exist in the target SAST system.
5. The server side YAML has the following related configurations:
* No protected branches configured
* No branch naming scripts
* preserve project name is false

## Test 1
1. Cut a branch named "feature/testado" from "demo-master"
2. Change a file in "feature/testado"
3. Open a PR "feature/testado" -> "demo-master"

### Expected
Based on the config-as-code naming and CxFlow project name normalization, a branch project named "SimplyVulnerableReact-feature-testado" is created with a scan.

### Actual
A licensed project named "SimplyVulnerableReact-feature-testado" is created with a scan.

## Test 2
1. Remove project "SimplyVulnerableReact-feature-testado" from target SAST system, if it exists.
2. Cut a branch named "feature-testado" from "demo-master"
2. Change a file in "feature-testado"
3. Open a PR "feature-testado" -> "demo-master"

### Expected
Based on the config-as-code naming (no CxFlow naming normalization would change the name), a branch project named "SimplyVulnerableReact-feature-testado" is created with a scan.

### Actual
Worked as expected.

**Comment by HussainS12** [comment]
Fixed in PR #987
