### ISSUE TITLE
GitHub cx-branch - deployment of config as code in feature branch only makes licensed projects

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#930]
### Description

It is common for large organizations to have a global webhook and not define protected branches on the CxFlow server config.  Teams integrate CxFlow in their SDLC by adding config-as-code to a feature branch and testing how it integrates before pushing the config-as-code change to a protected branch.  This means a licensed project for the default branch (or really the root branch) may not exist in the SAST system since the repo has no yet been onboarded.

When making a feature branch with GitHub to add config-as-code, then opening a PR to merge the feature into the protected (default) branch, the PR scan creates a licensed project rather than a branched project since a project for the default branch doesn't exist.

### Expected Behavior
PR scans should make a licensed project for root/default branches if it doesn't exist, followed by a branch project for the PR source branch.

### Actual Behavior
A licensed project is created for the PR source branch.

### Reproduction

1. No projects or scans exist for any branches for the repo
2. The default branch does not have a config as code file
3. Server YAML has no protected branches listed
4. No project name script
5. Create a branch from default (master<-test-cxflow)
6. Commit config as code file to test-cxflow branch that forms project names in the form of "application-${branch}"
7. Config as code specifies the default branch as a protected branch
8. Open a PR from test-cxflow to master
**Expected:** Licensed project created for default branch following naming convention of config-as-code file in test-cxflow branch, branch project created with the parent as the project made for the default branch.
**Actual:** Licensed project created for the test-cxflow branch, no other projects created.

### Environment Details

CxFlow 1.6.30
Tested with GitHub Cloud, may apply to other SCMs as well.

**Comment by HussainS12** [comment]
Fixed in PR #987
