### ISSUE TITLE
GitHub - cx-branch requires default/root branch project

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#931]
### Description

This appears to work differently on ADO, see #928 

A project with the name of the root/default branch MUST exist when using GitHub as an SCM otherwise branching is totally ignored.

Following some of the same concepts described in #930 , it is often the case that a project for the root/default branch does not exist at the time the first child branch is deployed.  In some cases, a project for the root/default branch will never exist.

### Expected Behavior
Branching should work without a project specifically named after the root/default branch in a repo.

### Actual Behavior
All branching activities are ignored in GitHub unless a project named after the root/default branch exists.  This may apply to other SCMs, but it was verified to not apply when using ADO in #928.

### Reproduction

1. No project name script
2. Server YAML has no protected branches listed
3. The default branch (master) does not have a config as code file.
4. An integration branch named "demo-master" is cut from "master" (master<-demo-master)
5. No config-as-code file in "demo-master"
6. A feature branch named "feature-cxflow" is cut from demo-master (master<-demo-master<-feature-cxflow)
7. A licensed project exists in SAST named "application-demo-master" with no scans
8. A config-as-code file is checked into "feature-cxflow" naming "demo-master" as a protected branch
9. Open a PR from "feature-cxflow" to "demo-master"
Expected: Branch project named "application-feature-cxflow" created with parent project as "application-demo-master"
Actual: Licensed project named "application-feature-cxflow" created

Same as above except:
1. Delete licensed project "application-feature-cxflow"
2. Close PR opened in previous step
3. Create licensed project named "application-master" (name of default/root branch) with no scans
4. Reopen the PR from "feature-cxflow" to "demo-master"
Expected: Branch project "application-feature-cxflow" created with the parent project "application-demo-master"
Actual: Branch project "application-feature-cxflow" created with the parent project "application-master" (wrong parent project)

Following from previous test:
1. Delete projects "application-feature-cxflow" and "application-demo-master"
2. Leave licensed project "application-master" with no scans
3. Close PR opened in previous step
4. Reopen the PR from "feature-cxflow" to "demo-master"
Expected: Branch project "application-demo-master" created with parent "application-master",  branch project "application-feature-cxflow" created with the parent project "application-demo-master"
Actual: Branch project "application-feature-cxflow" created with the parent project "application-master" (wrong parent project)

Following from previous test:
1. Merge the PR from "application-feature-cxflow" to "application-demo-master".
Expected: Branch project "application-demo-master" created with parent "application-master".
Actual: As expected, but further tests should be taken to ensure projects are branching properly on more than 1 level below the default/root branch.

### Environment Details

CxFlow 1.6.30

**Comment by HussainS12** [comment]
Fixed in PR #987
