### ISSUE TITLE
JAVA_HOME env variable not set since v1.6.27

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#933]
### Description

After the changes done to the Dockerfile since v1.6.27, when the `Dockerfile` moved from using Alipne's openJDK base image to the base Alpine one and installing JDK manually, the JAVA_HOME variable is not defined anymore.
This, for example, can break scripts that rely on injecting self-signed certificates using the variable to find the path to the current JDK's _cacerts_ file and force users to set either hardcode the JAVA_HOME environment variable when loading the container or passing the hardcoded path when trying to access the JDK directory.

### Expected Behavior

Have the JAVA_HOME directory set on the container pointing to JDK's current softlink path to the installed and active version (`/usr/lib/jvm/java-1.8-openjdk`).
It should be set like this in the Dockerfile:

`ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk`

The last lines of the current Dockerfile would look like this:

```dockerfile
(...)

RUN apk add openjdk8=8.302.08-r2 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
COPY build/libs/cxgo/*.jar cx-flow.jar
ENTRYPOINT ["java", "-Xms512m", "-Xmx2048m", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=cxgo", "-jar", "cx-flow.jar"]
EXPOSE 8080
```

### Actual Behavior

The `JAVA_HOME` environment variable isn't set.

### Reproduction

Executing a `echo $JAVA_HOME` inside a new CxFlow container will show it's empty.

### Environment Details

Any CxFlow version since 1.6.27.

**Comment by jbrotsos** [comment]
@umeshwaghode @HussainS12 can you take a look at this?

**Comment by jndietz** [comment]
In case anyone else finds themselves here, I had to run some commands to find a `cacerts` file, which ended up being in `/usr/lib/jvm/java-1.8-openjdk/jre/lib/security`.  From there, it turns out that was a symlink to the actual `cacerts` file which is located in `/etc/ssl/certs/java/cacerts`

```
$ ls -axl $JAVA_HOME/jre/lib/security
total 76
drwxr-xr-x    3 root     root          4096 Mar 11 10:29 .
drwxr-xr-x   10 root     root          4096 Mar 11 10:29 ..
-rw-r--r--    1 root     root          2488 Jan 26 05:46 blacklisted.certs
lrwxrwxrwx    1 root     root            27 Mar 11 10:29 cacerts -> /etc/ssl/certs/java/cacerts
-rw-r--r--    1 root     root          2567 Jan 26 05:46 java.policy
-rw-r--r--    1 root     root         5[102](https://gitlab.devops.fnbo.io/transaction-site/transaction-site-util/-/jobs/311977#L102)8 Jan 26 05:46 java.security
-rw-r--r--    1 root     root           137 Jan 26 05:46 nss.cfg
drwxr-xr-x    4 root     root          4096 Mar 11 10:29 policy
```

I originally followed the GitLab documentation [located here](https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1929937052/GitLab+Integration#Adding-Certs), which won't work as it is layed out since you have to programatically set or hard-code the path to the `cacerts` file.

**Comment by jbrotsos** [comment]
@umeshwaghode can you review this?
