### ISSUE TITLE
using System.Tags as an --alt-fields option throws an error

### ISSUE THREAD

**Issue by cx-justin-ruth** [checkmarx-ltd/cx-flow#936]
### Description
When using --alt-fields as part of a command line call for CxFlow in project mode, if a customer uses System.Tags for additional meta data, the following error is returned.

```
--alt-fields="System.Tags:SCA"
```

[11:37 AM] customer
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"$id":"1","innerException":null,"message":"VS403691: Update to work item -1 had two or more updates for field with reference name 'System.Tags'. A field cannot be updated more than once in the same update.","typeName":"System.InvalidOperationException, mscorlib","typeKey":"InvalidOperationException","errorCode":0,"eventId":0}"

Per the documentation, these tags fields should be allowed for customer project tags in ADO but seem like They are already in use via Cxflow

**Comment by itsKedar** [comment]
Fixed in 1.6.45
