### ISSUE TITLE
Github links to issues in code are busted when running sast analysis via pipeline

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#937]
When a sast analysis is run using a pipeline in Github, the the links to the code locations of the respective issues are busted. They do not point to the proper location.

Expected Behavior
Link points to proper location
Example: https://github.com/jvlstuff/JavaVulnerableLab/blob/master/src/main/webapp/vulnerability/sqli/download_id_union.jsp#L18
Project: https://github.com/jvlstuff/JavaVulnerableLab

Actual Behavior
Link is busted:
Example: https://github.com/jvlstuff/JavaVulnerableLab/issues/null#L18

Reproduction
use the yml piplene of the project or any other yml pipeline that is using cxflow via the cxflow gh action: 

Detail the steps taken to reproduce the issue
dispatch the workflow e. g. push

Pipeline project: https://github.com/jvlstuff/JavaVulnerableLab
This works as is

**Comment by satyamchaurasiapersistent** [comment]
> When a sast analysis is run using a pipeline in Github, the the links to the code locations of the respective issues are busted. They do not point to the proper location.
> 
> Expected Behavior Link points to proper location Example: https://github.com/jvlstuff/JavaVulnerableLab/blob/master/src/main/webapp/vulnerability/sqli/download_id_union.jsp#L18 Project: https://github.com/jvlstuff/JavaVulnerableLab
> 
> Actual Behavior Link is busted: Example: https://github.com/jvlstuff/JavaVulnerableLab/issues/null#L18
> 
> Reproduction use the yml piplene of the project or any other yml pipeline that is using cxflow via the cxflow gh action:
> 
> Detail the steps taken to reproduce the issue dispatch the workflow e. g. push
> 
> Pipeline project: https://github.com/jvlstuff/JavaVulnerableLab This works as is

Hi @juegge We have checked from our end below is our finding : 

Ananlysis :

We have tried to replicate issue in web mode and we have found issues but link is not Broken.
Kindly recheck and also share which version of CXFLOW you are using.
![image](https://user-images.githubusercontent.com/102941840/165747329-37cb73a9-d1f6-4c28-9e1b-65f395cf9b3b.png)
