### ISSUE TITLE
Postback Mode not working properly

### ISSUE THREAD

**Issue by atheismann** [checkmarx-ltd/cx-flow#939]
### Description

We were seeing some odd behavior in that Postback is working, but instead of commenting on the PR, it is opening GitHub issues on a non-default branch.

It looks like a "projectName" and "teamName" field were added to the comments, but are not part of the decode method.  So CxFlow doesn't know they exist and the GitHub event type [here](https://github.com/checkmarx-ltd/cx-flow/blob/cfafb3bbedb6435f3e1ff91e905576c8cee0b5fb/src/main/java/com/checkmarx/flow/controller/FlowController.java#L241-L246) should actually be case 8 and the new fields should be added above it.

### Expected Behavior
CxFlow should issue a PR Comment or GitHub issue based on the "GitHub Method" in the scan comment.

### Actual Behavior
CxFlow is issuing GitHub issues even on PRs when the "Method" in the scan comment is correct.

It looks like a "projectName" and "teamName" field were added to the comments, but are not part of the decode method.  So CxFlow doesn't know they exist and the GitHub event type [here](https://github.com/checkmarx-ltd/cx-flow/blob/cfafb3bbedb6435f3e1ff91e905576c8cee0b5fb/src/main/java/com/checkmarx/flow/controller/FlowController.java#L241-L246) should actually be case 8 and the new fields should be added above it.

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by HussainS12** [comment]
Fixed in PR #941
