### ISSUE TITLE
broken XML schema link

### ISSUE THREAD

**Issue by warrior8792** [checkmarx-ltd/cx-flow#946]
### Description

The Checkmarx results XML schema link is still referring to a protected confluence section.  Refer to [this section](https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#data) of the documentation to observe.

### Expected Behavior
Navigation to the Results XML schema.

### Actual Behavior
Navigation to an internal confluence site.

### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by jbrotsos** [comment]
Hey @warrior8792 , what are you looking for in the XML report?

This has some info: https://checkmarx.atlassian.net/wiki/spaces/KC/pages/222101925/Get+Report+s+by+Id+-+GET+reports+sastScan+id+v8.6.0+and+up

But you can just also download an XML report from the Checkmarx SAST Manager UI to see a full XML report.

**Comment by warrior8792** [comment]
That works, although I would think fixing the link would be good for others as well?

I'm trying to use this information for Jira field mappings in CxFlow.

**Comment by jbrotsos** [comment]
I'll add the update to our backlog - please feel free to create other issues that become a blocker.

**Comment by jbrotsos** [comment]
Released in 1.6.32
