### ISSUE TITLE
Map latest scan custom fields to JIRA fields

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#950]
### Describe the problem

Scan custom fields were introduced recently in CxSAST 9.4 and in CxFlow, but they cannot be mapped into JIRA fields in CxFlow config.

### Proposed solution

Map new scan custom fields to CxFlow's JIRA field's type configuration, I suggest a new field type called `scan` or `cx-scan` or something that describes the cx-scan-custom-field.

Just for reference, in the code the project custom fields are described by a structure called [cxFields](https://github.com/checkmarx-ltd/cx-flow/blob/53ca4ef6b050ee8018716f71ad87e5fdb8bc2825/src/main/java/com/checkmarx/flow/dto/ScanRequest.java#L33) and the new scan custom fields in [scanFields](https://github.com/checkmarx-ltd/cx-flow/blob/53ca4ef6b050ee8018716f71ad87e5fdb8bc2825/src/main/java/com/checkmarx/flow/dto/ScanRequest.java#L34).

**Comment by itsKedar** [comment]
Fixed in 1.6.36 release
