### ISSUE TITLE
Code snippets include passwords

### ISSUE THREAD

**Issue by CxMichaelFowler** [checkmarx-ltd/cx-flow#964]
### Describe the problem

When a Jira case is created with code snippets this can include sensitive data such as passwords. Jira access much wider than access to the code bases and so this presents a security risk.

### Proposed solution

The ability to suppress code snippets for specific vulnerability types e.g. Use_Of_Hardcoded_Password and replace it with a warning or alternatively including a feature to automatically remove potentially sensitive data such as passwords from the snippets

**Comment by jbrotsos** [comment]
Workaround is to not create tickets for this Issue type.

**Comment by james-bostock-cx** [comment]
The problem with configuring CxFlow to not create Jira tickets for this vulnerability (issue) type is that, as a result, such issues might fall through the cracks. For this reason, I have reopened this issue.

Intuitively, it should not be too hard to implement:

- Add a list member to the `JiraProperties` class which contains a list of vulnerabilities for which code snippets should be supressed.
- Modify the `JiraService`.`getBody()` method to check against this list before inserting the code snippet.

**Comment by james-bostock-cx** [comment]
Closed by PR #976.
