### ISSUE TITLE
Ability to set post-action-scan based on config as code

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#970]
### Describe the problem

We want to allow our teams to pass in a post-action-postback-id which should trigger the action server side in Checkmarx, once Checkmarx finish a scan

### Proposed solution

introduce the ability to pass a post-action-id via config as code

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by itsKedar** [comment]
Fixed in 1.6.39 https://github.com/checkmarx-ltd/checkmarx-spring-boot-java-sdk/pull/281
