### ISSUE TITLE
Integration with MS-Teams channels rather than sending an email

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#971]
### Describe the problem

Similar to https://github.com/checkmarx-ltd/cx-flow/issues/967
But rather than sending an email which includes the PDF which shouldn't be available on Teams we would just like the summary (simiar to the PR decoration) or scan failure message to be reported in Teams

### Proposed solution

Introduce Teams as an additional tracker to include just scan summary/failure info
### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by itsKedar** [comment]
New feedback apps will be added in CxOne.
