### ISSUE TITLE
Support Jira Issue Summary for SCA tickets

### ISSUE THREAD

**Issue by warrior8792** [checkmarx-ltd/cx-flow#979]
### Describe the problem
SAST scan Jira ticketing has two properties to customize the Jira ticket summary (sast-issue-summary-format and sast-issue-summary-branch-format).  SCA scan ticketing does not have any properties for customization of Jira issue summaries.  

### Proposed solution

SCA scan ticketing needs to support equivalent properties to handle things like Git repos that have spaces in the names and other customization.  

### Additional details

> Add any other details / contexts / screenshots about the feature request.

**Comment by itsKedar** [comment]
Fixed in 1.6.41
