### ISSUE TITLE
GitHub PR decoration - Not escaping spaces

### ISSUE THREAD

**Issue by nirw** [checkmarx-ltd/cx-flow#983]
### Description

> when the path of file containing the vulnerability includes spaces those aren't escaped well and the link to the file is broken

### Expected Behavior
link to the file should be escaped and properly replace spaces with %20 (and possibly other special characters) for GitHub markdown

### Actual Behavior
link contains space and therefore doesn't work - see screenshot attached
### Reproduction

> Detail the steps taken to reproduce the issue
> 
> Where applicable, please include (exclude sensitive information):
>
> - Code of Files to reproduce the issue
> - Log files
> - Application settings
> - Screenshots

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)
![image](https://user-images.githubusercontent.com/1933763/160759374-7e7c0f5f-1820-4e4b-be00-edbd783cc819.png)

**Comment by itsKedar** [comment]
Fixed in 1.6.40 release
